### ISSUE TITLE
Adding "Works about" to HMO pages

### ISSUE THREAD

**Issue by ar2674** [project-lux/lux-frontend#100]
**Problem Description:**
There is textual work that should show on HMO pages that is not currently not shown. For the [example](https://lux-front-dev.collections.yale.edu/view/object/28aecd74-ba50-4e0e-b4e2-2804e9721468) below, there is an exhibition catalog about it but it does not show since we do not have a section to link it to. 

**Expected Behavior/Solution:**
Create a "works about" section (such as inscribed titles, Object types, etc) that lists the textual work related to the HMO page.  

**Requirements:**
"Works about" will list all applicable textual work results related to the HMO page. 

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [ ] Wireframe/Mockup - Mike
- [ ] Committee discussions - Sarah
- [ ] Feasibility/Team discussion - Sarah
- [ ] Backend requirements - TBD
- [ ] Frontend requirements- TBD
- [ ] Questions
- List of questions for discussions. Answers should be documented within the issue.

**UAT/LUX Examples:**
What it currently looks like: 
https://lux-front-dev.collections.yale.edu/view/object/28aecd74-ba50-4e0e-b4e2-2804e9721468
![image](https://github.com/project-lux/lux-frontend/assets/160149818/591c55b3-d90d-4f99-be66-733b68eab14a)

What it should look like: 
![100](https://github.com/project-lux/lux-frontend/assets/98550395/89e939ba-850a-4e80-9f07-65190fe984bb)

**Dependencies/Blocks:**

- Blocked By: Issues that are blocking the completion of the current issue.
- Blocking: Issues being blocked by the completion of the current issue.

**Related Github Issues:**
- https://github.com/project-lux/lux-frontend/issues/62

**Related links:**
- https://www.bugherd.com/projects/284041/tasks/2015

**Wireframe/Mockup:**
Place wireframe/mockup for the proposed solution at end of ticket.

**Comment by kamerynB** [comment]
@ar2674 It is HumanMadeObjects. Objects have a type of "HumanMadeObject" or "DigitalObject". You can see the example [here](https://lux-front-dev.collections.yale.edu/data/object/28aecd74-ba50-4e0e-b4e2-2804e9721468). At the very top of the record, you should see `type: "HumanMadeObject"`. This data is not important to users and is therefor not shown by the frontend.

**Comment by miketullo95** [comment]
@kamerynB I added my first pass of the wireframe but I couldn't find an example of a "works about" for https://lux-front-dev.collections.yale.edu/view/object/28aecd74-ba50-4e0e-b4e2-2804e9721468. Could you give me the links for what these works about would link out to? thanks!

**Comment by prowns** [comment]
dupe, closing per @kamerynB

**Comment by ar2674** [comment]
Dupe of https://github.com/project-lux/lux-frontend/issues/62
