### ISSUE TITLE
Handle Data constants updates in Front End 

### ISSUE THREAD

**Issue by clarkepeterf** [project-lux/lux-frontend#102]
**Problem Description:**
Data constants are a pain to re-generate every release. We are going to change the way we handle them so that they are based on AATs and remain static

**Expected Behavior/Solution:**
May need an endpoint that returns a LUX URI given an alternate identifer (such as Getty AAT) Depends on ML implementation

**Requirements:**
Need to know implementation of ML

**Needed for promotion:**

~~- [ ] Wireframe/Mockup - Mike~~
~~- [ ] Committee discussions - Sarah~~
~~- [ ] Feasibility/Team discussion - Sarah~~
~~- [ ] Backend requirements - TBD~~
~~- [ ] Frontend requirements- TBD~~
~~- [ ] Questions~~
~~- List of questions for discussions. Answers should be documented within the issue.~~

**UAT/LUX Examples:**

- TBD

**Dependencies/Blocks:**
- Blocked By: https://github.com/project-lux/lux-marklogic/issues/54
- Blocked By: https://github.com/project-lux/lux-middletier/issues/18
- updated dataset (after 3/1)

**Related Github Issues:**

**Related links:**

**Wireframe/Mockup:**

**Comment by roamye** [comment]
Wondering if this is still blocked by the data set...? it says 
"updated data set after 3/1" so should this still be blocked? 

cc: @prowns @clarkepeterf

**Comment by clarkepeterf** [comment]
It is blocked by https://github.com/project-lux/lux-marklogic/issues/54 which has not been implemented yet

**Comment by roamye** [comment]
@clarkepeterf so https://github.com/project-lux/lux-marklogic/issues/54 should no longer be blocked then? as the dataset was blocking it?

**Comment by clarkepeterf** [comment]
Yes we can unblock https://github.com/project-lux/lux-marklogic/issues/54

**Comment by kamerynB** [comment]
@roamye @prowns Propose close. This issue must have gotten lost in the weeds. #196 has replaced it.

**Comment by roamye** [comment]
Closing as a duplicate (from UAT)
