### ISSUE TITLE
Change "Work" label to "Occupations"

### ISSUE THREAD

**Issue by kamerynB** [project-lux/lux-frontend#105]
**Problem Description:**
The data is being parsed and returning "Work" as the primary name.

**Expected Behavior/Solution:**
If the label for "work" is caught in the frontend return "Occupations" instead.

**Requirements:**

- [x] Add conditional to change work to occupations in getAllClassifiedAs function in the PersonAndGroupParser
```
   if (label === config.dc.occupation) {
      label = 'Occupation'
   }
```

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [x] Wireframe/Mockup - Mike
- [ ] ~Committee discussions - Sarah~
- [ ] ~Feasibility/Team discussion - Sarah~
- [ ] ~Backend requirements - TBD~
- [x] Frontend requirements - Kam
- [ ] ~Questions~

**UAT/LUX Examples:**

- https://lux-front-dev.collections.yale.edu/view/person/4dc53d61-37e7-4a69-a05a-dbb8ce23c75f
- Navigate down and on the right-hand side, you will find the listing Occupation.

**Dependencies/Blocks:**
N/A

**Related Github Issues:**
N/A

**Related links:**

- Bugherd: https://www.bugherd.com/projects/284041/tasks/2008

**Wireframe/Mockup:**
Current:
![Screenshot 2024-02-27 at 12 17 17 PM](https://github.com/project-lux/lux-frontend/assets/140102078/963a5ca0-f8c5-4c01-99a4-38df538aec58)

Expected:
![Screenshot 2024-02-27 at 12 17 33 PM](https://github.com/project-lux/lux-frontend/assets/140102078/5e481a93-7d90-4409-959a-82d38b50f6d7)

**Comment by ar2674** [comment]
Approved per UAT

**Comment by prowns** [comment]
deployed
