### ISSUE TITLE
Add Concepts Influenced to events pages

### ISSUE THREAD

**Issue by kamerynB** [project-lux/lux-frontend#106]
**Problem Description:**
The events pages do no display concepts influenced.

**Expected Behavior/Solution:**
Add an accordion for Concepts Influenced on events pages.

**Requirements:**

- [x] Add configuration for HAL link on frontend

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [x] Wireframe/Mockup - Mike
- [ ] ~Committee discussions - Sarah~
- [ ] ~Feasibility/Team discussion - Sarah~
- [x] Backend requirements - HAL link (Peter)
- [x] Frontend requirements - Kam
- [ ] ~Questions~

**UAT/LUX Examples:**

- https://lux-front-tst.collections.yale.edu/view/activity/1f18ba99-f5f3-46ef-9c25-0ebcea1af8dd

**Dependencies/Blocks:**

- Blocked By: https://github.com/project-lux/lux-middletier/issues/20

**Related Github Issues:**
N/A

**Related links:**

- Bugherd: https://www.bugherd.com/projects/284041/tasks/2029

**Wireframe/Mockup:**
![Screenshot 2024-03-04 at 2 30 09 PM](https://github.com/project-lux/lux-frontend/assets/140102078/c368fabc-a772-47e2-b837-3c9fc14ee6f6)

**Comment by ar2674** [comment]
Approved per UAT

**Comment by prowns** [comment]
deployed
