### ISSUE TITLE
Add Places with Type accordion to concept pages

### ISSUE THREAD

**Issue by kamerynB** [project-lux/lux-frontend#107]
**Problem Description:**
The concept pages are missing an accordion that shows Places with Type

**Expected Behavior/Solution:**
There should be a Places with Type **Search Accordion** added.  

**Requirements:**

- [x] Add configuration for HAL link on frontend (https://github.com/project-lux/lux-middletier/issues/21)
- [x] The accordion label will be `Places with Type`

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [x] Wireframe/Mockup - Mike
- [ ] ~Committee discussions - Sarah~
- [ ] ~Feasibility/Team discussion - Sarah~
- [x] Backend requirements - HAL link (Peter)
- [x] Frontend requirements - Kam
- [ ] ~Questions~

**UAT/LUX Examples:**

- [Places with Type](https://lux-front-tst.collections.yale.edu/view/concept/ce2af8c9-1d34-46be-a3cb-434f332d678b)

**Dependencies/Blocks:**

- Blocked By: https://github.com/project-lux/lux-middletier/issues/21

**Related Github Issues:**
https://github.com/project-lux/lux-middletier/issues/21

**Related links:**

- Bugherd: https://www.bugherd.com/projects/284041/tasks/1888

**Wireframe/Mockup:**
![image](https://github.com/project-lux/lux-frontend/assets/140099762/13b4de89-21e2-43a1-835c-c8f4a00736fc)

**Comment by ar2674** [comment]
@clarkepeterf Do we want seperate HAL links for those listed under the requirements?

**Comment by ar2674** [comment]
We need HAL link and LUX examples by thursday.

**Comment by clarkepeterf** [comment]
@ar2674 yes please

@kamerynB is "Concepts with Type" a thing?

I think we just need:
Objects, Works, Places, and Events

There is already a "People and Groups with Type" accordion

**Comment by ar2674** [comment]
@clarkepeterf @kamerynB Places is all set by https://github.com/project-lux/lux-middletier/issues/21, is concepts with Type https://github.com/project-lux/lux-middletier/issues/34 ?

**Comment by kamerynB** [comment]
@clarkepeterf @ar2674 I created the HAL links and there are Concepts with Type. An example record is linked in the original comment. I'd like this to be promoted as the middletier issue 34 is already completed and deployed to DEV for testing.

**Comment by ar2674** [comment]
@kamerynB Thanks Kam, I have removed 36/37

**Comment by roamye** [comment]
Per UAT this is approved.

**Comment by roamye** [comment]
Looks good in prod, closing
