### ISSUE TITLE
Objects/Works Rights Info (from 831)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-frontend#11]
Problem Description: As part of #388 and #372 , we created a /content/rights-info page so that the 'Can I re-use it?' section can show rights information. However, we will want to revisit how to display this data at a future point. Objects can be linked to Units, which may have certain policies around rights to reproduction. However, it is really the Works carried by Objects which are subject to rights.

This ticket should be considered as part of the larger Rights Meta Issue: #1698 

~There is potentialy a rights profile being added to Marklogic: https://git.yale.edu/lux-its/marklogic/issues/1059, which would make it easy to just get the rights info for the Work carried by an Object, rather than getting the entire document~  Per Teams meeting of 11/3/23, there is not a data solution to this.

**Expected Behavior:** 
For any object that has a work use the following statement. "Rights information may be available on the associated Works page."
Also, change the text of the FAQ link in all Can I re-use it boxes to say "For more information about Rights and Usage, visit the LUX Frequently Asked Questions"

<img width="461" alt="image" src="https://github.com/project-lux/lux-frontend/assets/160149818/070b012f-b61e-43a2-8488-8d806a54b407">

Needed:

- [x] Requirements
- [x] wireframes/mock for Rights WG discussion
- [x] Mark as groomed on #1698 
- [ ] Update FAQ (post deployment)

Testing link: 
 - shows the change: https://lux-front-tst.collections.yale.edu/view/object/2e538bf0-faa7-4484-accf-43b5cde93c72
 - doesn't show the change: https://lux.collections.yale.edu/view/object/2e538bf0-faa7-4484-accf-43b5cde93c72

**Comment by ar2674** [comment]
Approved per UAT

**Comment by prowns** [comment]
deployed
