### ISSUE TITLE
Add ability to make nested search criteria the top level search criteria. 

### ISSUE THREAD

**Issue by ar2674** [project-lux/lux-frontend#110]
**Problem Description:**
Users do not have the ability to promote nested search criteria's in Advanced Search. If a user wanted to "promote" their nested search they would have to make a completely new search within AS. 

**Expected Behavior/Solution:**
A User will have the ability to promote a nested search as their top level search criteria by selecting [Promote Search] option in gear icon. 

**Requirements:**
- Gear icon will have the option [Promote Search] (option name can vary) 
- Gear icon option will be available to all searches besides the first one. (if possible, else option will be on all searches even first one) 
- When gear icon is selected, all searches above the search will delete and will start with the desired promoted search. 
- When gear icon is selected, all searches below the promoted search will remain under it. 
- Type will change to the correct Type dependent on the search that gets promoted. (ex: if the advances search was within Places, but now we promote a search that has to do with agents, then the type would be People & Groups.)

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [ ] Wireframe/Mockup - Mike
- [ ] Committee discussions - Sarah
- [ ] Feasibility/Team discussion - Sarah
- [ ] Backend requirements - TBD
- [ ] Frontend requirements- TBD
- [ ] Questions
- List of questions for discussions. Answers should be documented within the issue.

**UAT/LUX Examples:**
[Current: ](https://lux-front-dev.collections.yale.edu/view/results/places?q=%7B%22startPlaceOfAgent%22%3A%7B%22created%22%3A%7B%22aboutAgent%22%3A%7B%22OR%22%3A%5B%7B%22endAt%22%3A%7B%22name%22%3A%22Paris%22%7D%7D%2C%7B%22encountered%22%3A%7B%22name%22%3A%22the%22%7D%7D%5D%7D%7D%7D%7D)
![image](https://github.com/project-lux/lux-frontend/assets/160149818/88a3ed97-eb76-4c81-aed3-a71613918afd)
**Note: 
We no longer have gear options next to searches. We would have to think about how we want to display this option.** 

Expected: 
TBD - future work 

**Dependencies/Blocks:**

**Related Github Issues:**
- https://github.com/project-lux/lux-frontend/issues/30 **(dupe)**
- https://github.com/project-lux/lux-frontend/issues/136 (new ticket made by roamye) 

**Related links:**
Bugherd: https://www.bugherd.com/projects/284041/tasks/1526

**Wireframe/Mockup:**
Place wireframe/mockup for the proposed solution at end of ticket.

**Comment by roamye** [comment]
Closing as new issue was created: #136
