### ISSUE TITLE
Remove site verification file from repo

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-frontend#112]
**Problem Description:**
There's a Google site verification file in /client/public/. While it is required to be deployed with the Yale LUX site, it cannot be part of this public repo. 

**Expected Behavior/Solution:**
The file should rather be injected, probably via an environment variable, when being deployed, e.g. via Jenkins.

**Requirements:**
- [x] Remove the file from code
- [x] Add injection from Jenkins

**For UAT**
See that the source code https://github.com/project-lux/lux-frontend/tree/main/client/public does not contain the google42f9fb0e189ddb7c.html file anymore, but that you can still retrieve it from the deployed app: https://lux-front-tst.collections.yale.edu/google42f9fb0e189ddb7c.html

**Comment by gigamorph** [comment]
Deleted the file from the repo. It will be created by Jenkins during the build process.

**Comment by roamye** [comment]
@gigamorph is this issue still set to be deployed for 04-01? or is it fine to push it back as this tix is still in progress? let me know. thanks.

**Comment by roamye** [comment]
@gigamorph when I select the https://lux-front-tst.collections.yale.edu/google42f9fb0e189ddb7c.html, it brings me to a blank page. Should this be the case? I am unsure how to verify that we can still retrieve the file that was removed.

**Comment by gigamorph** [comment]
@roamye, it shouldn't. It should show the text
`google-site-verification: google42f9fb0e189ddb7c.html`. Can you check again?

**Comment by roamye** [comment]
Ahh okay. I had seen that but I had thought it was an error message. I understand the UAT now. Thanks @gigamorph

**Comment by roamye** [comment]
Approved by UAT

**Comment by roamye** [comment]
Closing as https://github.com/project-lux/lux-frontend/tree/main/client/public does not contain the google42f9fb0e189ddb7c.html file anymore.
