### ISSUE TITLE
Some Wikidata images are not rendering in IIIF viewer and returning 500 error upon request to server

### ISSUE THREAD

**Issue by kamerynB** [project-lux/lux-frontend#114]
**Problem Description:**
Some Wikidata images are failing to be retrieved from the manifest server. The requests are returning 500 error codes.

**Expected Behavior/Solution:**
The images should render.

**Requirements:**

- [x] Determine what is causing the problem and update these requirements accordingly

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [ ] ~Wireframe/Mockup - Mike~
- [ ] ~Committee discussions - Sarah~
- [ ] Feasibility/Team discussion - Sarah
- [ ] Backend requirements - TBD
- [ ] Frontend requirements - TBD
- [ ] ~Questions~

**UAT/LUX Examples:**

- https://lux-front-tst.collections.yale.edu/view/text/0c354407-170b-42d1-973d-b913ddeef68d

**Dependencies/Blocks:**
N/A

**Related Github Issues:**
N/A

**Related links:**

- Bugherd: https://www.bugherd.com/projects/284041/tasks/2051

**Wireframe/Mockup:**
N/A

**Comment by gigamorph** [comment]
For the example of 
https://lux-front-tst.collections.yale.edu/view/text/0c354407-170b-42d1-973d-b913ddeef68d,
the request for manifest is made for
https://manifests.collections.yale.edu/wikimedia/manifest/Old_New_York_2_The_Old_Maid_-_cover.png.

**Comment by gigamorph** [comment]
In agreement with with what @kamerynB suggested, the CDS2 manifest server was only letting JPEG images go through the processing. 
Began working on the manifest server with https://git.yale.edu/cultural-heritage-dam/cds2-manifest-server/issues/3.

**Comment by gigamorph** [comment]
Fixed and deployed the manifest server. LUX should work now.

**Comment by jffcamp** [comment]
I agree that this can be closed. The issue was due to a dependency on another system which has been remediated.

**Comment by kamerynB** [comment]
Closing the issue.
