### ISSUE TITLE
Update frontend Show all links to including sorting options when applicable

### ISSUE THREAD

**Issue by kamerynB** [project-lux/lux-frontend#123]
**Problem Description:**
When a user is on an entity page looking at related Events, the events are sorted. When they choose to "see all results" the subsequent results page down not sort the events.

**Expected Behavior/Solution:**
The events should be sorted when a user navigates to the results page from an entity page, where applicable.

**Requirements:**

- [x] Add conditional to determine if "sort=" is in the HAL link and to replace it with the correct parameter for the frontend

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [ ] ~Wireframe/Mockup - Mike~
- [ ] ~Committee discussions - Sarah~
- [ ] ~Feasibility/Team discussion - Sarah~
- [ ] ~Backend requirements - TBD~
- [x] Frontend requirements - Kam
- [ ] ~Questions~

**UAT/LUX Examples:**

- "Events Carried Out": https://lux-front-tst.collections.yale.edu/view/group/6086b58d-941d-41e3-87c1-e00e96952ffb
- "Events Containing Objects Created By": https://lux-front-tst.collections.yale.edu/view/person/c225d5e4-8767-4a25-802b-af054d5e8f52

**Dependencies/Blocks:**
N/A

**Related Github Issues:**
N/A

**Related links:**
N/A

**Wireframe/Mockup:**
N/A

**Comment by roamye** [comment]
Per UAT this is approved.

**Comment by roamye** [comment]
Looks good in prod closing
