### ISSUE TITLE
Implement Virtual Page View Tracking

### ISSUE THREAD

**Issue by clarkepeterf** [project-lux/lux-frontend#124]
**Problem Description:**
By default, SiteImprove only counts pageviews when the browser loads a new web page. Since LUX is a single-page application, it only tracks the first page a user visits. Further "page-views" or view changes are handled by React.

**Expected Behavior/Solution:**
Add [custom visit tracking](https://help.siteimprove.com/support/solutions/articles/80000448441-siteimprove-analytics-custom-visit-tracking) to LUX so that virtual "page-views" are tracked as regular page views in SiteImprove

From the link above, we should be able to use the following to track page views:
```
_sz.push(["trackdynamic",{
       "url": "new page URL",
       "ref": "current page URL",
       "title": "new page title"
}]);
```

**Requirements:**
Test behavior of the [custom visit tracking](https://help.siteimprove.com/support/solutions/articles/80000448441-siteimprove-analytics-custom-visit-tracking). It should work with page view changes via `history.push()`, react router Links, and any other mechanism that is used to change the view in LUX

See also: [Analytics Requirements](https://docs.google.com/spreadsheets/d/1VICQvsPW2IJpkOFV20dGoIe5DsiLp-geYW_d3nXtcZk/edit#gid=0)

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

~~- [ ] Wireframe/Mockup - Mike~~
~~- [ ] Committee discussions - Sarah~~
~~- [ ] Feasibility/Team discussion - Sarah~~
~~- [ ] Backend requirements - TBD~~
~~- [ ] Frontend requirements- TBD~~
~~- [ ] Questions~~
~~- List of questions for discussions. Answers should be documented within the issue.~~

**UAT/LUX Examples:**

SiteImprove tracks all page views. Should be able to go from homepage to a search to a record and all of those should be tracked.

Expected Reports for UAT: [Analytics Requirements](https://docs.google.com/spreadsheets/d/1VICQvsPW2IJpkOFV20dGoIe5DsiLp-geYW_d3nXtcZk/edit#gid=0)
Site Improve Prod: https://my2.siteimprove.com/Analytics/359298/Custom/EventTracking/Index

**Dependencies/Blocks:**

~~- Blocked By: Issues that are blocking the completion of the current issue.~~
~~- Blocking: Issues being blocked by the completion of the current issue.~~

**Related Github Issues:**

- Meta issue: https://github.com/project-lux/lux-frontend/issues/51

**Related links:**
- Rechecking of all SI events with correct URL page | [spreadsheet](https://docs.google.com/spreadsheets/d/1INlt1C-e3lnJ6ulDb_8w7akFcz9U8WCj1jn_EBzOW8c/edit#gid=0)  (tst) 

**Wireframe/Mockup:**
~~Place wireframe/mockup for the proposed solution at end of ticket.~~

**Comment by kamerynB** [comment]
Currently deployed to DEV for testing purposes.

cc: @roamye @prowns @jffcamp

**Comment by roamye** [comment]
124 prevents events from #90 and #91 from working.

**Comment by roamye** [comment]
all SI events are being captured correctly in prod. Closing.
