### ISSUE TITLE
Add Events with Type accordion to concept pages

### ISSUE THREAD

**Issue by prowns** [project-lux/lux-frontend#128]
**Problem Description:**
The concept pages are missing an accordion that shows Events with Type.

**Expected Behavior/Solution:**
There should be an Events with Type **Search Accordion** added.

**Requirements:**

- [x]  Add configuration for HAL link on frontend - https://github.com/project-lux/lux-middletier/issues/34 
- [x] The accordion label will be `Events with Type`

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [x] Wireframe/Mockup
- [ ] ~Committee discussions - Sarah~
- [ ] ~Feasibility/Team discussion - Sarah~
- [ ] ~Backend requirements - TBD~
- [ ] Frontend requirements - Kam
- [ ] ~Questions~

**UAT/LUX Examples:**

- Exhibitions: https://lux-front-tst.collections.yale.edu/view/concept/88af90e3-d194-4bfb-aa8c-0998cdf7e679

**Dependencies/Blocks:**

- Blocked By: Issues that are blocking the completion of the current issue.

**Related Github Issues:**

- https://github.com/project-lux/lux-middletier/issues/34

**Related links:**

- These links can consist of resources, bugherds, etc.

**Wireframe/Mockup:**
![image](https://github.com/project-lux/lux-frontend/assets/140099762/71d703f9-cfd5-42a7-8ea8-341e472c70e2)

**Comment by roamye** [comment]
Per UAT this is approved.

**Comment by roamye** [comment]
Looks good in prod. Closing
