### ISSUE TITLE
Change instances of "Campus Division" to "Responsible Unit"

### ISSUE THREAD

**Issue by kamerynB** [project-lux/lux-frontend#132]
**Problem Description:**
The "Campus Division" label is an inaccurate label for the data being rendered. 

**Expected Behavior/Solution:**
Change hard coded instances of "Campus Division" to "Responsible Unit". The JSON used to form the "Campus Division" faceted search should be updated once the query is updated in the backend.

**Requirements:**

- [x] Update on entity pages
- [x] Update in facet accordions labels
- [x] Change the JSON used in the config
- [x] Remove the getCollections functionality and replace with `itemDepartment` HAL link

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [ ] ~Wireframe/Mockup - Mike~
- [ ] ~Committee discussions - Sarah~
- [ ] ~Feasibility/Team discussion - Sarah~
- [ ] ~Backend requirements - TBD~
- [x] Frontend requirements - Kam
- [ ] ~Questions~

**UAT/LUX Examples:**

- Any Object results: https://lux-front-tst.collections.yale.edu/view/results/objects/?q=%7B%22text%22%3A%22ochre%22%2C%22_lang%22%3A%22en%22%7D&sq=ochre (tst) 
- https://lux.collections.yale.edu/view/results/objects/?q=%7B%22text%22%3A%22ochre%22%2C%22_lang%22%3A%22en%22%7D&sq=ochre (prod) 

**Dependencies/Blocks:**

- Blocked By: 
    - https://github.com/project-lux/lux-marklogic/issues/68

**Related Github Issues:**
META: https://github.com/project-lux/lux-frontend/issues/153

**Related links:**
N/A

**Wireframe/Mockup:**
Current: 
![image](https://github.com/project-lux/lux-frontend/assets/163148482/4c2bd7a9-1e8f-414a-ae1e-3ca24636a78b)
Updated: 
![image](https://github.com/project-lux/lux-frontend/assets/163148482/6111b499-0250-46e4-8ad2-e0c25b84984e)

**Comment by roamye** [comment]
@kamerynB can we add UAT links if possible? this way we can move it forward for prioritization review.

**Comment by roamye** [comment]
@kamerynB is it ok to remove the forming label?

**Comment by kamerynB** [comment]
@roamye Removed

**Comment by clarkepeterf** [comment]
@kamerynB  I have updated ML in DEV such that it is ready to support this ticket

**Comment by roamye** [comment]
@kamerynB is this reviewable again? If not can you mark it as so when you are done? thanks

**Comment by kamerynB** [comment]
@roamye All set!

**Comment by roamye** [comment]
looks good in prod, closing.
