### ISSUE TITLE
Fix Works About or Depicting People and Groups search links

### ISSUE THREAD

**Issue by kamerynB** [project-lux/lux-frontend#135]
**Problem Description:**
The links in the `Works About or Depicting People and Groups` accordion on concept pages currently returns an error.

**Expected Behavior/Solution:**
The links should redirect to the results page with valid results.

**Requirements:**

- [x] Update the `formatSearchJson` function

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [ ] ~Wireframe/Mockup - Mike~
- [ ] ~Committee discussions - Sarah~
- [ ] ~Feasibility/Team discussion - Sarah~
- [ ] ~Backend requirements - TBD~
- [ ] Frontend requirements - Kam
- [ ] ~Questions~

**UAT/LUX Examples:**

- https://lux-front-dev.collections.yale.edu/view/concept/bf572421-ad85-4b8b-9d14-d631371375df --> Test any `Show all x results` links in the `Works About or Depicting People and Groups` accordion

**Dependencies/Blocks:**
N/A

**Related Github Issues:**
N/A

**Related links:**

- Bugherd: https://www.bugherd.com/projects/284041/tasks/2079

**Wireframe/Mockup:**
There should be no change to the frontend.

**Comment by roamye** [comment]
Per UAT this is approved.

**Comment by roamye** [comment]
Looks good in prod, closing
