### ISSUE TITLE
Change alignment of single/multiple fields in advanced search to connect to "add row" options.

### ISSUE THREAD

**Issue by roamye** [project-lux/lux-frontend#138]
**Problem Description:**
In Advanced Search, a blue line is connected to each single/multiple field. This blue line follows a path to it's respective 'add row' option. However since this line is not connected to the 'add row' option it is hard to understand which single/multiple field it belongs without using the [-] option. 

**Expected Behavior/Solution:**
Add a horizontal line to the vertical line which points to which 'add row' option belongs to the single/multiple field above. 

**Requirements:**
- [x] From the single/multiple fields there will be a blue horizontal line attached to the original blue vertical line  which will point to its respective "add row" option.
- [x] [-] [+] will continue to work the same as before the change. Such that it will hide/show the vertical and horizontal lines attached to the "add row" options

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [x] Wireframe/Mockup - Mike
- [x] Committee discussions - Sarah
- [ ] ~Feasibility/Team discussion - Sarah~
- [ ] ~Backend requirements - TBD~
- [x] Frontend requirements- TBD
- [ ] Questions
- List of questions for discussions. Answers should be documented within the issue.

**UAT/LUX Examples:**
Current [design](https://lux-front-tst.collections.yale.edu/view/results/objects?q=%7B%22AND%22%3A%5B%7B%22OR%22%3A%5B%7B%22carries%22%3A%7B%22aboutConcept%22%3A%7B%22name%22%3A%22Dog%22%7D%7D%7D%2C%7B%22name%22%3A%22Dog%22%7D%5D%7D%5D%7D)

**Dependencies/Blocks:**
N/A

**Related Github Issues:**
N/A

**Related links:**
- Bugherd: https://www.bugherd.com/projects/284041/tasks/2074

**Wireframe/Mockup:**
Current:
![Image](https://github.com/project-lux/lux-frontend/assets/140102078/a7fd508d-8101-4605-a6bd-37a0b8f5411c)

Proposed: 
![Image](https://github.com/project-lux/lux-frontend/assets/98550395/6e165036-216c-46d2-9f21-0596b4468ce5)

**Comment by kamerynB** [comment]
I'd like to revisit this after the deployment on 4/1 as removing the Add Row buttons under the single field relationships may help clarify where the buttons relate to.

@jffcamp @prowns @roamye

**Comment by roamye** [comment]
we need to add the blue line to the mockup. have it make a right turn to the "add row" please @miketullo95

**Comment by miketullo95** [comment]
@prowns @roamye wireframe added

**Comment by roamye** [comment]
@kamerynB can the status of this be moved to Reviewable? or is this still being worked on?

**Comment by roamye** [comment]
Approved by UAT

**Comment by roamye** [comment]
Looks good in prod, close.
