### ISSUE TITLE
Advanced Search: Selector for People/Group type

### ISSUE THREAD

**Issue by roamye** [project-lux/lux-frontend#141]
**Problem Description:**
We have the ability to facet by person or group in the Refinement section of People & Groups, but we do not have this same option available in advanced search single field. 

**Expected Behavior/Solution:**
Modify the Single Field to include the selection of "Person or Group" which will contain a Person checkbox and Group checkbox. Which will act as a boolean. 

NOTE: confirmed that this should also appear as a facet option

**Requirements:**
Advanced search single field will include the selection of "Person Or Group" which will contain Person and Group checkbox options. 

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [x] Wireframe/Mockup - Mike 
_Person checkbox and Group checkbox or a dropdown that will show such options?_ Checkbox
- [x] MT ticket for configuration - Peter
- [x] Committee discussions - Sarah
- [x] Feasibility/Team discussion - Sarah
- [x] Backend requirements - TBD
- [x] Frontend requirements- TBD
- [x] Questions
- How will we decide which way we would like to display the options Person or Group? 
- It is best to use checkboxes such as 'Is Online' single field does. 

**UAT/LUX Examples:**
- [Advanced Search](https://lux-front-tst.collections.yale.edu/view/results/people?q=%7B%22AND%22%3A%5B%7B%22startAt%22%3A%7B%22name%22%3A%22zurich%22%7D%7D%2C%7B%22recordType%22%3A%22Group%22%7D%5D%7D)
- https://lux-front-tst.collections.yale.edu/view/results/people?q=%7B%22AND%22%3A%5B%7B%22recordType%22%3A%22Group%22%7D%5D%7D (tst)
- https://lux.collections.yale.edu/view/results/people?q=%7B%22AND%22%3A%5B%7B%22recordType%22%3A%22Group%22%7D%5D%7D (prod) 

**Dependencies/Blocks:**
This should be deployed concurrently with https://github.com/project-lux/lux-marklogic/issues/75

**Related Github Issues:**
- https://github.com/project-lux/lux-marklogic/issues/75
**Related links:**
Bugherd: https://www.bugherd.com/projects/284041/tasks/2062

**Wireframe/Mockup:**
![141](https://github.com/project-lux/lux-frontend/assets/98550395/df9fd58e-90a0-478a-88ab-e456691615d2)

**Comment by roamye** [comment]
@clarkepeterf pls add middle-tier ticket here when it is created. thank you.

**Comment by roamye** [comment]
@miketullo95 please add a mockup for this. thank you.

**Comment by miketullo95** [comment]
added mockup

**Comment by prowns** [comment]
Discussed at 3/28 team meeting.  Ok to move forward with this.  Noted that it is adv. search and facet.

**Comment by clarkepeterf** [comment]
@kamerynB I have the ML implementation ready for this. Let me know when you are ready to move forward with the frontend changes and I will make sure it is available in DEV for testing

**Comment by kamerynB** [comment]
@clarkepeterf I'm going to add this to this milestone. If you can have it in DEV sooner rather than later that would be great.

**Comment by clarkepeterf** [comment]
@kamerynB it's available in DEV now. This is its entry in the advanced search config:
```
            "recordType": {
                "label": "Person or Group",
                "helpText": "Search only records that are a Person or search only for records that are a Group",
                "relation": "text",
                "allowedOptionsName": "keyword"
            },
```

**Comment by azaroth42** [comment]
UAT: https://lux-front-tst.collections.yale.edu/view/results/people?q=%7B%22AND%22%3A%5B%7B%22recordType%22%3A%22Group%22%7D%5D%7D

**Comment by roamye** [comment]
Approved per UAT

**Comment by roamye** [comment]
Looks good in prod, closing issue.
