### ISSUE TITLE
Remove "object" section in Event records which contain information on Exhibition Sets

### ISSUE THREAD

**Issue by roamye** [project-lux/lux-frontend#142]
**Problem Description:**
When there are multiple exhibition sets in an event record it can be hard for a user to differentiate between them. 

After UAT discussion 4/4, core team had decided to remove the "objects" and it's information, as users could see this information by selecting the "show all results" under the entity page and then faceting by YUAG/YCBA. 

**Expected Behavior/Solution:**
The "Object" sections will be removed from the event entity page. 

~Possible ideas were discussed:~
~Adding the exhibition on the right hand side, such as:~ 
  - ~YBCA exhibit set for [exhibit name]~
  - ~YUAG exhibit set for [exhibit name]~

~We could also get feedback through user testing to clarify what solution would be better~

**Requirements:**
- "Object" section and all it's information will no longer show under the About of an Event record. 

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [x] Wireframe/Mockup - Mike
- [X] Committee discussions - Sarah (Interactions, if needed) 
- [x] Feasibility/Team discussion - Sarah - should be unit data solution
- [x] Backend requirements - TBD
- [x] Frontend requirements- TBD
- [X] Questions
- is there a way to shorten the label so that its not repeating the name of the exhibit? 
- The possible solution section for possible ideas appends the unit name in front of the current primary name of the exhibition set. Is this ok, or is it important to have consistent labels?

**UAT/LUX Examples:**
[Event Record: Colorful Impressions](https://lux-front-tst.collections.yale.edu/view/activity/ef9bfa8b-1d19-4b44-a004-a5ab75cdf6d7) (tst) 
- https://lux.collections.yale.edu/view/activity/ef9bfa8b-1d19-4b44-a004-a5ab75cdf6d7 (prod) 

**Dependencies/Blocks:**
- Blocked By: Data. We currently do not have the data to do this. 
- Blocking: Issues being blocked by the completion of the current issue.

**Related Github Issues:**

**Related links:**
BugHerd: https://www.bugherd.com/projects/284041/tasks/2068
CHIT Meeting [3/14](https://docs.google.com/document/d/1Dke3UQokjVaXtqRsvj-4n8yc83dqtV4awgYRjY1gWg8/edit)

**Wireframe/Mockup:**
Current:
![image](https://github.com/project-lux/lux-frontend/assets/163148482/0c901c64-de5d-426f-ba64-6975ecccfed2)

New: 
Note: Identifiers will not be shown as we removed these in #93 
![image](https://github.com/project-lux/lux-frontend/assets/163148482/3836a8db-a5f1-4d35-bceb-e156c03bb32c)

**Comment by roamye** [comment]
Scope needs to be re-done as we want to remove the "objects" section to no longer include the Exhibit links.

**Comment by roamye** [comment]
@miketullo95 @prowns can this be put into prioritzation review to be promoted as blocked? It is blocked by data but the tix is formed.

**Comment by prowns** [comment]
@roamye  - it is already in backlog

**Comment by roamye** [comment]
Please note the mockup includes identifiers as it was created before #93 was complete, however the tst link will not show this due to #93 .

**Comment by roamye** [comment]
Objects are removed from prod, good to close.
