### ISSUE TITLE
Remove/Suppress 'How Do I See it?' YUL links 

### ISSUE THREAD

**Issue by roamye** [project-lux/lux-frontend#143]
**Problem Description:**
When a user selects an object record, "The Objects Includes The Following Works" section lists all corresponding YUL links in the 'How Do I See it?' section. This is difficult for users to understand which links correspond to which works as they are in different sections and are not aligned together. 

Additionally, all YUL links can also be seen within each work record a user selects. So users may not need the 'How Do I See it?' section on the object record. 

Note: We are changing the 'This object includes the following works' to display 5 result cards. (See related github below) 

**Expected Behavior/Solution:**
Remove or Suppress the YUL links in the 'How Do I See it?' section. 

**Requirements:**
- [ ] Either, the YUL links are removed from the object record OR YUL links are suppressed in the object record. 

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [ ] Wireframe/Mockup - Mike
- [ ] Committee discussions - Sarah
- [ ] Feasibility/Team discussion - Sarah
- [ ] Backend requirements - TBD
- [ ] Frontend requirements- TBD
- [ ] Questions
- List of questions for discussions. Answers should be documented within the issue.

**UAT/LUX Examples:**
Object record: [1976 Folio 67 ](https://lux.collections.yale.edu/view/object/f205a441-5895-4328-8ad8-655f56f2a7ce)

**Dependencies/Blocks:**

- Blocked By: Issues that are blocking the completion of the current issue.
- Blocking: Issues being blocked by the completion of the current issue.

**Related Github Issues:**
https://github.com/project-lux/lux-frontend/issues/85 (results card change for 'this object includes the following works' and 'this work includes the following object') 

**Related links:**
CHIT meeting [3/14](https://docs.google.com/document/d/1Dke3UQokjVaXtqRsvj-4n8yc83dqtV4awgYRjY1gWg8/edit)

**Wireframe/Mockup:**
Place wireframe/mockup for the proposed solution at end of ticket.

**Comment by roamye** [comment]
This issue has been added to the next ticket forming meeting.

**Comment by azaroth42** [comment]
Propose that this should be a data pipeline issue, not front end

**Comment by roamye** [comment]
@kkdavis14 to follow up.

**Comment by kkdavis14** [comment]
https://github.com/project-lux/data-pipeline/issues/23

**Comment by roamye** [comment]
Closing issue as this belong in pipeline repo. Thank you @kkdavis14
