### ISSUE TITLE
Remove the Add Button in advanced search on non-group fields

### ISSUE THREAD

**Issue by kamerynB** [project-lux/lux-frontend#149]
**Problem Description:**
The Add Row button that is attached to single fields should not exists as they should only be single relationships.

**Expected Behavior/Solution:**
The Add Row button should be removed from the single field options. Users can continue to add nested relationships in single fields where applicable.

**Requirements:**

- [x] Remove the Add Row button from the relationship component
- [x] Test

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [x] Wireframe/Mockup - Mike
- [ ] ~Committee discussions - Sarah~
- [ ] ~Feasibility/Team discussion - Sarah~
- [x] Backend requirements - ~Need to determine if ML config will need updating but most likely not~
- [x] Frontend requirements - Kam
- [ ] ~Questions~

**UAT/LUX Examples:**
NOTE: Any advanced search should reflect this change but the below link is directly from the Bugherd.

- https://lux-front-tst.collections.yale.edu/view/results/objects?q=%7B%22OR%22%3A%5B%7B%22name%22%3A%22dog%22%7D%2C%7B%22AND%22%3A%5B%7B%22classification%22%3A%7B%22name%22%3A%22dog%22%7D%7D%5D%7D%5D%7D
- https://lux.collections.yale.edu/view/results/objects?q=%7B%22OR%22%3A%5B%7B%22name%22%3A%22dog%22%7D%2C%7B%22AND%22%3A%5B%7B%22classification%22%3A%7B%22name%22%3A%22dog%22%7D%7D%5D%7D%5D%7D (prod)

**Dependencies/Blocks:**
N/A

**Related Github Issues:**
N/A

**Related links:**

- Bugherd: https://www.bugherd.com/projects/284041/tasks/2070

**Wireframe/Mockup:**
Current:
![Screenshot 2024-03-22 at 11 17 36 AM](https://github.com/project-lux/lux-frontend/assets/140102078/46b6c280-7f41-45bf-bcab-9da2771c2773)

Expected:
![Screenshot 2024-03-22 at 11 17 14 AM](https://github.com/project-lux/lux-frontend/assets/140102078/effb91d2-c800-4906-b293-8726a839d77d)

**Comment by roamye** [comment]
Approved by UAT

**Comment by roamye** [comment]
Closing as it looks good in Prod.
