### ISSUE TITLE
Remove the Works About or Depicting People and Groups accordion on concept pages

### ISSUE THREAD

**Issue by kamerynB** [project-lux/lux-frontend#155]
**Problem Description:**
The current accordion for `Works About or Depicting People and Groups` is not needed as the data is rendered in `Related People and Groups`.

**Expected Behavior/Solution:**
The accordion will not appear.

**Requirements:**

- [x] Remove the HAL link config

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [x] Wireframe/Mockup - Mike
- [ ] ~Committee discussions - Sarah~
- [ ] ~Feasibility/Team discussion - Sarah~
- [x] Backend requirements - Kam, remove HAL link in middle tier
- [x] Frontend requirements - Kam
- [ ] ~Questions~

**UAT/LUX Examples:**

- https://lux-front-tst.collections.yale.edu/view/concept/bb258a2e-5050-4bef-93f6-ac24276f1878
- https://lux.collections.yale.edu/view/concept/bb258a2e-5050-4bef-93f6-ac24276f1878 (prod)

**Dependencies/Blocks:**
N/A

**Related Github Issues:**

- https://github.com/project-lux/lux-middletier/issues/46

**Related links:**

- Bugherd: https://www.bugherd.com/projects/284041/tasks/2094

**Wireframe/Mockup:**
Current:
![Screenshot 2024-03-28 at 8 57 11 AM](https://github.com/project-lux/lux-frontend/assets/140102078/7db7effb-6251-4009-a480-47f8ae189b81)

Expected:
![Screenshot 2024-03-28 at 8 57 04 AM](https://github.com/project-lux/lux-frontend/assets/140102078/500bd0bf-b310-4998-8a2b-0a8e682c198f)

**Comment by roamye** [comment]
Approved by UAT

**Comment by roamye** [comment]
Closing, looks good in prod.
