### ISSUE TITLE
Simple Search Site Improve Events

### ISSUE THREAD

**Issue by kamerynB** [project-lux/lux-frontend#160]
**Problem Description:**
There are SI events missing on simple search.

**Expected Behavior/Solution:**
Add or update SI events on simple search.

**Requirements:**

- [x] Add event on simple search submit button
    - Category: Search Button
    - Action: Submit
    - Label: Simple Search

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [ ] ~Wireframe/Mockup - Mike~
- [ ] ~Committee discussions - Sarah~
- [ ] ~Feasibility/Team discussion - Sarah~
- [ ] ~Backend requirements - TBD~
- [x] Frontend requirements - Kam
- [ ] Questions

**UAT/LUX Examples:**

View `Submit Simple Search` report: 
https://my2.siteimprove.com/Analytics/375000/Custom/EventTracking/Index/1?SearchField=&Query=search+button
Verify Category, Action, and Labels appear correctly.

**Dependencies/Blocks:**
N/A

**Related Github Issues:**

- #90 
- #91 

**Related links:**
For more information on SI Events please view the documentation here:
https://docs.google.com/document/d/1jsH4ckYOW7ykXlKACctZOP1IpxYnGaRIRPGDiuUbGMQ/edit

**Wireframe/Mockup:**
N/A

**Comment by roamye** [comment]
Approved per UAT

**Comment by roamye** [comment]
capturing events in prod - good to close.
