### ISSUE TITLE
Advanced Search Site Improve events

### ISSUE THREAD

**Issue by kamerynB** [project-lux/lux-frontend#161]
**Problem Description:**
There are SI events missing on advanced search events.

**Expected Behavior/Solution:**
Add or update SI events on advanced search.

**Requirements:**

- [x] User navigates to advanced search from the landing page
    - Category: Search Switch
    - Action: Clicked
    - Label: To Advanced Search `<tab>`
- [x] Submit an advanced search
    - Category: Search Button
    - Action: Submit
    - Label: Advanced Search
- [x] User opens or closes advanced search section
    - Category: Collapse Button
    - Action: Open/Close
    - Label: Advanced Search

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [ ] ~Wireframe/Mockup - Mike~
- [ ] ~Committee discussions - Sarah~
- [ ] ~Feasibility/Team discussion - Sarah~
- [ ] ~Backend requirements - TBD~
- [ ] Frontend requirements - Kam
- [ ] Questions

**UAT/LUX Examples:**
View `User Navigates to Advanced Search from Landing Page` report:
https://my2.siteimprove.com/Analytics/375000/Custom/EventTracking/Index/1?SearchField=&Query=Search+Switch
Verify Category, Action and Label appear correctly. 

View `Submits an Advanced Search` report: 
https://my2.siteimprove.com/Analytics/375000/Custom/EventTracking/Index/1?SearchField=&Query=search+button
Verify Category, Action and Label appear correctly. 

View `User Opens or Closes Advanced Search Settings` report: 
https://my2.siteimprove.com/Analytics/375000/Custom/EventTracking/Index/1?SearchField=&Query=collapse
Verify Category, Action and Label appear correctly. 

**Dependencies/Blocks:**
N/A

**Related Github Issues:**

- #90 
- #91 

**Related links:**
For more information on SI Events please view the documentation here:
https://docs.google.com/document/d/1jsH4ckYOW7ykXlKACctZOP1IpxYnGaRIRPGDiuUbGMQ/edit

**Wireframe/Mockup:**
N/A

**Comment by roamye** [comment]
@kamerynB do we want to remove "User navigates to advanced search from the landing page" from this ticket? it is already listed in https://github.com/project-lux/lux-frontend/issues/162 with a different name of "Switch to Advanced Search from landing page"

**Comment by prowns** [comment]
@roamye - "Switch to Advanced Search from landing page" - does not exist.  It should just be "Switch to Advanced Search" which is a specific action from a results page.  Can you update that on 162?

**Comment by roamye** [comment]
Approved per UAT

**Comment by roamye** [comment]
capturing events in prod good to close.
