### ISSUE TITLE
Search Toggle Site Improve Events

### ISSUE THREAD

**Issue by kamerynB** [project-lux/lux-frontend#162]
**Problem Description:**
There are SI events missing when toggling between simple and advanced search.

**Expected Behavior/Solution:**
Add or update SI events on toggling between simple and advanced search.

**Requirements:**

- [x] Switch to Advanced Search button
    - Category: Search Switch
    - Action: Clicked
    - Label: To Advanced Search
- [x] Close Switch to Simple Search button
    - Category: Search Switch
    - Action: Clicked
    - Label: Cancel Switch to Simple Search
- [x] Continue Switch to Simple Search button
    - Category: Search Switch
    - Action: Clicked
    - Label: Continue to Simple Search

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [ ] ~Wireframe/Mockup - Mike~
- [ ] ~Committee discussions - Sarah~
- [ ] ~Feasibility/Team discussion - Sarah~
- [ ] ~Backend requirements - TBD~
- [ ] Frontend requirements - Kam
- [ ] Questions

**UAT/LUX Examples:**
View Site Improve: `Search Switch`  report: 
https://my2.siteimprove.com/Analytics/375000/Custom/EventTracking/Index/1?SearchField=&Query=search+switch
- Verify Category, Action, and Labels appear correctly.

**Dependencies/Blocks:**
N/A

**Related Github Issues:**

- #90 
- #91 

**Related links:**
For more information on SI Events please view the documentation here:
https://docs.google.com/document/d/1jsH4ckYOW7ykXlKACctZOP1IpxYnGaRIRPGDiuUbGMQ/edit

**Wireframe/Mockup:**
N/A

**Comment by roamye** [comment]
Approved per UAT

**Comment by roamye** [comment]
It is capturing the events in prod. good to close.
