### ISSUE TITLE
Facets Site Improve Events

### ISSUE THREAD

**Issue by kamerynB** [project-lux/lux-frontend#163]
**Problem Description:**
There are SI events missing on advanced search events.

**Expected Behavior/Solution:**
Add or update SI events on advanced search.

**Requirements:**

- [x] User selects a facet accordion
    - Category: Facets Accordion Item
    - Action: Open/Close
    - Label: Facet `<name of facet>`
- [x] User checks a facet checkbox
    - Category: Facets Checkbox
    - Action: Checked
    - Label: Facet `<name of entity>`
- [x] User unchecks a facet checkbox
    - Category: Facets Checkbox
    - Action: Unchecked
    - Label: Facet `<name of entity>`
- [x] User deselects a facet from the Selected Filters
    - Category: Facets Selected Filters
    - Action: Remove
    - Label: Facet`<name of entity>`
- [x] User selects Clear All facets from the Selected Filters
    - Category: Facets Selected Filters
    - Action: Selected
    - Label: Facet Clear All

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [ ] ~Wireframe/Mockup - Mike~
- [ ] ~Committee discussions - Sarah~
- [ ] ~Feasibility/Team discussion - Sarah~
- [ ] ~Backend requirements - TBD~
- [ ] Frontend requirements - Kam
- [ ] Questions

**UAT/LUX Examples:**
View `User selects a facet accordion` report: 
https://my2.siteimprove.com/Analytics/375000/Custom/EventTracking/Index/1?SearchField=&Query=facets+acco
-  Verify Category, Action, and Labels appear correctly.

View `User checks a facet checkbox` | 1User unchecks a facet checkbox` reports:  
https://my2.siteimprove.com/Analytics/375000/Custom/EventTracking/Index/1?SearchField=&Query=facets+checkbox
- Verify Category, Action, and Labels appear correctly.

View `User deselects a facet from the Selected Filters` | `User selects Clear All facets from the Selected Filters` reports: 
https://my2.siteimprove.com/Analytics/375000/Custom/EventTracking/Index/1?SearchField=&Query=facets+selec
- Verify Category Action, and Labels appear correctly.

**Dependencies/Blocks:**
N/A

**Related Github Issues:**

- #90 
- #91 

**Related links:**
For more information on SI Events please view the documentation here:
https://docs.google.com/document/d/1jsH4ckYOW7ykXlKACctZOP1IpxYnGaRIRPGDiuUbGMQ/edit

**Wireframe/Mockup:**
N/A

**Comment by roamye** [comment]
Approved per UAT

**Comment by roamye** [comment]
SI events are being captured from prod. Looks good to close.
