### ISSUE TITLE
Entity Links Site Improve Events

### ISSUE THREAD

**Issue by kamerynB** [project-lux/lux-frontend#164]
**Problem Description:**
There are SI events missing on entity links.

**Expected Behavior/Solution:**
Add or update SI events on entity links.

**Requirements:**

- [x] User selects an entity link
    - We want to track the place where a user selected an entity link. Below are the Labels that will be implemented to track this. All of these will use the same Action and Category.
    - Category: Entity Link
    - Action: Clicked
    - Label:
        - [x] Breadcrumb Link
        - [x] Results Snippet Link
        - [x] Accordion `<accordion name>`
        - [x] Hierarchy Link
        - [x] Entity Link (any entity link not associated with a specific action)

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [ ] ~Wireframe/Mockup - Mike~
- [ ] ~Committee discussions - Sarah~
- [ ] ~Feasibility/Team discussion - Sarah~
- [ ] ~Backend requirements - TBD~
- [ ] Frontend requirements - Kam
- [ ] Questions

**UAT/LUX Examples:**
1. Click URL: https://my2.siteimprove.com/Analytics/375000/Custom/EventTracking/Index/1?SearchField=&Query=entity+link
2. View Report for SI Entity Link. 
3. Verify Category, Action, and Labels appear correctly. 

**Dependencies/Blocks:**
N/A

**Related Github Issues:**

- #90 
- #91 

**Related links:**
For more information on SI Events please view the documentation here:
https://docs.google.com/document/d/1jsH4ckYOW7ykXlKACctZOP1IpxYnGaRIRPGDiuUbGMQ/edit

**Wireframe/Mockup:**
N/A

**Comment by roamye** [comment]
Approved per UAT

**Comment by roamye** [comment]
SI is capturing the events of this in the prod site. Good to close. 

One question (does not affect tix)  @kamerynB what are the steps for the Hero Image link to appear as a entity link event?
