### ISSUE TITLE
Accordion Site Improve Events

### ISSUE THREAD

**Issue by kamerynB** [project-lux/lux-frontend#166]
**Problem Description:**
There are SI events missing on accordions on entity pages.

**Expected Behavior/Solution:**
Add or update SI events on  accordions on entity pages.

**Requirements:**

- [x] User selects an entity link in an accordion
    - This issue is covered in #164 
- [x] User selects an search link in an accordion
    - This issue is covered in #171 
- [x] User selects an accordion
    - Category: Accordion Item
    - Action: Open/Close
    - Label: Accordion `<accordion name>`

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [ ] ~Wireframe/Mockup - Mike~
- [ ] ~Committee discussions - Sarah~
- [ ] ~Feasibility/Team discussion - Sarah~
- [ ] ~Backend requirements - TBD~
- [ ] Frontend requirements - Kam
- [ ] Questions

**UAT/LUX Examples:**

View `user selects an accordion` report:
https://my2.siteimprove.com/Analytics/375000/Custom/EventTracking/Index/1?SearchField=&Query=accordion+item
Verify Category, Action, and Labels appear correctly.

**Dependencies/Blocks:**
N/A

**Related Github Issues:**

- #90 
- #91 

**Related links:**
For more information on SI Events please view the documentation here:
https://docs.google.com/document/d/1jsH4ckYOW7ykXlKACctZOP1IpxYnGaRIRPGDiuUbGMQ/edit

**Wireframe/Mockup:**
N/A

**Comment by roamye** [comment]
Approved per UAT

**Comment by roamye** [comment]
events are being captured in prod. good to close.
