### ISSUE TITLE
External Links Site Improve Events

### ISSUE THREAD

**Issue by kamerynB** [project-lux/lux-frontend#167]
**Problem Description:**
There are SI events missing on external links.

**Expected Behavior/Solution:**
Add or update SI events on external links.
NOTE: Links coming from the data and CMS can't be tracked.

**Requirements:**

- [x] User selects an external link
    - Category: External Link
    - Action: Selected
    - Label: External `<name of link>`

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [ ] ~Wireframe/Mockup - Mike~
- [ ] ~Committee discussions - Sarah~
- [ ] ~Feasibility/Team discussion - Sarah~
- [ ] ~Backend requirements - TBD~
- [ ] Frontend requirements - Kam
- [ ] Questions

**UAT/LUX Examples:**
View `external link` report:
https://my2.siteimprove.com/Analytics/375000/Custom/EventTracking/Index/1?SearchField=&Query=external+link
Verify Category, Action, and Labels appear correctly.

**Dependencies/Blocks:**
N/A

**Related Github Issues:**

- #90 
- #91 

**Related links:**
For more information on SI Events please view the documentation here:
https://docs.google.com/document/d/1jsH4ckYOW7ykXlKACctZOP1IpxYnGaRIRPGDiuUbGMQ/edit

**Wireframe/Mockup:**
N/A

**Comment by roamye** [comment]
Approved per UAT

**Comment by roamye** [comment]
events are being captured in prod, good to close.
