### ISSUE TITLE
Internal Links Site Improve Events

### ISSUE THREAD

**Issue by kamerynB** [project-lux/lux-frontend#169]
**Problem Description:**
There are SI events missing on internal links.

**Expected Behavior/Solution:**
Add or update SI events on internal links (non entity links, search links, or external links).

**Requirements:**

- [x] User selects an interal link
    - Category: Internal Link
    - Action: Selected
    - Label: Internal `<name of link>`

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [ ] ~Wireframe/Mockup - Mike~
- [ ] ~Committee discussions - Sarah~
- [ ] ~Feasibility/Team discussion - Sarah~
- [ ] ~Backend requirements - TBD~
- [ ] Frontend requirements - Kam
- [ ] Questions

**UAT/LUX Examples:**
View `Internal Links` report: 
https://my2.siteimprove.com/Analytics/375000/Custom/EventTracking/Index/1?SearchField=&Query=internal+link
Verify Category, Action, and Labels appear correctly.

**Dependencies/Blocks:**
N/A

**Related Github Issues:**

- #90 
- #91 

**Related links:**
For more information on SI Events please view the documentation here:
https://docs.google.com/document/d/1jsH4ckYOW7ykXlKACctZOP1IpxYnGaRIRPGDiuUbGMQ/edit

**Wireframe/Mockup:**
N/A

**Comment by roamye** [comment]
Approved per UAT

**Comment by roamye** [comment]
events are being captured in prod, good to close.
