### ISSUE TITLE
Search Link Site Improve Events

### ISSUE THREAD

**Issue by kamerynB** [project-lux/lux-frontend#171]
**Problem Description:**
There are SI events missing on Show All search links.

**Expected Behavior/Solution:**
Add or update SI events on Show All search links.

**Requirements:**

- [x] User selects a Show All search link
- NOTE: There will be several Labels to classify where the user has selected the search link.
    - Category: Search Link
    - Action: Selected
    - Label:
        - [x] Accordion `<accordion name>`
        - [x] Tab `<name of tab>`
        - [x] Timeline

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [ ] ~Wireframe/Mockup - Mike~
- [ ] ~Committee discussions - Sarah~
- [ ] ~Feasibility/Team discussion - Sarah~
- [ ] ~Backend requirements - TBD~
- [ ] Frontend requirements - Kam
- [ ] Questions

**UAT/LUX Examples:**
View `Search Link` report: 
https://my2.siteimprove.com/Analytics/375000/Custom/EventTracking/Index/1?SearchField=&Query=search+link
Verify Category, Action, and Labels appear correctly.

**Dependencies/Blocks:**
N/A

**Related Github Issues:**

- #90 
- #91 

**Related links:**
N/A

**Wireframe/Mockup:**
N/A

**Comment by roamye** [comment]
Approved per UAT

**Comment by roamye** [comment]
events are being captured in prod. good to close.
