### ISSUE TITLE
Error Site Improve Events

### ISSUE THREAD

**Issue by kamerynB** [project-lux/lux-frontend#172]
**Problem Description:**
There are SI events missing on errors.

**Expected Behavior/Solution:**
Add or update SI events on errors.

**Requirements:**

- [x] User is shown an error boundary
    - Category: Error
    - Action: Triggered
    - Label: Error Boundary
- [x] User is shown a page 404
    - Category: Error
    - Action: Triggered
    - Label: Page Not Found 404

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [ ] ~Wireframe/Mockup - Mike~
- [ ] ~Committee discussions - Sarah~
- [ ] ~Feasibility/Team discussion - Sarah~
- [ ] ~Backend requirements - TBD~
- [ ] Frontend requirements - Kam
- [ ] Questions

**UAT/LUX Examples:**
View `Error Boundary` and `Error Page 404` report: 
https://my2.siteimprove.com/Analytics/375000/Custom/EventTracking/Index/1?SearchField=&Query=error
Verify Category, Action, and Labels appear correctly.

- ~Page 404 should come up when going to a [malformed url](https://lux-front-dev.collections.yale.edu/view/person/34f4eec7-7a03-49c8-b1be-976c2f6)~
- Testing an error boundary may be harder to detect. 
-  NOTE: This works properly. However, when changing the time frame in SI it affects all other links. Please look at documentation for an image of Error Boundary or change time frame till after all SI issues have been reviewed. 

**Dependencies/Blocks:**
N/A

**Related Github Issues:**

- #90 
- #91 

**Related links:**
For more information on SI Events please view the documentation here:
https://docs.google.com/document/d/1jsH4ckYOW7ykXlKACctZOP1IpxYnGaRIRPGDiuUbGMQ/edit

**Wireframe/Mockup:**
N/A

**Comment by kamerynB** [comment]
@prowns @roamye Right now you can see the Error Boundary event by going to the people and group advanced search and selecting the single field "People or Group". Right now ML support is pushed to DEV so I can test #141 but I haven't yet deployed that change. But that will trigger the Error Boundary error at this moment. 

Page 404 can be seen by going to a [malformed url](https://lux-front-dev.collections.yale.edu/view/person/34f4eec7-7a03-49c8-b1be-976c2f6) as mentioned in the original issue description.

Example in Site Improve of both error types being recorded:
![Screenshot 2024-04-04 at 3 09 35 PM](https://github.com/project-lux/lux-frontend/assets/140102078/c37ee71b-3f4b-45d6-881f-432259cd523c)

**Comment by roamye** [comment]
Approved per UAT

**Comment by roamye** [comment]
prod event looks good. good to close. 

Note: we currently do not have an error boundary to test as what we previously used to test is now in PROD. We hope that someone would never come across that error because that would mean there is an issue in the Typescript or React code.
