### ISSUE TITLE
Existing Site Improve Event Updates

### ISSUE THREAD

**Issue by kamerynB** [project-lux/lux-frontend#174]
**Problem Description:**
There are SI events with incorrect categories, actions, and labels.

**Expected Behavior/Solution:**
Update SI events.

**Requirements:**

- [x] User selects to sort the results on the results page
    - Category: Results Sort
    - Action: Selected
    - Label: Sort by `<field name> <direction>`
- [x] User selects to toggle results view
    - Category: Results Toggle View
    - Action: Selected
    - Label: To `<list/grid>` View
- [x] User selects tab on entity page
    - Category: Tabs
    - Action: Selected
    - Label: Tab `<name of tab>`
- [x] User selects tab on results page
    - Category: Results Tabs
    - Action: Selected
    - Label: <scope name> 

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [ ] ~Wireframe/Mockup - Mike~
- [ ] ~Committee discussions - Sarah~
- [ ] ~Feasibility/Team discussion - Sarah~
- [ ] ~Backend requirements - TBD~
- [x] Frontend requirements - Kam
- [ ] ~Questions~

**UAT/LUX Examples:**
View `User selects to sort the results on the results page` report: 
https://my2.siteimprove.com/Analytics/375000/ThisQuarter/EventTracking/Index/1?SearchField=&Query=Results+sort

View `User selects to toggle results view` report: 
https://my2.siteimprove.com/Analytics/375000/ThisQuarter/EventTracking/Index/1?SearchField=&Query=Results+view+toggle

View `User selects tab on entity page` report: 
https://my2.siteimprove.com/Analytics/359298/ThisQuarter/EventTracking/Index/1?SearchField=&Query=Entity+tab

Verify Category, Action and Label appear correct. 

**Dependencies/Blocks:**
N/A

**Related Github Issues:**

- #90 
- #91 

**Related links:**
For more information on SI Events please view the documentation here:
https://docs.google.com/document/d/1jsH4ckYOW7ykXlKACctZOP1IpxYnGaRIRPGDiuUbGMQ/edit

**Wireframe/Mockup:**
N/A

**Comment by roamye** [comment]
tabs on results/entity page, toggle results view and sorting are captured in prod. good to close.
