### ISSUE TITLE
Create "Concept Class" facet in Concepts and Advanced Search

### ISSUE THREAD

**Issue by roamye** [project-lux/lux-frontend#176]
**Problem Description:**
We want to create a new facet within the Concepts tab and Advanced Search that can facet by `Concept Class`. 

**Expected Behavior/Solution:**
Users will be able to facet by `Concept Class` values `Measurement Unit`, `Language`, `Material`, `Currency` and `General Concept` in Concepts tab and Advanced Search. 

**Requirements:**

- [x] The refinement section of Concepts tab will now show the option `Concepts Class`
- [x] New facet will include values such as `Measurement Unit`, `Language`, `Material`, `Currency` and `General Concept`.
- [x] Advanced search will include this facet as a new single field. 
- [x] Advanced search options will be drop down to select the values.
- [x] Concept records will display `Concept Class` within its about page and include the following options of  `Measurement Unit`, `Language`, `Material`, `Currency` and `General Concept`.

The following requires a change to the config in ML:
Help Text will be displayed for the selection of each Concept class value.
- [ ] **Measurement Unit:** Search for Concepts that are used as the unit of a measurement, such as inches, seconds, kilograms or bytes.
- [ ] **Language:** Search for Concepts that represent human-spoken languages, such as English, Spanish or Latin.
- [ ] **Material:** Search for Concepts that represent a class of physical material, such as bronze, paper, or agate.
- [ ] **Currency:** Search for Concepts that represent monetary currencies, such as dollars, euros, or francs.
- [ ] **General Concept:** Search for Concepts that represent more general ideas, topics or subjects, which excludes the more specific classes of Measurement Unit, Language, Material, and Currency
- [ ] regression test needed - Amy 

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [x] Wireframe/Mockup - Mike
- [x] Committee discussions - Sarah
- [x] Feasibility/Team discussion - Sarah
- [x] Backend requirements - TBD
- [x] Frontend requirements- TBD
- [x] UAT - need a decision on what to call 5th class of general, other concept classes
- [x] Create Help Text - Sarah, Advocates
- [x] update wireframe 
- [x] Regression Test Required? - Amy | Yes 
- [x] Questions
- List of questions for discussions. Answers should be documented within the issue.
- Can we change "Type" to something else such as `Topic` or `General Idea or Subject`? Per LUX advocate meeting (05/14), advocates were not fond of Type as it is everything excluding the other values.  Will Help text may need to be updated depending on name change? 
- Answer: General Concept rather than Type 

**UAT/LUX Examples:**
- https://lux-front-tst.collections.yale.edu/view/results/concepts?q=%7B%22text%22%3A%22colors%22%2C%22_lang%22%3A%22en%22%7D&sq=colors
- Example of value type: ~https://lux-front-tst.collections.yale.edu/view/concept/af8fe2d4-fa58-4fba-92ee-d968578b7a05~ AND https://lux-front-tst.collections.yale.edu/view/concept/3dcea981-17cb-4a8b-acbf-49ab679066da
- Language: https://lux-front-tst.collections.yale.edu/view/concept/dfa53b96-4eda-4c9a-b091-10008a726c38 
- Currency: https://lux-front-tst.collections.yale.edu/view/concept/7ecf94c6-ab59-4814-a16d-d7fd6776f1b8
- Measurement Unit:  https://lux-front-tst.collections.yale.edu/view/results/concepts?q=%7B%22text%22%3A%22inch%22%2C%22_lang%22%3A%22en%22%7D&sq=inch&cp=1&cf=%7B%22AND%22%3A%5B%7B%22recordType%22%3A%22MeasurementUnit%22%7D%5D%7D&facetRequest=true
- Material: https://lux-front-tst.collections.yale.edu/view/concept/dd6f548b-56df-436b-966e-3442af1c5863
- Advanced Search: https://lux-front-tst.collections.yale.edu/view/results/concepts?q=%7B%22AND%22%3A%5B%7B%22recordType%22%3A%22Currency%22%7D%2C%7B%22name%22%3A%22franc%22%7D%5D%7D

**Dependencies/Blocks:**
- Blocked/Dependent On: https://github.com/project-lux/lux-marklogic/issues/42
- Dependent on: https://github.com/project-lux/lux-marklogic/issues/138 (ML) 

**Related Github Issues:**

**Related links:**

**Wireframe/Mockup:**
Current: 
![image](https://github.com/project-lux/lux-frontend/assets/163148482/a928821e-1f57-4747-807a-f07aba174ccd)

Updated: 
Note -  the number of items will be to the right of each value. For example: Language (x) 
![image](https://github.com/project-lux/lux-frontend/assets/163148482/a8114e9a-90f0-4a1c-9c23-6beb08d17a98)

Advanced Search:
Note: Help text is general until decision is made of what the help text should say. 
![image](https://github.com/project-lux/lux-frontend/assets/163148482/eb88e1cf-55d1-4089-b635-688e9de5fec2)

Concept Record: 
![image](https://github.com/project-lux/lux-frontend/assets/163148482/813d84c6-84f7-4693-a13c-944323a79eb4)

**Comment by roamye** [comment]
Hi @miketullo95, after discussion with UAT it was decided that the mockups should reflect a drop down option next to the new facets. 
In the example below we would replace the facets as follows: 
 "Is Online" = "Concept Class"
 "Gear Icon" = "Select Value" 
"Boosted" = "Measurement Unit", "Currency", etc options. 

We would still like the gear option next to it (as reflected in the link) but I am using the functionality of the gear icon as an example of what the concept class facet should look like. 

These changes will also reflect for the Boolean types in the other tixs. 

- mockup link example: https://lux.collections.yale.edu/view/results/objects?q=%7B%22isOnline%22%3A1%7D 
- Rough mockup example: 
![image](https://github.com/project-lux/lux-frontend/assets/163148482/5aa45900-8b4a-483c-be08-b4420e25ad22)

Please let me know if you have any questions. 

cc: @prowns

**Comment by kamerynB** [comment]
@prowns @roamye Can this be an agenda discussion? Along with #190.

**Comment by miketullo95** [comment]
advanced search mocks updated @prowns @roamye

**Comment by roamye** [comment]
This looks good. 
The only thing - there should be more than those two values listed. In the req it shows the values of Measurement Unit, Language, Material, and Currency. But I think we can list above the wireframe that it will include those other values as well. We should be ok. Thanks!

cc: @miketullo95 @prowns

**Comment by prowns** [comment]
@miketullo95 - would it take long to add all the options to the dropdown?   I think it's worth making this one right since it's the most complex and a new feature.

**Comment by miketullo95** [comment]
wireframe fixed

**Comment by prowns** [comment]
Per UAT: Add Concept Class: Type

**Comment by roamye** [comment]
Per IT team meeting it was decided to go forward with the value/name of "Type" to be added as a selector. The issue has been updated to capture these details and the mockups have been updated as well.

**Comment by roamye** [comment]
mockups have been updated. Ready for backlog

**Comment by clarkepeterf** [comment]
@kamerynB FYI the facet will be called `conceptRecordType` and the advanced search field will be called `recordType`

**Comment by clarkepeterf** [comment]
@kamerynB FYI the name of the facet is called `conceptRecordType` and the name of the JSON search field is `recordType`

**Comment by roamye** [comment]
Approved by UAT

**Comment by roamye** [comment]
This looks good in the front end. Closing 

Please note: the help text does not update for each selection of a Concept Class value in Advanced Search.
