### ISSUE TITLE
Create "Work Class" facet in Works and Advanced Search

### ISSUE THREAD

**Issue by roamye** [project-lux/lux-frontend#177]
**Problem Description:**
We want to create a new facet within the Works tab and Advanced Search that can facet by `Work Class`. 

**Expected Behavior/Solution:**
Users will be able to facet by `Work Class` values `Visual Work` , and `Textual Work` in Works tab and Advanced Search. 

Note: this will also need a regression test created. 
**Requirements:**

- [x] The refinement section of Works tab will now show the option `Work Class`
- [x] New facet will include values such as  `Visual Work`, `Textual Work`, and `Set`.
- [x] Advanced search will include this facet as a new single field. 
- [x] Advanced search options will be a drop down.
- [x] Work records will display Work Class within its about page and include the following options of  `Visual Work`, `Textual Work`, and `Set`.

The following Help Text requires a config change in ML:
- [ ] **Visual Work:** Search for Works that are primarily visual, such as the images shown by paintings or photographs, sculptures, or other non language oriented creative expressions.
- [ ] **Textual Work:**  Search for Works that are primarily textual or otherwise convey information via human language. An Object may include both visual and textual works, such as a poster with graphics and text.  In addition, Textual Works encompasses most items from the Library collections, including posters, artworks, musical scores, video and sound recordings.  

- [ ] Add regression test - Amy

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [x] Wireframe/Mockup - Mike
- [x] Help Text - Sarah (note that audio and video = textual works)
- [x] Update mockup - Mike
- [x] Committee discussions - Sarah
- [x] Feasibility/Team discussion - Sarah
- [x] Backend requirements - TBD
- [x] Are new regression tests required for QA - Amy | Yes 
- [x] Frontend requirements- TBD
- [X] Questions
- List of questions for discussions. Answers should be documented within the issue.

**UAT/LUX Examples:**
- https://lux-front-tst.collections.yale.edu/view/results/works?q=%7B%22text%22%3A%22colors%22%2C%22_lang%22%3A%22en%22%7D&sq=colors
- Textual Work: https://lux-front-tst.collections.yale.edu/view/text/036a0146-fbd8-4c0b-9c05-6e47d3d3e824
- Visual work: https://lux-front-tst.collections.yale.edu/view/visual/72eaa0a9-7c71-4af2-8baa-03683de11ad5
- Advanced Search: https://lux-front-tst.collections.yale.edu/view/results/works?q=%7B%22AND%22%3A%5B%7B%22recordType%22%3A%22Set%22%7D%2C%7B%22name%22%3A%22saarinen%22%7D%5D%7D

**Dependencies/Blocks:**
- Blocked/Dependent On: https://github.com/project-lux/lux-marklogic/issues/42 
- Blocked: https://github.com/project-lux/lux-marklogic/issues/140

**Related Github Issues:**

**Related links:**

- These links can consist of resources, bugherds, etc.

**Wireframe/Mockup:**
Place wireframe/mockup for the proposed solution at end of ticket.

Wireframe:
![Screenshot 2024-04-15 at 4 16 20 PM](https://github.com/project-lux/lux-frontend/assets/98550395/bfcc0a29-84e3-4c6b-bc65-b797acff8c84)

New Advanced Search 
Note: each value selection will display the help text listed above. 
![Image](https://github.com/project-lux/lux-frontend/assets/98550395/71c6b286-61ce-46d3-a7db-19abb4fe4ef8)

Work record: 
![image](https://github.com/project-lux/lux-frontend/assets/163148482/7a2564a0-3132-4c28-8357-21acdba851d0)

**Comment by miketullo95** [comment]
@roamye same question as #175

**Comment by roamye** [comment]
Yes this new mock up looks good to me. I will delete the old one. Ty @miketullo95 

cc: @prowns

**Comment by clarkepeterf** [comment]
@kamerynB fyi the facet is called `workRecordType` and the search field is called `recordType`

**Comment by roamye** [comment]
Per UAT: 
This is approved BUT the Work Class does not show the AS multiple field is `set`. This bug needs to be a hot fix before deployment.

If this cannot be resolved by the time, it will need to be a priority for next release.

**Comment by roamye** [comment]
OK the work class set facet now works but I noticed that the numbers do not match up. For example: 
https://lux.collections.yale.edu/view/results/works?q=%7B%22AND%22%3A%5B%7B%22text%22%3A%22andy%22%2C%22_lang%22%3A%22en%22%7D%2C%7B%22text%22%3A%22warhol%22%2C%22_lang%22%3A%22en%22%7D%5D%7D&sq=andy+warhol

We only have two work class values: visual work and textual work... but the numbers in the facet does not match up to the total number of records... what are the remaining 34 records classified as? 

1288 work results
1254 combined results of visual and textual work..

I will make a BH for this issue and close this one as the rest looks good in PROD.
