### ISSUE TITLE
Create "Object Class" facet in Objects and Advanced Search

### ISSUE THREAD

**Issue by roamye** [project-lux/lux-frontend#178]
**Problem Description:**
We want to create a new facet within the Objects tab and Advanced Search that can facet by `Object Class`. 

**Expected Behavior/Solution:**
Users will be able to facet by `Object Class` values `Physical Object`, and `Digital Object` in Objects tab and Advanced Search. 

**Requirements:**

- [x] - The refinement section of Objects tab will now show the option `Object Class`
- [x] - New facet will include values such as `Physical Object`, and `Digital Object`.
- [x] - Advanced search will include this facet as a new single field. 
- [x] - Advanced search options will be a drop down similar to #175 and  #176. 
- [x] The Object records will display `Object Class` within the about page and contain the options of: `Physical Object`, and `Digital Object` 
- [ ] - The following help text will be displayed for each value selection: 
- [ ]    - **Physical Object**: Search for Objects that are physical items, such as paintings, sculptures, fossils and other specimens, and archival objects. Individual physical copies of books are included in this class. 
- [ ]    -  **Digital Object:** Search for Objects that are digital items, such as internet resources (datasets, e-books, and other digital files).  Digitized images of collection items that are physical objects can be found with the “Is Online” facet on Physical Objects
- [ ] regression test case - amy 

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [x] Wireframe/Mockup - Mike
- [x] Help Text - Sarah
- [x] Update mockup - Mike
- [x] Committee discussions - Sarah
- [x] Feasibility/Team discussion - Sarah
- [x] Backend requirements - TBD
- [x] Frontend requirements- TBD
- [x] Questions
- List of questions for discussions. Answers should be documented within the issue.

**UAT/LUX Examples:**
- https://lux-front-tst.collections.yale.edu/view/results/objects?q=%7B%22text%22%3A%22colors%22%2C%22_lang%22%3A%22en%22%7D&sq=colors
- physical object: https://lux-front-tst.collections.yale.edu/view/object/64a6f0c2-6d58-44d8-8ffe-43ff5d213b62
- Digital object: https://lux-front-tst.collections.yale.edu/view/digital/8d70874b-224e-4d3c-9ae9-823924407442
- Advanced Search: https://lux-front-tst.collections.yale.edu/view/results/objects?q=%7B%22AND%22%3A%5B%7B%22recordType%22%3A%22DigitalObject%22%7D%2C%7B%22name%22%3A%22rabbit%22%7D%5D%7D

**Dependencies/Blocks:**
- Blocked/Dependent On: https://github.com/project-lux/lux-marklogic/issues/42
- Blocked by: https://github.com/project-lux/lux-marklogic/issues/141

**Related Github Issues:**

**Related links:**

- These links can consist of resources, bugherds, etc.

**Wireframe/Mockup:**
Place wireframe/mockup for the proposed solution at end of ticket.

Wireframe:
![Screenshot 2024-04-15 at 4 24 55 PM](https://github.com/project-lux/lux-frontend/assets/98550395/2cdd9ac8-af63-45e9-8db9-f9a67fa7c91f)

Advanced Search:
![Screenshot 2024-05-01 at 1 46 04 PM](https://github.com/project-lux/lux-frontend/assets/98550395/b9cbfeed-6d1a-4528-abca-8528871cf0b8)

Object record: 
![image](https://github.com/project-lux/lux-frontend/assets/163148482/c6032421-958c-4408-9f69-fd360b8ee132)

**Comment by miketullo95** [comment]
@roamye wireframe fixed

**Comment by clarkepeterf** [comment]
@kamerynB FYI the facet is called `itemRecordType` and the search field is called `recordType`

**Comment by roamye** [comment]
The label for the records needs to be added. 

So for example, in the record : https://lux-front-tst.collections.yale.edu/view/object/64a6f0c2-6d58-44d8-8ffe-43ff5d213b62

the about section needs to contain the label of [TBD] to show the record is a physical object. 
This will need to be consistent with the label for Categorized as: People / Group from BH 2333 https://www.bugherd.com/projects/284041/tasks/2333

**Comment by kamerynB** [comment]
The label should be the same as what is reflected in facets and advanced search.

Examples:
Object Class      Physical Object
Work Class        Visual Item
Person or Group Class      Person
etc....

**Comment by roamye** [comment]
@kamerynB - the req for the classes to be displayed on each req has been updated on all 175-178 issues. I will create some mockups for them and add them when ready.

**Comment by roamye** [comment]
Looks good in PROD closing.
