### ISSUE TITLE
Sort item events by year (from 1266)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-frontend#18]
Problem description: It is unclear how the list of Exhibitions is sorted on an object record.  Also, the events are showing duplicate event names, so need a way to distinguish.

Expected behaviors:  
- Sort events by year (middle tier)
- Display Event title only

Needed

- [x] Sort ascending or descending? - Decision:  chronological ascending
- [x] Should event show month/year and location?  YES
- [x] Decision about what the event list should show (date? location)
- [x] wireframe/mockup to show final decision

Dependency
- [ ] [New HAL link ticket -  Update itemEvents HAL Link To Sort Events (from 105) #8](https://github.com/project-lux/lux-middletier/issues/8)
[Old ticket - 105](https://git.yale.edu/lux-its/lux-backend/issues/105)

Links
- Bugherd: https://www.bugherd.com/projects/284041/tasks/1020
- https://lux.collections.yale.edu/view/object/9d51c432-68dd-4d58-b393-32dba4dcb245

**Comment by ar2674** [comment]
@prowns @jffcamp This is set to this weeks deployment, Is it ready to be reviewed? It also says blocked but I checked the dependency and old 105/new 8  is closed.

**Comment by prowns** [comment]
Propose close - looks implemented using examples from 1266. Exhibitions sorting in order:  https://lux-front-sbx.collections.yale.edu/view/object/9d51c432-68dd-4d58-b393-32dba4dcb245
