### ISSUE TITLE
Update Related Subjects on event pages

### ISSUE THREAD

**Issue by kamerynB** [project-lux/lux-frontend#180]
**Problem Description:**
The current relationship for Related Lists on event pages is incorrect.

**Expected Behavior/Solution:**
The Related Subjects list should be a related list.
Note: the Related Subjects accordion is now re-labeled as Related Concepts as we will be removing related subjects. (#205)

**Requirements:**

- [x] Change HAL link config

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [x] Wireframe/Mockup - Kam
- [ ] ~Committee discussions - Sarah~
- [ ] ~Feasibility/Team discussion - Sarah~
- [x] Backend requirements - Peter, ML and MT ticket
- [x] ML ticket: https://github.com/project-lux/lux-marklogic/issues/96
- [x] Frontend requirements - Kam
- [ ] ~Questions~

**UAT/LUX Examples:**

- https://lux-front-dev.collections.yale.edu/view/activity/6e09857c-6b08-4155-a3b9-c7055d688d92 (dev) 
- https://lux.collections.yale.edu/view/activity/6e09857c-6b08-4155-a3b9-c7055d688d92 (prod) 

**Dependencies/Blocks:**

- Blocked By: https://github.com/project-lux/lux-middletier/issues/51
- MT issue 51 is blocked by: https://github.com/project-lux/lux-marklogic/issues/96

**Related Github Issues:**

- Original issue: #7 

**Related links:**
N/A

**Wireframe/Mockup:**
Accordion Name: Related Concepts
![image](https://github.com/project-lux/lux-frontend/assets/140102078/f1e55a3a-6e22-4e55-bdf8-d2949edfaf54)

**Comment by clarkepeterf** [comment]
@kamerynB with https://github.com/project-lux/lux-middletier/issues/51 I have done the following:
- ADDED the lux:eventRelatedConcepts HAL link
- REMOVED the lux:eventConceptsOfItems HAL link

**Comment by roamye** [comment]
Looks good in prod :), closing
