### ISSUE TITLE
Upgrade the CMS to Drupal 10

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-frontend#189]
**Problem Description:**
The current version is Drupal 9, the support of which has ended on 11/1/23 - https://www.drupal.org/docs/understanding-drupal/drupal-9-release-date-and-what-it-means/how-long-will-drupal-9-be-supported. 

**Expected Behavior/Solution:**
Upgrade to version 10 with all current features still working.

**UAT**
- regression test
- smoke tests of landing page, static pages, FAQ

**Comment by jffcamp** [comment]
Planning document and proposed schedule:
https://docs.google.com/document/d/1z_PjDsR9uFIJG1PscYjDk3mjWiMYj6_YP7QZnjYkl0A/edit

Non-prd - upgraded by the morning of September 11th
1. Freeze updating CMS content
2. Vincent: Copy LUX data from PRD (https://lux-cms.collections.yale.edu/) to TST instance of D9 & then TST to DEV
3. Seong: Point lux-front-tst at non-prd D9 environment
4. Sarah/Jeff: Smoke test that it still works
5. Vincent: Upgrade DEV D9 to D10
6. Sarah/Jeff/Seong: Smoke test lux-front-tst
7. QA: run our Drupal regression test against the environment connected to lux-front-tst
8. Point lux-front-tst back to PRD D9 (https://lux-cms.collections.yale.edu/)

Prd – upgraded ON the morning of September 18th. The earlier the better.
1. Vincent: upgrade PRD D9 to D10
2. Sarah/Jeff/Seong: Smoke test using lux-front-tst
3. QA: run our Drupal regression test

**Comment by roamye** [comment]
UAT 9/12
This needs to be finished and will be complete sometime next week. Can be closed after the 18th if everything looks good.

**Comment by prowns** [comment]
Upgrade complete.
