### ISSUE TITLE
Add Works About tab and list to events (from 1303)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-frontend#19]
Problem Description:  Periods (events) are not displaying lists of Related Works: https://lux-front-dev.collections.yale.edu/view/activity/6297d4d4-ea61-45b2-8c47-9a0e6298fdcc

Expected Behavior: Front end should render the list Works Related on Event page.  Middle tier will provide a HAL link which searches for works about this event.

Needed: 

- [x] Implementation plan
- [x] Create HAL Link ticket - https://git.yale.edu/lux-its/lux-backend/issues/107 - Peter

Dependency: 
- [x] [Create WorksAboutEvent HalLink (from 107) #9](https://github.com/project-lux/lux-middletier/issues/9)
[Old ticket - 107](https://github.com/project-lux/lux-middletier/issues/9)
~https://git.yale.edu/lux-its/marklogic/issues/899~

UAT Review:

- Shows Works About: https://lux-front-tst.collections.yale.edu/view/activity/6297d4d4-ea61-45b2-8c47-9a0e6298fdcc 
- Does not show Works About: https://lux.collections.yale.edu/view/activity/6297d4d4-ea61-45b2-8c47-9a0e6298fdcc

Links
- Work with concept: https://lux-front-dev.collections.yale.edu/view/text/b73b66ae-a434-4214-adae-ba33427ae713
-  https://www.bugherd.com/projects/284041/tasks/1084
- https://www.bugherd.com/projects/284041/tasks/1982

**Comment by ar2674** [comment]
Approved per UAT

**Comment by prowns** [comment]
deployed
