### ISSUE TITLE
Refactor Person or Group selector in Advanced Search. 

### ISSUE THREAD

**Issue by roamye** [project-lux/lux-frontend#190]
**Problem Description:**
Per: https://github.com/project-lux/lux-frontend/issues/141, we had created a new Person or Group selector that looked like a Boolean type. However, after discussion and new additions of Object Class, Events Class, Work Class, and Concept Class selectors, it was decided to re-factor Person or Group to function as the Scope Classes above to create consistency.  

**Expected Behavior/Solution:**
The functionality of Person or Group will operate the same way as those in Object/Event/Work/Concept Class where it will have a drop down of options "Person" or "Group". 

**Requirements:**
-  Advanced search options will function as a drop down to select the values of `Person` or `Group`.
- The drop down will have a default name of 'Select Value'
- Should be Modeled on has single field drop down style

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [x] Wireframe/Mockup - Amy 
- [x] Committee discussions - Sarah
- [x] Feasibility/Team discussion - Sarah
- [ ] ~Backend requirements - TBD~
- [x] Frontend requirements- TBD
- [x] Questions
- List of questions for discussions. Answers should be documented within the issue.

**UAT/LUX Examples:**

- https://lux-front-dev.collections.yale.edu/view/results/people?q=%7B%22AND%22%3A%5B%7B%22name%22%3A%22andy+warhol%22%7D%2C%7B%22recordType%22%3A%22Person%22%7D%5D%7D 

**Dependencies/Blocks:**
N/A

**Related Github Issues:**
- https://github.com/project-lux/lux-frontend/issues/141

**Related links:**

**Wireframe/Mockup:**
Current: 
![image](https://github.com/project-lux/lux-frontend/assets/163148482/b5e7d1f3-9774-40c8-aa47-043cc9d6acb7)

Updated: 
![image](https://github.com/project-lux/lux-frontend/assets/163148482/2ac35e83-66bb-43d6-b17c-46ccf68753ec)

**Comment by roamye** [comment]
This issue has been updated to reflect the discussion of today's UX/BA meeting. Rather than changing Boolean types we will only refactor the Person or Group selector in Advanced Search.

**Comment by kamerynB** [comment]
Please promote as the wireframe can be added later considering we have examples in other tickets.

@prowns @jffcamp @roamye

**Comment by roamye** [comment]
Approved by UAT

**Comment by roamye** [comment]
looks good in prod, closing.
