### ISSUE TITLE
Change the labels for referred_to_by data

### ISSUE THREAD

**Issue by kamerynB** [project-lux/lux-frontend#195]
**Problem Description:**
Currently, the `referred_to_by` data has labels that are parsed from the nested `/referred_to_by/classified_as/id` data point. 

**Expected Behavior/Solution:**
The labels rendered with `referred_to_by` data should first render the value of `/referred_to_by/identified_by/content`. If that data is not present, the frontend will default to the existing `/referred_to_by/classified_as/id` as the label.

**Requirements:**

- [x] Update the getNotes function to parse `/referred_to_by/identified_by/content` for the label

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [x] Wireframe/Mockup - Mike
- [ ] ~Committee discussions - Sarah~
- [ ] ~Feasibility/Team discussion - Sarah~
- [ ] ~Backend requirements - TBD~
- [x] Frontend requirements - Kam
- [ ] ~Questions~

**UAT/LUX Examples:**

- TST: https://lux-front-tst.collections.yale.edu/view/object/047181f4-2fdf-43fd-abbe-f16d7f9edc10
- PRD: https://lux.collections.yale.edu/view/object/047181f4-2fdf-43fd-abbe-f16d7f9edc10

Screenshot of the data:
<img width="1404" alt="Screenshot 2024-04-19 at 2 08 34 PM" src="https://github.com/project-lux/lux-frontend/assets/140102078/63b38e37-43f2-4a33-a0bf-842631960e63">

**Dependencies/Blocks:**
N/A

**Related Github Issues:**
N/A

**Related links:**
N/A

**Wireframe/Mockup:**
Current:
<img width="781" alt="Screenshot 2024-04-19 at 2 13 29 PM" src="https://github.com/project-lux/lux-frontend/assets/140102078/d08233cc-e4b8-4d39-824c-43c3cd9d8a12">

Expected:
<img width="781" alt="Screenshot 2024-04-19 at 2 14 19 PM" src="https://github.com/project-lux/lux-frontend/assets/140102078/c3dd9fd2-d39e-4f05-908c-6c34fb8b3423">

**Comment by roamye** [comment]
Is this okay to move to reviewable(since the in progress label was removed) ? @kamerynB

**Comment by roamye** [comment]
Approved by UAT

**Comment by roamye** [comment]
Looks good in prod, closing.
