### ISSUE TITLE
Remove the use of data constants and their configuration and replace with AAT config

### ISSUE THREAD

**Issue by kamerynB** [project-lux/lux-frontend#196]
**Problem Description:**
Data constants are being removed as there is too much variability when deploying new datasets.

**Expected Behavior/Solution:**
Remove the data constants config in the frontend. Replace all configuration and uses within the code with AAT config. 

**Requirements:**

- [x] Replace dataConstants.ts with aat.ts, which will contain the AAT values
- [x] The frontend will store AATs as they will be stable
- [x] Replace all instances of `config.dc` with `config.aat`
- [x] Replace frontend env variables to reflect the change
- [x] Update all impacted functions to parse nested `/equivalent/id` data points to check the AAT values. These functions and components are listed below. This does not include tests and test mocks.

Functions that use data constants:
- [x] getPrimaryName
- [x] getDescriptions
- [x] isClassifiedAs
- [x] getNames
- [x] getTypes
- [x] getCopyrightLicensingStatement
- [x] getMultipleSpecificReferredToBy
- [x] isInLanguage
- [x] getNotes
- [x] validateClassifiedAsIdMatches
- [x] getIdentifiers
- [x] getClassifiedAs
- [x] isSpecimen
- [x] getSupertypeIcon
- [x] getName
- [x] getAccessStatement
- [x] getCallNumber --> ~NEED THE AAT FOR THIS~
- [x] getDimensions
- [x] containsSpecificNote
- [x] getAboutData (ObjectParser)
- [x] getAllClassifiedAs
- [x] getClassifiedAsWithMatchingClassifier
- [x] getCarriedOut
- [x] isArchive
- [x] getContentByClassifiedAs
- [x] transformRelatedListResults
- [x] getLinkToUnitSite
- [x] getAllSiteLinks
- [x] getOccupations
- [x] getNationalities

Components that use data constants:
- [x] ApiText
- [x] Checklist
- [x] FacetsRelatedList

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [ ] ~Wireframe/Mockup - Mike~
- [ ] ~Committee discussions - Sarah~
- [ ] ~Feasibility/Team discussion - Sarah~
- [x] Backend requirements - Peter
- [x] Frontend requirements - Kam
- [ ] ~Questions~

**UAT/LUX Examples:**

- All pages should behave as they currently do.

**Dependencies/Blocks:**

- Blocked by: https://github.com/project-lux/lux-marklogic/issues/54

**Related Github Issues:**
N/A

**Related links:**
N/A

**Wireframe/Mockup:**
This does not require a wireframe as the frontend should appear the exact same as it did before this change.

**Comment by roamye** [comment]
@kamerynB 
Is there an example of a record page we could use to verify it will look/work the same? Is it fine to use the Andy Warhol record? 

I am trying to figure out a way this could be tested.

**Comment by roamye** [comment]
This is no longer blocked. 

@kamerynB

**Comment by clarkepeterf** [comment]
List of frontend data constants and their AATs:

```
[
    {
        "name": "accessStatement",
        "equivalent": [
            "http://vocab.getty.edu/aat/300133046"
        ]
    },
    {
        "name": "active",
        "equivalent": [
            "http://vocab.getty.edu/aat/300393177"
        ]
    },
    {
        "name": "alternateName",
        "equivalent": [
            "http://vocab.getty.edu/aat/300264273"
        ]
    },
    {
        "name": "animalSpecimens",
        "equivalent": [
            "http://vocab.getty.edu/aat/300420186"
        ]
    },
    {
        "name": "archive",
        "equivalent": [
            "http://vocab.getty.edu/aat/300312242",
            "http://vocab.getty.edu/aat/300375748",
            "http://vocab.getty.edu/aat/300124822",
            "http://vocab.getty.edu/aat/300004482"
        ]
    },
    {
        "name": "biologicalSpecimens",
        "equivalent": [
            "http://vocab.getty.edu/aat/300421897"
        ]
    },
    {
        "name": "collection",
        "equivalent": [
            "http://vocab.getty.edu/aat/300025976"
        ]
    },
    {
        "name": "collectionItem",
        "equivalent": [
            "http://vocab.getty.edu/aat/300404024"
        ]
    },
    {
        "name": "copyrightLicensingStatement",
        "equivalent": [
            "http://vocab.getty.edu/aat/300435434"
        ]
    },
    {
        "name": "descriptionStatement",
        "equivalent": [
            "http://vocab.getty.edu/aat/300435416"
        ]
    },
    {
        "name": "dimensionStatement",
        "equivalent": [
            "http://vocab.getty.edu/aat/300435430"
        ]
    },
    {
        "name": "displayName",
        "equivalent": [
            "http://vocab.getty.edu/aat/300404669"
        ]
    },
    {
        "name": "exhibition",
        "equivalent": [
            "http://vocab.getty.edu/aat/300054766"
        ]
    },
    {
        "name": "first",
        "equivalent": [
            "http://vocab.getty.edu/aat/300404050"
        ]
    },
    {
        "name": "fossil",
        "equivalent": [
            "http://vocab.getty.edu/aat/300247919"
        ]
    },
    {
        "name": "gender",
        "equivalent": [
            "http://vocab.getty.edu/aat/300055147"
        ]
    },
    {
        "name": "imprintStatement",
        "equivalent": [
            "http://vocab.getty.edu/aat/300202362"
        ]
    },
    {
        "name": "langdut",
        "equivalent": [
            "http://vocab.getty.edu/aat/300388256"
        ]
    },
    {
        "name": "langen",
        "equivalent": [
            "http://vocab.getty.edu/aat/300388277"
        ]
    },
    {
        "name": "langfr",
        "equivalent": [
            "http://vocab.getty.edu/aat/300388306"
        ]
    },
    {
        "name": "langfre",
        "equivalent": []
    },
    {
        "name": "langger",
        "equivalent": []
    },
    {
        "name": "langspa",
        "equivalent": []
    },
    {
        "name": "languageStatement",
        "equivalent": [
            "http://vocab.getty.edu/aat/300435433",
            "http://vocab.getty.edu/aat/300055193"
        ]
    },
    {
        "name": "nationality",
        "equivalent": [
            "http://vocab.getty.edu/aat/300379842"
        ]
    },
    {
        "name": "occupation",
        "equivalent": [
            "http://vocab.getty.edu/aat/300263369",
            "http://vocab.getty.edu/aat/300263340"
        ]
    },
    {
        "name": "plantSpecimens",
        "equivalent": [
            "http://vocab.getty.edu/aat/300430421"
        ]
    },
    {
        "name": "primaryName",
        "equivalent": [
            "http://vocab.getty.edu/aat/300404670"
        ]
    },
    {
        "name": "sortName",
        "equivalent": [
            "http://vocab.getty.edu/aat/300404672"
        ]
    },
    {
        "name": "sortValue",
        "equivalent": [
            "http://vocab.getty.edu/aat/300451544"
        ]
    },
    {
        "name": "typeOfPart",
        "equivalent": [
            "http://vocab.getty.edu/aat/300241583"
        ]
    },
    {
        "name": "visitors",
        "equivalent": [
            "http://vocab.getty.edu/aat/300025883"
        ]
    },
    {
        "name": "webPage",
        "equivalent": [
            "http://vocab.getty.edu/aat/300264578"
        ]
    }
]
```

**Comment by clarkepeterf** [comment]
@azaroth42 @kkdavis14  from above - the following constants have multiple AATs - how should the frontend handle these?

- archive
- languageStatement
- occupation

There are a few  constants for languages which don't have AATs, but they are not actually used in the frontend. For some reason they are used in tests, though @kamerynB - if they are not used should they be removed from tests?

**Comment by kkdavis14** [comment]
@clarkepeterf 
The correct AATs for the above, if it helps:
archive: [http://vocab.getty.edu/aat/300375748](http://vocab.getty.edu/aat/300375748)
languageStatement: [http://vocab.getty.edu/page/aat/300435433](http://vocab.getty.edu/page/aat/300435433)
occupation:[http://vocab.getty.edu/page/aat/300263369](http://vocab.getty.edu/aat/300263369)

**Comment by kamerynB** [comment]
Note from 6/26/24 meeting:
There shouldn't be an issue when filtering an entity from a list via its /equivalent IDs/AATs. AATs should not be repeated in multiple entities.

**Comment by roamye** [comment]
@kamerynB - 

can this be checked off from above? 

` getCallNumber --> NEED THE AAT FOR THIS`

**Comment by roamye** [comment]
Need to confirm the above. Once it is confirmed this is Approved by UAT 7/22.

**Comment by kkdavis14** [comment]
if you need the AAT for call number, it's 300311706

**Comment by kamerynB** [comment]
@kkdavis14 I already got it before deploying this issue. @roamye Whoops, I forgot to check that one off. Call Numbers should be visible in the frontend.

**Comment by roamye** [comment]
Closing as this has been deployed to PROD & it is unreviewable.
