### ISSUE TITLE
Add agent data to identifiers via the /identified_by/assigned_by/carried_out_by/id data point

### ISSUE THREAD

**Issue by kamerynB** [project-lux/lux-frontend#198]
**Problem Description:**
The agent that the identifier is associated with is not being rendered.

**Expected Behavior/Solution:**
The frontend should render that data by reading the `/identified_by/assigned_by` data point.

**Requirements:**

- [x] Update the getIdentifiers function to read `/identified_by/assigned_by`

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [x] Wireframe/Mockup - Mike
- [ ] ~Committee discussions - Sarah~
- [ ] ~Feasibility/Team discussion - Sarah~
- [ ] ~Backend requirements - TBD~
- [x] Frontend requirements - Kam
- [ ] ~Questions~

**UAT/LUX Examples:**

- https://lux-front-tst.collections.yale.edu/view/text/97aa002f-8224-4618-bc1a-284988c2accc

**Dependencies/Blocks:**
N/A

**Related Github Issues:**
N/A

**Related links:**

- Bugherd: https://www.bugherd.com/projects/284041/tasks/2120

**Wireframe/Mockup:**
Current:
![Screenshot 2024-04-23 at 4 06 41 PM](https://github.com/project-lux/lux-frontend/assets/140102078/a58b8620-11cc-4cc6-8a29-4173ec82adf0)

Expected:
![Screenshot 2024-04-23 at 4 08 27 PM](https://github.com/project-lux/lux-frontend/assets/140102078/01544571-2973-4b95-91cc-6a88487ecfd1)

**Comment by roamye** [comment]
Approved by UAT

**Comment by roamye** [comment]
works in prod, closing.
