### ISSUE TITLE
Create a process for updating dependencies (from 118)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-frontend#2]
**Problem Description:**
The frontend does not have a process for updating packages based on vulnerabilities or on latest releases.

**Expected Behavior/Solution:**
The frontend should have a maintenance cycle so that packages and code are always up to date. This schedule should be constantly taking place.

**Requirements:**

- [ ] maintenance tickets should use the `maintenance` tag
- [ ] Code updates should be included in the maintenance cycle 
- [ ] Utilize `yarn audit` and [yarn-audit-fix package](https://www.npmjs.com/package/yarn-audit-fix) to check for vulnerabilities and updates
- [ ] `yarn update` or `yarn update-interactive` commands should be used to update the packages
- [ ] exact version numbers should be used for packages
- [ ] Docker should be reviewed for any updates
- [ ] Docker dependencies should be updated
- [ ] Software updates should be checked
- [ ] Any reason for not performing an update on a package or software should be documented with a reason

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [x] ~Wireframe/Mockup - Mike~
- [x] ~Committee discussions - Sarah~
- [x] ~Feasibility/Team discussion - Sarah~
- [x] ~Backend requirements - TBD~
- [ ] Frontend requirements - Kam
- [ ] Questions:
- When to update packages? ANSWER: on a monthly basis
- What determines a package's priority to be updated (criticality, etc)? ANSWER: security issues and deprecated packages should be given priority
- What testing will be performed once a package is updated to ensure there are no dependency issues? ANSWER: yarn audits for security and running the test suite

**UAT/LUX Examples:**
N/A

**Dependencies/Blocks:**
N/A

**Related Github Issues:**

- #412 
- #414 

**Related links:**
N/A

**Wireframe/Mockup:**
N/A

**Comment by roamye** [comment]
@kamerynB Do these questions need to be brought up at an IT meeting?

**Comment by kamerynB** [comment]
@roamye No they are more for me. I've been part of dev teams that have had processes in place for updating packages so that was me asking questions to myself on how I can use previous knowledge for this task. 😄

**Comment by roamye** [comment]
dev mtg 10/21: 
 - one of the purposes of this issue is to eliminate any current/future security risks.

**Comment by clarkepeterf** [comment]
Yarn has a tool to help upgrade packages:
https://classic.yarnpkg.com/lang/en/docs/cli/upgrade-interactive/

**Comment by kamerynB** [comment]
@prowns @jffcamp I would like to discuss this in the next frontend meeting. I have a document outlining what this process should look like.

**Comment by kamerynB** [comment]
@prowns @jffcamp This issue is marked for review but does not require UAT review. The review will take place internally with Peter, Seong, and Xinjian.

**Comment by roamye** [comment]
Approved by UAT

**Comment by roamye** [comment]
unreviewable. closing as all issues in this milestone are in PROD. 
@kamerynB
