### ISSUE TITLE
Wikimedia manifest error

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-frontend#200]
**Problem Description:**
IIIF viewer fails to load images for some records.

Failing Example: https://lux.collections.yale.edu/view/text/475d969e-2f2f-4e95-bad2-ba86e566abf3

Working Example: https://lux.collections.yale.edu/view/text/5ad5d97a-1b16-42c4-ad5e-145b2371643b

**Comment by gigamorph** [comment]
Manifest server is getting 500 for the request.

**Comment by gigamorph** [comment]
The last URL from the previous comment -- https://commons.wikimedia.org/w/api.php?action=query&format=json&prop=imageinfo&iiprop=url|timestamp|user|mime|extmetadata&iiurlwidth=30000&titles=File:Turner,_J._M._W._-_The_Fighting_Téméraire_tugged_to_her_last_Berth_to_be_broken.jpg -- returns a valid JSON when requested from a browser, but returns an HTTP error 400 when requested by manifest server or cURL.

**Comment by gigamorph** [comment]
When spaces are escaped with `%20` instead of `_` for the above URL, the request from cURL succeeds.

**Comment by gigamorph** [comment]
Findings:
- The Gorilla MUX library that manifest server uses unescapes the URL components before handling the request.
- The URLs contained in query responses returned by the Wikimedia API are escaped.

Solution:
- Fix manifest server to escape/unescape URL components consistently.

**Comment by gigamorph** [comment]
Fixed.

**Comment by jffcamp** [comment]
@gigamorph - looks good and the ticket explains why it is fixed everywhere :)
Great job

**Comment by roamye** [comment]
I see the manifest error no longer appears for prod record https://lux.collections.yale.edu/view/text/475d969e-2f2f-4e95-bad2-ba86e566abf3, is it fine to propose close? 

@gigamorph
