### ISSUE TITLE
Remove Related Subjects accordion from People & Group records

### ISSUE THREAD

**Issue by roamye** [project-lux/lux-frontend#205]
**Problem Description:**
Related Subjects accordion is redundant to the Related Concepts accordion in People & Group records. This can cause user confusion as they both contain the same results. 

**Expected Behavior/Solution:**
After discussion on IT team meeting 4/26 it was proposed to remove the related subjects accordion from People & Group records. 

**Requirements:**
- Related subjects accordion will no longer show on people & group records. 

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [x] ~Wireframe/Mockup - Mike~
- [x] ~Committee discussions - Sarah~
- [x] ~Feasibility/Team discussion - Sarah~
- [x] ~Backend requirements - TBD~
- [x] Frontend requirements - Kam
- [x] Questions
- Are we also removing this accordion from event pages? I noticed that the event pages has a related subjects accordion as well but its query is different. 
  - Ex: [Shakespeare event](https://lux-front-tst.collections.yale.edu/view/activity/3627f6a0-be4a-4ca8-bffd-5cc62e23e6ae) | [show all results AS query ](https://lux-front-tst.collections.yale.edu/view/results/concepts?q=%7B%22subjectOfConcept%22%3A%7B%22carriedBy%22%3A%7B%22memberOf%22%3A%7B%22usedForEvent%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Factivity%2F3627f6a0-be4a-4ca8-bffd-5cc62e23e6ae%22%7D%7D%7D%7D%7D&openSearch=false)
  - ANSWER: This has already been removed in Event pages.

**UAT/LUX Examples:**
- Person TST:  [Andy Warhol](https://lux-front-dev.collections.yale.edu/view/person/34f4eec7-7a03-49c8-b1be-976c2f6ba6ba)
- Group TST: https://lux-front-tst.collections.yale.edu/view/group/6b1104a6-4957-4b77-8218-9c686febd8db
- Person PRD: https://lux.collections.yale.edu/view/person/34f4eec7-7a03-49c8-b1be-976c2f6ba6ba
- Group PRD: https://lux.collections.yale.edu/view/group/6b1104a6-4957-4b77-8218-9c686febd8db

**Dependencies/Blocks:**
N/A

**Related Github Issues:**
N/A

**Related links:**
- Bugherd: https://www.bugherd.com/projects/284041/tasks/2118

**Wireframe/Mockup:**
Wireframe not needed as the Related Concepts accordion component should just not appear in the above UAT example.
![image](https://github.com/project-lux/lux-frontend/assets/163148482/949c3d30-9306-4cdc-8886-4f962abd3c22)

**Comment by roamye** [comment]
I left a question above, but I wanted to clarify whether this is only removing the related subjects accordion from the people & group records OR if this is removing all related subjects accordions from all scope records. Please see question above in the question section. 

@kamerynB @prowns

**Comment by prowns** [comment]
Where else does Related Subjects appear?

**Comment by roamye** [comment]
It also appears in event pages. We have a ticket https://github.com/project-lux/lux-frontend/issues/180 where we are updating the related subjects on events pages to be a related list.

**Comment by roamye** [comment]
Approved by UAT

**Comment by roamye** [comment]
Looks good in prod, closing.
