### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by kamerynB** [project-lux/lux-frontend#216]
**Problem Description:**
The current documentation is missing steps.

**Expected Behavior/Solution:**
Update the documentation based on the Requirements.

**Requirements:**

- [x] Specify the minimum node version to have downloaded
- [x] Specify which steps should be completed before moving on to the next section

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [ ] ~Wireframe/Mockup - Mike~
- [ ] ~Committee discussions - Sarah~
- [ ] ~Feasibility/Team discussion - Sarah~
- [ ] ~Backend requirements - TBD~
- [x] Frontend requirements - Kam
- [ ] ~Questions~

**UAT/LUX Examples:**
- Nestor can review this again and try the setup again. If there are still gaps then they can be addressed further.

**Dependencies/Blocks:**
N/A

**Related Github Issues:**
N/A

**Related links:**
N/A

**Wireframe/Mockup:**
N/A

**Comment by roamye** [comment]
Approved by UAT

**Comment by roamye** [comment]
Closing this as Kam had updated the document.
