### ISSUE TITLE
Expanding Search Query for Objects in Collection

### ISSUE THREAD

**Issue by roamye** [project-lux/lux-frontend#221]
**Problem Description:**
Under the group record `Yale University Art Gallery, 1940 -` the `Objects in Collection` Tab only shows three results. However, there should be more results listed as there are multiple objects under Yale University Art Gallery. ([example](https://lux-front-tst.collections.yale.edu/view/results/objects?q=%7B%22text%22%3A%22colors%22%2C%22_lang%22%3A%22en%22%7D&sq=colors&ip=1&if=%7B%22AND%22%3A%5B%7B%22memberOf%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fset%2Fcb466280-c7f2-4edd-8ec2-bf84c64b9150%22%7D%7D%5D%7D&facetRequest=true)) 

Note: The results under YUAG is caused by how their data is vended. All other Units do not show as a collection because collections are handled by the individual departments. 
- [Yale University Library](https://lux.collections.yale.edu/view/group/d07b9b86-0a1e-4026-aa4c-8ecba8bbd9c9)
- [YPM ](https://lux.collections.yale.edu/view/group/0a5ed086-396b-4cc2-8120-fdc3f8953ce2)
- [YCBA](https://lux.collections.yale.edu/view/group/0e8bc04a-6538-4792-b82a-9e0751857e7d)

**Expected Behavior/Solution:**
Move forward with expanding the search query to include an additional block that can search for all objects in a specific collection. 

~Depending on the IT meeting on 05/10, we will move forward with:
 (a) label change to accurately define the results in Objects in Collection or~
 ~(b) have all objects under the Objects in Collection, such as [Yale University Library 1701-](https://lux-front-tst.collections.yale.edu/view/group/d07b9b86-0a1e-4026-aa4c-8ecba8bbd9c9) does.~

**Requirements:**
- Tabs "Objects in Collection" will be re-queried to contain the extra block needed to find all objects in a collection. 
- Query will contain an extra `member of` block. 
- ~Tab "Objects in Collection" will be renamed to reflect a more accurate name.~
- ~new label TBD~

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [ ] Wireframe/Mockup - Mike
- [ ] Committee discussions - Sarah
- [ ] Feasibility/Team discussion - Sarah
- [ ] Backend requirements - TBD
- [ ] Frontend requirements- TBD
- [ ] Questions
- What is the feasibility for YPM/YUL? 
- Should we change the label to accurately define the results? Or change the query to return all objects? 
- Answer: From 5/10 IT Meeting, it was decided a label change would be best. 
- What will it be renamed to? 
- Answer: From conversation below a label change is not needed. Instead this ticket will be re-purposed to expand the current query to capture all the objects in a collecction. 

**UAT/LUX Examples:**
Set pages:
- [YUL](https://lux.collections.yale.edu/view/set/9ccacfdc-9e8d-46d0-a8d8-fdaa09d6e4df)
    -  Will have query of: [this.](https://lux-front-tst.collections.yale.edu/view/results/objects?q=%7B%22OR%22%3A%5B%7B%22memberOf%22%3A%7B%22curatedBy%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fgroup%2F6086b58d-941d-41e3-87c1-e00e96952ffb%22%7D%7D%7D%2C%7B%22memberOf%22%3A%7B%22curatedBy%22%3A%7B%22memberOf%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fgroup%2F6086b58d-941d-41e3-87c1-e00e96952ffb%22%7D%7D%7D%7D%5D%7D)
- YUAG
- YPM
- YCBA

Group pages
- [YUAG](https://lux-front-tst.collections.yale.edu/view/group/6086b58d-941d-41e3-87c1-e00e96952ffb)
- [Yale University Library](https://lux.collections.yale.edu/view/group/d07b9b86-0a1e-4026-aa4c-8ecba8bbd9c9)
- [YPM ](https://lux.collections.yale.edu/view/group/0a5ed086-396b-4cc2-8120-fdc3f8953ce2)
- [YCBA](https://lux.collections.yale.edu/view/group/0e8bc04a-6538-4792-b82a-9e0751857e7d)

**Dependencies/Blocks:**

- Blocked By: Issues that are blocking the completion of the current issue.
- Blocking: Issues being blocked by the completion of the current issue.

**Related Github Issues:**

- [YUL data fix to remove Yale University Library as collection name](https://git.yale.edu/LUX/unit-data/issues/129)

**Related links:**
- Bugherd: https://www.bugherd.com/projects/284041/tasks/2176

**Wireframe/Mockup:**: 
![image](https://github.com/project-lux/lux-frontend/assets/163148482/2d07e372-821d-4ad9-b956-0818e687de03)

**Comment by kamerynB** [comment]
@prowns @roamye We need a label to promote this to prioritization.

**Comment by prowns** [comment]
#agenda for interactions

**Comment by prowns** [comment]
@kamerynB - what happened to the Objects in Collection Tab (see [bugherd](https://www.bugherd.com/projects/284041/tasks/2176
))?   I was going to bring to interactions but it is gone.

**Comment by kamerynB** [comment]
@prowns The HAL link is not in the record. It is `lux:departmentItems`.

**Comment by prowns** [comment]
"lux:departmentItems": {
      "href": "https://lux.collections.yale.edu/api/search/item?q=%7B%22memberOf%22%3A%7B%22curatedBy%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fgroup%2Fd07b9b86-0a1e-4026-aa4c-8ecba8bbd9c9%22%7D%7D%7D",
      "_estimate": 1

**Comment by prowns** [comment]
Additional context/analysis for #agenda.

The "tab" is not appearing on any of the UAT example pages (per Kam, a HAL link issue?), but I also don't understand what is missing from the YUAG data, per the note a the top.
 
We will see this tab a lot in the UI when users click on Collection in results snippets and get to the set. 
Group: https://lux.collections.yale.edu/view/group/b6cb6d82-3a56-443f-8826-139c201afd2a
Set: https://lux.collections.yale.edu/view/set/812660f3-946a-4941-aa85-6ac4fffaa22a

Question: is there ever a need for a "Set" page for a Responsible Unit?  If so, then how would a user get to that SET page?  Would we add a Responsible unit link to the results snippet?

**Comment by prowns** [comment]
This will be solved by hierarchy searching/transitive query.   Will need to change HAL link to use transitive query.  Blocked by ML work in this area.   Need to find that issue.

**Comment by roamye** [comment]
tix forming 6/17: 
Objects that are curated by this group or members of this group. This will add to the query to make it bigger. 

Do we want to expand the query? #agenda 

@prowns 
cc: @clarkepeterf

**Comment by brent-hartwig** [comment]
@prowns, as I under this ticket, we can either change a label (current scope) or have the query find all objects associated to a collection, regardless of the data going through a department.  More general, we're looking to start with a collection, hop a specific predicate until we reach the objects, regardless of how many times we have to hop.

Options that come to mind:

1. CTS can partially meet this need.  It would need to be finite number of hops, but that may suffice for the current dataset.
2. Offer a way to execute select searches outside of CTS (e.g., SPARQL).
3. Wait for the Optic/API exercise to complete.  If Optic is selected, this will be a freebie.

We could select no. 1 or 2 in advance of no. 3, and switch when the time comes.

We should plan a performance test for any selected option.

**Comment by clarkepeterf** [comment]
I think the easiest option is to expand the search to look for objects either curated by this agent, or by a member of this agent:

https://lux-front-tst.collections.yale.edu/view/results/objects?q=%7B%22OR%22%3A%5B%7B%22memberOf%22%3A%7B%22curatedBy%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fgroup%2F6086b58d-941d-41e3-87c1-e00e96952ffb%22%7D%7D%7D%2C%7B%22memberOf%22%3A%7B%22curatedBy%22%3A%7B%22memberOf%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fgroup%2F6086b58d-941d-41e3-87c1-e00e96952ffb%22%7D%7D%7D%7D%5D%7D

**Comment by roamye** [comment]
From it meeting 6/21 this will be brought up to UAT to discuss which option to move forward with. 
Will update tix after meeting 6/27.

**Comment by roamye** [comment]
@brent-hartwig - could ML 11.3 help with option # 3 listed in your comment? 

"Wait for the Optic/API exercise to complete. If Optic is selected, this will be a freebie."

**Comment by roamye** [comment]
From UAT meeting 6/26:
 It is OK to move forward with option 1 (expanding the search) as mentioned by @brent-hartwig @clarkepeterf  while we await if option 3 is possible.

**Comment by brent-hartwig** [comment]
> @brent-hartwig - could ML 11.3 help with option # 3 listed in your comment?
> 
> "Wait for the Optic/API exercise to complete. If Optic is selected, this will be a freebie."

@roamye, ML 11.3 includes an Optic optimization we would want should we switch to Optic.  But Optic in previous ML versions offer the functionality required by this ticket.

**Comment by roamye** [comment]
Closing this ticket as it should be a MT tix. 

That tix can be found here: https://github.com/project-lux/lux-middletier/issues/76 and has moved onto backlog.
