### ISSUE TITLE
Add ErrorBoundary for facets to prevent white screens

### ISSUE THREAD

**Issue by kamerynB** [project-lux/lux-frontend#225]
**Problem Description:**
If a facet request times out, an error is triggered in the frontend causing a white screen.

**Expected Behavior/Solution:**
The frontend will handle errors to prevent the white screen.

**Requirements:**

- [x] Add ErrorBoundary around each facet item to catch Typescript errors.

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [x] Wireframe/Mockup - Kam
- [ ] ~Committee discussions - Sarah~
- [ ] ~Feasibility/Team discussion - Sarah~
- [ ] ~Backend requirements - TBD~
- [x] Frontend requirements - Kam
- [ ] ~Questions~

**UAT/LUX Examples:**

- https://lux.collections.yale.edu/view/results/works?q=%7B%22createdBy%22%3A%7B%22AND%22%3A%5B%7B%22gender%22%3A%7B%22name%22%3A%22female%22%7D%7D%2C%7B%22startAt%22%3A%7B%22classification%22%3A%7B%22name%22%3A%22city%22%7D%7D%7D%5D%7D%7D

Post deployment screenshot from Kam:
![image](https://github.com/project-lux/lux-frontend/assets/140099762/425b8144-323c-4f28-981f-3f8acfed55cc)
SI Event captured (5/15): 
![image](https://github.com/project-lux/lux-frontend/assets/163148482/35903270-a4e0-47af-8166-0a93f9911f13)

**Dependencies/Blocks:**
N/A

**Related Github Issues:**
N/A

**Related links:**
N/A

**Wireframe/Mockup:**
![Screenshot 2024-05-09 at 11 30 36 AM](https://github.com/project-lux/lux-frontend/assets/140102078/0d1220e8-6989-4961-8392-78c8cd74c3d5)

**Comment by roamye** [comment]
@kamerynB
Is there any SI work to be done? or once this is implemented the SI will count it as an error boundary event?

**Comment by kamerynB** [comment]
@roamye The SI events will register with this event.

**Comment by roamye** [comment]
Approved by UAT

**Comment by roamye** [comment]
Looks good in prod, closing.
