### ISSUE TITLE
Do not render data objects if no data is provided

### ISSUE THREAD

**Issue by kamerynB** [project-lux/lux-frontend#232]
**Problem Description:**
There are rare instances of empty data properties in the data and their labels will show but with no data.

**Expected Behavior/Solution:**
The frontend should check if there is data and not render it if the data point is empty.

**Requirements:**

- [x] The frontend will use the existing `hasData` function to ensure a data point contains data before rendering

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [x] Wireframe/Mockup - Kam
- ~Committee discussions - Sarah~
- ~Feasibility/Team discussion - Sarah~
- ~Backend requirements - TBD~
- [x] Frontend requirements - Kam
- [ ] ~Are new regression tests required for QA - Amy~
- ~Questions~

**UAT/LUX Examples:**

- PRD: https://lux.collections.yale.edu/view/object/4ea019e0-7957-43f7-9d52-ac2e7e49b63b
- DEV: https://lux-front-dev.collections.yale.edu/view/object/4ea019e0-7957-43f7-9d52-ac2e7e49b63b

**Dependencies/Blocks:**
N/A

**Related Github Issues:**
N/A

**Related links:**
N/A

**Wireframe/Mockup:**
Current:
![Screenshot 2024-05-15 at 10 59 39 AM](https://github.com/project-lux/lux-frontend/assets/140102078/4682aaf7-8ef7-483b-a155-e71764444aaa)

Expected:
![Screenshot 2024-05-15 at 11 00 21 AM](https://github.com/project-lux/lux-frontend/assets/140102078/f86ac16f-85c6-4088-b734-e9cbad483361)

**Comment by roamye** [comment]
Would this be considered an error boundary for Site Improve to capture? 

@kamerynB

**Comment by kamerynB** [comment]
@roamye No and this is because it isn't caused by an error but rather a lack of data in the record.

**Comment by roamye** [comment]
Approved by UAT

**Comment by roamye** [comment]
Looks good in prod, closing.
