### ISSUE TITLE
Add data validation for entity page sections and only render sections if data is valid

### ISSUE THREAD

**Issue by kamerynB** [project-lux/lux-frontend#238]
**Problem Description:**
There are sections on entity pages with no data.

**Expected Behavior/Solution:**
Only render sections with valid data.

**Requirements:**

-  Retrieve necessary data and then validate with existing hasData function

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [x] Wireframe/Mockup - Kam
- [x] ~Committee discussions - Sarah~
- [x] ~Feasibility/Team discussion - Sarah~
- [x] ~Backend requirements - TBD~
- [x] Frontend requirements - Kam
- [x] ~Are new regression tests required for QA - Amy~
- [x] ~Questions~

**UAT/LUX Examples:**

- https://lux-front-dev.collections.yale.edu/view/object/91721db1-f9d7-435d-ad8f-e5022cedc39f
- PRD: https://lux.collections.yale.edu/view/object/91721db1-f9d7-435d-ad8f-e5022cedc39f

**Dependencies/Blocks:**
N/A

**Related Github Issues:**
N/A

**Related links:**

- Bugherd: https://www.bugherd.com/projects/284041/tasks/2255

**Wireframe/Mockup:**
Current:
![Image](https://github.com/project-lux/lux-frontend/assets/140102078/490d2668-5279-483d-a46f-ef3cda4d6250)

Expected:
![Image](https://github.com/project-lux/lux-frontend/assets/140102078/604bd904-49ba-4c36-a8c3-72459e274518)

**Comment by roamye** [comment]
Approved by UAT

**Comment by roamye** [comment]
looks good in prod, closing.
