### ISSUE TITLE
Fix icon alignment in Safari

### ISSUE THREAD

**Issue by kamerynB** [project-lux/lux-frontend#239]
**Problem Description:**
The advanced search icons do not align with their corresponding fields in Safari.

**Expected Behavior/Solution:**
The icons should align with their fields.

**Requirements:**

- Wrap the content in a span tag

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [x] ~Wireframe/Mockup - Mike~
- [ ] ~Committee discussions - Sarah~
- [x] ~Feasibility/Team discussion - Sarah~
- [x] ~Backend requirements - TBD~
- [x] Frontend requirements - Kam
- [x] ~Are new regression tests required for QA - Amy~
- [x] ~Questions~

**UAT/LUX Examples:**

- [Search link to test](https://lux-front-tst.collections.yale.edu/view/results/objects?q=%7B%22OR%22%3A%5B%7B%22AND%22%3A%5B%7B%22OR%22%3A%5B%7B%22name%22%3A%22Yosemite%22%7D%2C%7B%22encounteredAt%22%3A%7B%22name%22%3A%22Yosemite%22%7D%7D%5D%7D%2C%7B%22OR%22%3A%5B%7B%22AND%22%3A%5B%7B%22encounteredDate%22%3A%221850%22%2C%22_comp%22%3A%22%3E%22%7D%2C%7B%22encounteredDate%22%3A%221900%22%2C%22_comp%22%3A%22%3C%22%7D%5D%7D%2C%7B%22AND%22%3A%5B%7B%22producedDate%22%3A%221850%22%2C%22_comp%22%3A%22%3E%22%7D%2C%7B%22producedDate%22%3A%221900%22%2C%22_comp%22%3A%22%3C%22%7D%5D%7D%5D%7D%2C%7B%22classification%22%3A%7B%22OR%22%3A%5B%7B%22name%22%3A%22painting%22%7D%2C%7B%22name%22%3A%22print%22%7D%2C%7B%22name%22%3A%22plant%22%7D%2C%7B%22name%22%3A%22drawing%22%7D%5D%7D%7D%5D%7D%2C%7B%22carries%22%3A%7B%22AND%22%3A%5B%7B%22OR%22%3A%5B%7B%22aboutPlace%22%3A%7B%22name%22%3A%22yosemite%22%7D%7D%2C%7B%22aboutConcept%22%3A%7B%22name%22%3A%22yosemite%22%7D%7D%5D%7D%2C%7B%22OR%22%3A%5B%7B%22AND%22%3A%5B%7B%22createdDate%22%3A%221850%22%2C%22_comp%22%3A%22%3E%22%7D%2C%7B%22createdDate%22%3A%221900%22%2C%22_comp%22%3A%22%3C%22%7D%5D%7D%2C%7B%22AND%22%3A%5B%7B%22publishedDate%22%3A%221850%22%2C%22_comp%22%3A%22%3E%22%7D%2C%7B%22publishedDate%22%3A%221900%22%2C%22_comp%22%3A%22%3C%22%7D%5D%7D%5D%7D%5D%7D%7D%5D%7D) (must be tested in Safari Browser) 
- [PRD](https://lux.collections.yale.edu/view/results/objects?q=%7B%22OR%22%3A%5B%7B%22AND%22%3A%5B%7B%22OR%22%3A%5B%7B%22name%22%3A%22Yosemite%22%7D%2C%7B%22encounteredAt%22%3A%7B%22name%22%3A%22Yosemite%22%7D%7D%5D%7D%2C%7B%22OR%22%3A%5B%7B%22AND%22%3A%5B%7B%22encounteredDate%22%3A%221850%22%2C%22_comp%22%3A%22%3E%22%7D%2C%7B%22encounteredDate%22%3A%221900%22%2C%22_comp%22%3A%22%3C%22%7D%5D%7D%2C%7B%22AND%22%3A%5B%7B%22producedDate%22%3A%221850%22%2C%22_comp%22%3A%22%3E%22%7D%2C%7B%22producedDate%22%3A%221900%22%2C%22_comp%22%3A%22%3C%22%7D%5D%7D%5D%7D%2C%7B%22classification%22%3A%7B%22OR%22%3A%5B%7B%22name%22%3A%22painting%22%7D%2C%7B%22name%22%3A%22print%22%7D%2C%7B%22name%22%3A%22plant%22%7D%2C%7B%22name%22%3A%22drawing%22%7D%5D%7D%7D%5D%7D%2C%7B%22carries%22%3A%7B%22AND%22%3A%5B%7B%22OR%22%3A%5B%7B%22aboutPlace%22%3A%7B%22name%22%3A%22yosemite%22%7D%7D%2C%7B%22aboutConcept%22%3A%7B%22name%22%3A%22yosemite%22%7D%7D%5D%7D%2C%7B%22OR%22%3A%5B%7B%22AND%22%3A%5B%7B%22createdDate%22%3A%221850%22%2C%22_comp%22%3A%22%3E%22%7D%2C%7B%22createdDate%22%3A%221900%22%2C%22_comp%22%3A%22%3C%22%7D%5D%7D%2C%7B%22AND%22%3A%5B%7B%22publishedDate%22%3A%221850%22%2C%22_comp%22%3A%22%3E%22%7D%2C%7B%22publishedDate%22%3A%221900%22%2C%22_comp%22%3A%22%3C%22%7D%5D%7D%5D%7D%5D%7D%7D%5D%7D)

**Dependencies/Blocks:**
N/A

**Related Github Issues:**
N/A

**Related links:**

- Bugherd: https://www.bugherd.com/projects/284041/tasks/2217

**Wireframe/Mockup:**
Current:
![Screenshot 2024-05-21 at 4 21 15 PM](https://github.com/project-lux/lux-frontend/assets/140102078/a19b124d-dd9d-4475-a8f0-cdd4af479fdd)

Expected:
![Screenshot 2024-05-21 at 4 39 44 PM](https://github.com/project-lux/lux-frontend/assets/140102078/bd4ad62f-3cf6-4863-8d06-22a651cd5789)

**Comment by roamye** [comment]
Approved by UAT

**Comment by roamye** [comment]
Closing as this ticket was marked as Done the week of 6/3.
