### ISSUE TITLE
Add error handling for site improve code

### ISSUE THREAD

**Issue by kamerynB** [project-lux/lux-frontend#240]
**Problem Description:**
The `window._sz` functionality is causing errors in Firefox.

**Expected Behavior/Solution:**
Add error handling around the Site Improve code to prevent white screens.

**Requirements:**

- [x] Check if window._sz is null or undefined

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [x] Wireframe/Mockup - Kam
- [x] ~Committee discussions - Sarah~
- [x] ~Feasibility/Team discussion - Sarah~
- [x] ~Backend requirements - TBD~
- [x] Frontend requirements - Kam
- [x] ~Are new regression tests required for QA - Amy~
- [x] ~Questions~

**UAT/LUX Examples:**
Steps to test:

1. Open a private window in Firefox
2. Navigate to the landing page
3. It should render and not show a white screen

**Dependencies/Blocks:**
N/A

**Related Github Issues:**
N/A

**Related links:**
N/A

**Wireframe/Mockup:**
Current:
![Screenshot 2024-05-22 at 11 10 17 AM](https://github.com/project-lux/lux-frontend/assets/140102078/b05f7751-01b6-4941-ab4e-11afed5a110c)

Expected should just be the normal landing page.

**Comment by gigamorph** [comment]
In addition to the null check, please print an error message (console.error) to the console including the parameters passed to the function, which could help us determine in the longer run whether the problem can be fixed so the error would never occur.

**Comment by kamerynB** [comment]
Deploying to DEV.

cc: @jffcamp @azaroth42 @roamye @prowns

**Comment by roamye** [comment]
Closing as this was a hot fix and is in all environments.
