### ISSUE TITLE
Add types to sets pages

### ISSUE THREAD

**Issue by kamerynB** [project-lux/lux-frontend#241]
**Problem Description:**
Sets currently do not render their types.

**Expected Behavior/Solution:**
Render the types.

**Requirements:**

- [x] Add getTypes function to collections about page for rendering types list (kam ticket) 

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [ ] ~Wireframe/Mockup - Mike~
- [ ] ~Committee discussions - Sarah~
- [ ] ~Feasibility/Team discussion - Sarah~
- [ ] ~Backend requirements - TBD~
- [x] Frontend requirements - Kam
- [ ] ~Are new regression tests required for QA - Amy~
- [ ] ~Questions~

**UAT/LUX Examples:**
- TST: https://lux-front-tst.collections.yale.edu/view/set/664c4aeb-532f-46a2-9db8-4d0b51c73a64
- PRD: https://lux.collections.yale.edu/view/set/664c4aeb-532f-46a2-9db8-4d0b51c73a64

**Dependencies/Blocks:**
N/A

**Related Github Issues:**

- #88 

**Related links:**
N/A

**Wireframe/Mockup:**
Current: 
![image](https://github.com/project-lux/lux-frontend/assets/163148482/551eb475-27ca-4604-97f9-793fd228ce8b)
Update: 
![Screenshot 2024-03-04 at 3 32 46 PM](https://github.com/project-lux/lux-frontend/assets/140102078/3ad9d038-85b1-4eaf-af7d-be16e72e49ea)

**Comment by roamye** [comment]
![image](https://github.com/project-lux/lux-frontend/assets/163148482/b45750b2-00fb-4c59-a5f1-ec59aa407e08)


@kamerynB - Noticed the Exhibition Event doesn't show in TST/DEV. Can this be a hot fix? Else I can add a new tix for this.

**Comment by roamye** [comment]
@kamerynB apologies, I realized they were separate tickets after making the comment. 

This ticket is approved by UAT

**Comment by roamye** [comment]
Closing as this ticket was marked as Done the week of 6/3.
