### ISSUE TITLE
Render the place image if no map data is provided

### ISSUE THREAD

**Issue by kamerynB** [project-lux/lux-frontend#242]
**Problem Description:**
There are records with no map but have images. These images are not rendered.

**Expected Behavior/Solution:**
If there is no map data and an image exists in the data, render the image.

**Requirements:**

- [x] Add function to check if place has map data and images

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [x] Wireframe/Mockup - Kam
- [ ] ~Committee discussions - Sarah~
- [ ] ~Feasibility/Team discussion - Sarah~
- [ ] ~Backend requirements - TBD~
- [x] Frontend requirements - Kam
- [ ] ~Are new regression tests required for QA - Amy~
- [ ] ~Questions~

**UAT/LUX Examples:**
- TST: https://lux-front-tst.collections.yale.edu/view/place/bb8f6825-7a0c-4085-95c5-3a4599dcbd23
- PRD: https://lux.collections.yale.edu/view/place/bb8f6825-7a0c-4085-95c5-3a4599dcbd23

**Dependencies/Blocks:**
N/A

**Related Github Issues:**
N/A

**Related links:**

- Bugherd: https://www.bugherd.com/projects/284041/tasks/2266

**Wireframe/Mockup:**
![Screenshot 2024-05-22 at 2 25 07 PM](https://github.com/project-lux/lux-frontend/assets/140102078/fa1914cf-e172-47dd-ae54-943d100cdc20)

**Comment by prowns** [comment]
@kamerynB, @miketullo95  and @roamye - this one needs a mockup before promoting

**Comment by kamerynB** [comment]
@prowns A mockup has been added.

cc: @miketullo95 @roamye

**Comment by roamye** [comment]
Approved by UAT

**Comment by roamye** [comment]
Closing as this ticket was marked as Done the week of 6/3.
