### ISSUE TITLE
Change How Do I See It default link text

### ISSUE THREAD

**Issue by kamerynB** [project-lux/lux-frontend#243]
**Problem Description:**
If no identified_by data is provided the default link text is "View this item on the collection website" which is not accurate as not all links will be collection links.

**Expected Behavior/Solution:**
The default text should be the link itself.

**Requirements:**

- [x] Change the default text in the HowDoISeeIt component
- [x] Ensure text wrapping of link so that it does not spill out of it's container

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [x] Wireframe/Mockup - Kam
- [ ] ~Committee discussions - Sarah~
- [ ] ~Feasibility/Team discussion - Sarah~
- [ ] ~Backend requirements - TBD~
- [x] Frontend requirements - Kam
- [ ] ~Are new regression tests required for QA - Amy~
- [ ] ~Questions~

**UAT/LUX Examples:**

- DEV: https://lux-front-dev.collections.yale.edu/view/text/fada5383-ef3c-4b34-98d4-4ef55a51c0b0
- PRD: https://lux.collections.yale.edu/view/text/fada5383-ef3c-4b34-98d4-4ef55a51c0b0

**Dependencies/Blocks:**
N/A

**Related Github Issues:**
N/A

**Related links:**

- Bugherd: https://www.bugherd.com/projects/284041/tasks/2275

**Wireframe/Mockup:**
Current:
![Screenshot 2024-05-22 at 12 28 28 PM](https://github.com/project-lux/lux-frontend/assets/140102078/b14d01f9-7cdd-4934-84f8-358763b7244d)

Expected:
![Screenshot 2024-05-22 at 12 29 08 PM](https://github.com/project-lux/lux-frontend/assets/140102078/37240879-c00a-4430-bd42-42ba19a64bce)

**Comment by roamye** [comment]
Approved by UAT

**Comment by roamye** [comment]
Closing as this ticket was marked as Done the week of 6/3.
