### ISSUE TITLE
Result list for all works with this component term

### ISSUE THREAD

**Issue by roamye** [project-lux/lux-frontend#250]
This was fixed by https://github.com/project-lux/lux-middletier/issues/85

**Problem Description:**
For some concept pages, we have the message "Yale University does not have any objects or works directly related to this concept.". Although, they do not have objects/works directly related their component terms may have works related to them. However, since this functionality is not in place, users would have to look through each result in the **concepts influenced** accordion of the page. 

~In addition - the explore visualization only shows one item (this component). Unclear if this is true for all component terms~

From conversation with Kam, this above comment is no longer needed as it is a bug that will be fixed in #297. There is no need to understand what the visualizations will do as component terms and the explore are not connected. 

**Expected Behavior/Solution:**
Create a tab on concept records for "Works with this Concept Component Term" which finds all works related for a component term of the concept. 

- [Fascism--United States](https://lux-front-tst.collections.yale.edu/view/concept/e73aed00-04f2-483d-b0ba-8ff988f248fd) - user clicks on component term United States
- [United States](https://lux-front-tst.collections.yale.edu/view/place/f14804ea-6bd1-4bfb-9394-6f5428c83c34)
-- Add a Works with this Concept Component Term tab. 
-- Would be a search that returns any work that has any of the subject headings listed under "Concepts Influenced"

**Requirements:**
- Create new tab "Works with this Concept Component term" is listed on concept records and functions similarly as the "Works Related" tab. 
- TBD: validate tab label (CORE TEAM) 
- ~TBD: validate feasibility of offering this results list~
- ~TBD: what to do with Explore visualization here~

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [ ] Tab/Label decision - Core Team
- [x] Wireframe/Mockup - Mike
- [ ] ~Committee discussions - Sarah~
- [x] Feasibility/Team discussion - Sarah
- [x] Backend requirements - TBD - MT ticket listed below. 
- [ ] Frontend requirements- TBD
- [ ] Are new regression tests required for QA - Amy
- [x] Questions
- List of questions for discussions. Answers should be documented within the issue.

**UAT/LUX Examples:**
- pre-coordinated subject heading with component terms:  https://lux-front-dev.collections.yale.edu/view/concept/1fa3c3a7-50ca-4ae9-bce8-7098d041f5a8
- subject heading component term page (this ticket): https://lux-front-dev.collections.yale.edu/view/concept/12927247-87b8-43a3-a12d-ff3cd7082324

**Dependencies/Blocks:**

**Related Github Issues:**
- MT: https://github.com/project-lux/lux-middletier/issues/85

**Related links:**
- Bugherds: https://www.bugherd.com/projects/284041/tasks/2237
- https://www.bugherd.com/projects/284041/tasks/2288

**Wireframe/Mockup:**
Current: 
![image](https://github.com/project-lux/lux-frontend/assets/163148482/3bc424ef-c178-4a2e-aee7-505788f75cc1)

Expected: 
![Image](https://github.com/user-attachments/assets/6c5b1cda-2d2d-4c15-b6e9-56e267bc9d69)

**Comment by prowns** [comment]
Per ticket forming - could expand the HAL link for this query to include component terms and then would get a list of Works Related (everything with that component term) 

This will need a new MT ticket to update the HAL link for Works Related.

**Comment by prowns** [comment]
Examples from Rob
[United States](https://lux.collections.yale.edu/view/results/works?q=%7B%22AND%22%3A%5B%7B%22aboutConcept%22%3A%7B%22influencedByPlace%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fplace%2Ff14804ea-6bd1-4bfb-9394-6f5428c83c34%22%7D%7D%7D%5D%7D
) - 

[History](https://lux.collections.yale.edu/view/results/works?q=%7B%22text%22%3A%22history%22%2C%22_lang%22%3A%22en%22%7D&sq=history) - works tab, more or less.

**Comment by kamerynB** [comment]
@roamye @jffcamp @prowns This issue will not require a frontend ticket, only the HAL link update.

**Comment by roamye** [comment]
UAT 8/7: 

Fine to close as it did not need a FE ticket.
