### ISSUE TITLE
Update tooltips with minor accessibility updates

### ISSUE THREAD

**Issue by kamerynB** [project-lux/lux-frontend#255]
**Problem Description:**
The tooltip passes accessibility requirements but there have been suggestions to improve accessibility.

**Expected Behavior/Solution:**
The tooltip will have several updates made to it. Refer to the Requirements section of this ticket for further detail.

**Requirements:**

- [x] add an aria-label to the button called "Tooltip"
- [x] when the tooltip is closed set aria-expanded to false and when it opens, set it to true. 
- [x] increase font weight

**Needed for promotion:**

- [x] Wireframe/Mockup - Kam
- [x] ~Committee discussions - Sarah~
- [x] ~Feasibility/Team discussion - Sarah~
- [x] ~Backend requirements - TBD~
- [x] Frontend requirements - Kam
- [x] ~Are new regression tests required for QA - Amy~
- [x] ~Questions~

**UAT/LUX Examples:**

- https://lux-front-dev.collections.yale.edu/view/person/34f4eec7-7a03-49c8-b1be-976c2f6ba6ba
- PRD: https://lux.collections.yale.edu/view/person/34f4eec7-7a03-49c8-b1be-976c2f6ba6ba

**Dependencies/Blocks:**
N/A

**Related Github Issues:**
N/A

**Related links:**

- Bugherd: https://www.bugherd.com/projects/284041/tasks/2253

**Wireframe/Mockup:**
Current:
<img width="780" alt="Screenshot 2024-05-28 at 4 57 26 PM" src="https://github.com/project-lux/lux-frontend/assets/140102078/586e67e0-ba85-4de8-854b-4ea8a045219d">

Expected:
<img width="780" alt="Screenshot 2024-05-28 at 4 57 18 PM" src="https://github.com/project-lux/lux-frontend/assets/140102078/cbb2e314-2c30-46e6-a5e9-16364ae2dad7">

**Comment by roamye** [comment]
Approved by UAT

**Comment by roamye** [comment]
Looks good in prod, closing.
