### ISSUE TITLE
Show more information about place primary names in UI (from 1726)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-frontend#26]
https://www.bugherd.com/projects/284041/tasks/634

comments from old tix: Per triage session - very high dev costs/time costs, but noting importance.

**Comment by roamye** [comment]
has a label of wontfix on the BH, should this issue be closed?

**Comment by prowns** [comment]
Propose close.  This ticket is replaced by #89

**Comment by roamye** [comment]
per last UAT meeting this was approved to close. 03/27
