### ISSUE TITLE
Add paginations to DATE facets on results pages 

### ISSUE THREAD

**Issue by roamye** [project-lux/lux-frontend#262]
**Problem Description:**
The facets are causing performance issues. This ticket will cover the facet of DATES only. 

**Expected Behavior/Solution:**
ML will return the activity streams and paginations will be required for facets containing lists. 

For facets on the results page, the frontend will make a request to both the first page and last page of the date results to get the earliest and latest dates. From there, the frontend can generate the range input fields with a minimum and maximum year.

**Requirements:**
- TBD

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [ ] Wireframe/Mockup - Mike
- [ ] Committee discussions - Sarah
- [ ] Feasibility/Team discussion - Sarah
- [ ] Backend requirements - TBD
- [ ] Frontend requirements- TBD
- [ ] Are new regression tests required for QA - Amy
- [ ] Questions
- List of questions for discussions. Answers should be documented within the issue.

**UAT/LUX Examples:**

- EAny search result
- Specefic link TBD

**Dependencies/Blocks:**

- Blocked By: https://github.com/project-lux/lux-marklogic/issues/160
- Blocked By: https://github.com/project-lux/lux-marklogic/issues/161
- Blocked By: https://github.com/project-lux/lux-middletier/issues/65

**Related Github Issues:**

- All other facets: https://github.com/project-lux/lux-frontend/issues/252

**Related links:**

- These links can consist of resources, bugherds, etc.

**Wireframe/Mockup:**
Place wireframe/mockup for the proposed solution at end of ticket.

**Comment by kamerynB** [comment]
Closing as this was covered by #252.
