### ISSUE TITLE
Add Professional Activity Categorized As facet in People & Group  Simple Search

### ISSUE THREAD

**Issue by roamye** [project-lux/lux-frontend#268]
**Problem Description:**
There is no way to search for people or groups with a certain professional activity in Simple search. 

**Expected Behavior/Solution:**
Create a facet for "Professional Activity  Categorized As " in /Simple Search. 

**Requirements:**
- Facet option 'professional activity categorized as" will display in simple search People & Groups tab. 

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [x] Wireframe/Mockup - Mike
- [x] Committee discussions - Sarah
- [x] Feasibility/Team discussion - Sarah
- [x] Backend requirements - TBD
- [x] Frontend requirements- TBD
- [x] Are new regression tests required for QA - Amy | Yes
- [x] Questions
- List of questions for discussions. Answers should be documented within the issue.

**UAT/LUX Examples:**
- TST SS: https://lux-front-tst.collections.yale.edu/view/results/people?q=%7B%22AND%22%3A%5B%7B%22text%22%3A%22andy%22%2C%22_lang%22%3A%22en%22%7D%2C%7B%22text%22%3A%22warhol%22%2C%22_lang%22%3A%22en%22%7D%5D%7D&sq=andy+warhol 

**Dependencies/Blocks:**

- ML: https://github.com/project-lux/lux-marklogic/issues/156

**Related Github Issues:**

**Related links:**

- Bugherd: https://www.bugherd.com/projects/284041/tasks/2231

**Wireframe/Mockup:**

Simple Search Updated: 
![image](https://github.com/project-lux/lux-frontend/assets/163148482/7d99616a-9895-4eed-ac45-9ac065079fd3)

**Comment by roamye** [comment]
Mockups have been updated.

**Comment by kamerynB** [comment]
Update 6/14:
This issue is blocked as it requires ML configuration to be implemented. The ML issue has been prioritized for the 6/24 milestone deadline.

**Comment by roamye** [comment]
@kamerynB - I cannot find the AS `Professional Activity Categorized As` single field available in TST. Hot fix.....

Hmm, does the label addition need to happen in ML side and not FE?

**Comment by roamye** [comment]
from uat 7/22: 

this needs a hot fix from the ML ticket: https://github.com/project-lux/lux-marklogic/issues/156

**Comment by kamerynB** [comment]
@roamye @jffcamp @prowns  I'd like to keep this issue in the Reviewable column because the change will happen in ML 156 but this will have to be reviewed again on the frontend as well. The hotfix does not require a frontend change though.

**Comment by clarkepeterf** [comment]
@roamye @jffcamp @prowns what is the requirement for the advanced search field? At current, the field can only accept "ID" search terms. If we also want to search the child concepts by other fields (E.g. "Name", "Anywhere") we will either need to:
1. Add a triple in the data
OR
2. Add a new search pattern in ML (large ML change)

**Comment by prowns** [comment]
The wireframe shows a Name field, so this is a question for @azaroth42 - can there be a new triple?

**Comment by azaroth42** [comment]
A new triple ... for what? The name directly? No, definitely not. A shortcut from actor to the Type, sure.

**Comment by clarkepeterf** [comment]
@azaroth42 our current search patterns only support child search terms when the parent term is a triple. So using the index, we can only search for the LUX ID of the professional activity concept. So, yes the proposal would be to add a triple linking agent to the professional activity

**Comment by azaroth42** [comment]
added `lux:typeOfProfessionalActivity` from agents to concepts, other than the professional activity type itself.

**Comment by roamye** [comment]
Two separate issues have been created to tackle the AS portion of this. 

https://github.com/project-lux/lux-frontend/issues/305 & https://github.com/project-lux/lux-marklogic/issues/248. 

This issue is approved by UAT as it only covers SS facets.

**Comment by roamye** [comment]
Looks good in PROD. Closing...

Might need a seperate issue as some records do not display it's professional activity although it is listed in the JSON.
