### ISSUE TITLE
Improve Sorting of archival materials (from 1727)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-frontend#27]
**Problem Description:**
The lists of children in archives are not sorted in any way, however the intellectual arrangement of the archive is intentional as to the order. 

**Expected Behavior:**
This order should be preserved in the view of the list of members of the Set.

**Development details:**

The order is to be determined by the `value` of an `Identifier` in the `identified_by` field of the record, sorted alphanumerically from lowest to highest. 

**Requirements:**

- [x] the frontend will suppress identifiers that are classified as sorting (https://lux-front-tst.collections.yale.edu/data/concept/ab99d278-9323-4d84-8e97-1846058fc587)
- [x] Requests to works should be made before requests to objects
- [x] The current entity should be bolded and underlined
- [x] Remove the functionality that pushes the current entity to the top of its archive list

Example identifier to be used for sorting purposes:
```
    {
      "type": "Identifier",
      "content": "000016f200000bd7",
      "assigned_by": [
        {
          "type": "AttributeAssignment",
          "motivated_by": [
            {
              "id": "https://lux-front-tst.collections.yale.edu/data/set/3a62131a-55cc-475a-a2c9-1e253dd3ab3a",
              "type": "Set",
              "_label": "Series V: Audio Recordings, 1964-1996"
            }
          ]
        }
      ],
      "classified_as": [
        {
          "id": "https://lux-front-tst.collections.yale.edu/data/concept/ab99d278-9323-4d84-8e97-1846058fc587",
          "type": "Type",
          "_label": "Sort Name"
        }
      ]
    }
```

**UAT/LUX Examples:**

-TST:  https://lux-front-tst.collections.yale.edu/view/set/41f35f57-5490-46fe-9225-2ab7053fd053 - Archival Explore should appear in series order. 
- TST:  https://lux-front-tst.collections.yale.edu/view/set/5eb30c32-31aa-4a3a-a0c0-845aec1c4880
- TST:  https://lux-front-tst.collections.yale.edu/view/object/ed2f1d23-5b04-43b7-939f-318029478167
- TST Set with Members of Sets/Objects: https://lux-front-tst.collections.yale.edu/view/set/9e7a1c79-8fa0-4eaf-9570-a3cbce09fac2

**Dependencies/Blocks:**

- [x] Blocked by: https://github.com/project-lux/lux-marklogic/issues/38
- [x] Blocked by: https://github.com/project-lux/lux-marklogic/issues/90
- [x] Blocked by https://github.com/project-lux/lux-middletier/issues/47
- [x] requires new data set

**Related Github Issues:**
N/A

**Related links:**

- Bugherd: https://www.bugherd.com/projects/284041/tasks/927

**Wireframe/Mockup:**
N/A

**Comment by prowns** [comment]
@kamerynB - per conversation with RS, this is not blocked by https://github.com/project-lux/lux-marklogic/issues/38 and can be implemented.

**Comment by kamerynB** [comment]
Per 3/22 meeting:
The [inverted terms](https://lux-front-tst.collections.yale.edu/data/concept/31497b4e-24ad-47fe-88ad-af2007d7fb5a) vs [sort name](https://lux-front-tst.collections.yale.edu/data/concept/ab99d278-9323-4d84-8e97-1846058fc587) is a data issue and should technically be one record. In the meantime, the frontend should hard code the sort name on identifiers and will later be updated to use one data constant.

**Comment by kamerynB** [comment]
@azaroth42 This issue is blocked by ML. The frontend retrieves all ancestors (direct parent, direct grandparent, direct great-grandparent, etc) and then retrieves the children of each of those ancestors via the HAL links `lux:setIncludedItems` and `lux:setIncludedWorks`. If each of these returns more than 20 children each, the frontend has a "Show More/Less" button. But this means that not all entities can be sorted unless there is a way to tell ML to sort them with a `sort` param on the HAL link request. There will be inconsistent sorting otherwise.

cc: @clarkepeterf

**Comment by azaroth42** [comment]
Yes - blocked by enabling the sort at the backend index, then putting it into the HAL links. Front end doesn't need to actually /do/ anything differently.

This is as close as I can get to the sort:

https://lux.collections.yale.edu/view/results/works?q=%7B%22partOf%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fset%2Fc4a26744-8534-4e00-b263-45fae2423007%22%7D%7D&ws=anySortName%3Aasc

but should be the new sortIdentifier not anySortName.

**Comment by kamerynB** [comment]
The frontend should make all requests for works first and if there are no more works, then make requests for objects.

**Comment by roamye** [comment]
Approved by UAT

**Comment by roamye** [comment]
Closing as this ticket was marked as Done the week of 6/3.
