### ISSUE TITLE
Remove the workShownBy HAL link config

### ISSUE THREAD

**Issue by kamerynB** [project-lux/lux-frontend#277]
**Problem Description:**
The HAL link workShownBy is no longer offered.

**Expected Behavior/Solution:**
The configuration for workShownBy should be removed. The frontend will behave the same way once removed.

**Requirements:**

- [x] Remove the config

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [ ] ~Wireframe/Mockup - Mike~
- [ ] ~Committee discussions - Sarah~
- [ ] ~Feasibility/Team discussion - Sarah~
- [x] Backend requirements - Middle tier issue, Kam
- [x] Frontend requirements - Kam
- [ ] Are new regression tests required for QA - Amy
- [ ] ~Questions~

**UAT/LUX Examples:**

- https://lux-front-tst.collections.yale.edu/view/text/6aaa7701-02e7-4249-9bf5-faf1edc2c652

**Dependencies/Blocks:**
N/A

**Related Github Issues:**

- https://github.com/project-lux/lux-middletier/issues/15

**Related links:**
N/A

**Wireframe/Mockup:**
N/A

**Comment by roamye** [comment]
Approved as Hot Fix.

**Comment by roamye** [comment]
Looks good in PROD Json. Closing.
