### ISSUE TITLE
Add search link to show archival sets results containing digital image thumbnails (from 1728)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-frontend#28]
**Problem` Description:**
This is an enhancement to the explore hierarchy feature.  Although we now have a icon to indicate archival objects that have digital images, there is no easy way for a user to browse the digital images on the archival collection level.

**Expected Behavior/Solution:**
The hierarchy will have a link to the results page where a user can view records with images. The HAL link will have to cover objects and works.

**Requirements:**
- link on archival set page
- corresponding object results page (when user follows link)

**Needed for promotion:**

- [x] Wireframe/Mockup - Mike
- [x] Update mock-up to make link more prominent. Looks like it is part of the list above, but misaligned - Mike
- [x] Feasibility/Team discussion - Sarah
- [x] additional requirements - TBD
- [x] https://github.com/project-lux/lux-middletier/issues/14 (119)
- [ ] Questions
- List of questions for discussions. Answers should be documented within the issue.

**UAT/LUX Examples:**
- https://lux-front-tst.collections.yale.edu/view/set/5f1ff079-5f3a-4bd6-921a-5c6ae8f88262
- https://lux.collections.yale.edu/view/set/2bbba369-f848-42ee-8b25-b2d56da76b01
- ~[Advanced Search Query](https://lux.collections.yale.edu/view/results/objects?q=%7B%22AND%22%3A%5B%7B%22hasDigitalImage%22%3A1%7D%2C%7B%22OR%22%3A%5B%7B%22memberOf%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fset%2F2bbba369-f848-42ee-8b25-b2d56da76b01%22%7D%7D%2C%7B%22memberOf%22%3A%7B%22member%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fset%2F2bbba369-f848-42ee-8b25-b2d56da76b01%22%7D%7D%7D%2C%7B%22memberOf%22%3A%7B%22member%22%3A%7B%22memberOf%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fset%2F2bbba369-f848-42ee-8b25-b2d56da76b01%22%7D%7D%7D%7D%2C%7B%22memberOf%22%3A%7B%22member%22%3A%7B%22memberOf%22%3A%7B%22member%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fset%2F2bbba369-f848-42ee-8b25-b2d56da76b01%22%7D%7D%7D%7D%7D%5D%7D%5D%7D)~ (No longer applicable) 
- ~[advanced search query](https://lux.collections.yale.edu/view/results/objects?q=%7B%22AND%22%3A%5B%7B%22hasDigitalImage%22%3A1%7D%2C%7B%22OR%22%3A%5B%7B%22memberOf%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fset%2F2bbba369-f848-42ee-8b25-b2d56da76b01%22%7D%7D%2C%7B%22memberOf%22%3A%7B%22member%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fset%2F2bbba369-f848-42ee-8b25-b2d56da76b01%22%7D%7D%7D%2C%7B%22memberOf%22%3A%7B%22member%22%3A%7B%22memberOf%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fset%2F2bbba369-f848-42ee-8b25-b2d56da76b01%22%7D%7D%7D%7D%5D%7D%5D%7D)~ (No longer applicable) 

**Dependencies/Blocks:**

- Blocked By: Issues that are blocking the completion of the current issue.
- Blocking: Issues being blocked by the completion of the current issue.

**Related Github Issues:**

- Issues that contain similar work but are not blocking or being blocked by the current issue.

**Related links:**
Bugherd: - https://www.bugherd.com/projects/284041/tasks/851

**Wireframe/Mockup:**
![Image](https://github.com/project-lux/lux-frontend/assets/98550395/b0da7bfc-da37-4a7f-9124-776278c089f0)

**Comment by ar2674** [comment]
@miketullo95 should this be assigned to you instead?

**Comment by roamye** [comment]
From old tix(https://git.yale.edu/lux-its/lux-web/issues/1728): 
12/5/23
Per ticket forming - ready to promote as blocked and needing HAL link completed.

**Comment by prowns** [comment]
@miketullo95 - this is for you next; mockup needs updating.

**Comment by kamerynB** [comment]
This will require 2 links. One for `View objects from this archive with images` and the other being `View works from this archive with images`. The hierarchy shows both works and objects.

cc: @miketullo95

**Comment by prowns** [comment]
@kkdavis14 - would there ever be works with images in archival hierarchy? I'm thinking not. Only the archival object is digitized.

**Comment by kkdavis14** [comment]
@prowns I don't think so, archival Objects don't carry any Works, and I think all the Works that are Archives are top level or Series level collections, not Visual Items or Textual Works.

**Comment by roamye** [comment]
I looked at the third UAT example in tst [(here)](https://lux-front-tst.collections.yale.edu/view/results/objects?q=%7B%22AND%22%3A%5B%7B%22hasDigitalImage%22%3A1%7D%2C%7B%22OR%22%3A%5B%7B%22memberOf%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fset%2F2bbba369-f848-42ee-8b25-b2d56da76b01%22%7D%7D%2C%7B%22memberOf%22%3A%7B%22member%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fset%2F2bbba369-f848-42ee-8b25-b2d56da76b01%22%7D%7D%7D%2C%7B%22memberOf%22%3A%7B%22member%22%3A%7B%22memberOf%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fset%2F2bbba369-f848-42ee-8b25-b2d56da76b01%22%7D%7D%7D%7D%5D%7D%5D%7D) and it shows me an error. Is that supposed to happen? @kamerynB

**Comment by kamerynB** [comment]
@roamye I'm not sure why those search links are in the UAT block. The ones to be concerned about are the entity links, ie the first 2 UAT examples. The archives in those entities should have a link saying `View records from this archive with images` and those links should be valid. I'm not sure where those search links came from.

**Comment by roamye** [comment]
@kamerynB looks like it was added back in 2023 (old issue). I will strike them out. Thanks Kam.

**Comment by kamerynB** [comment]
@jffcamp A PR for the hotfix is already open.

What it will look like:
![Screenshot 2024-05-16 at 10 07 30 AM](https://github.com/project-lux/lux-frontend/assets/140102078/94b92c9f-b849-4c89-9656-9311bc9f3940)

**Comment by roamye** [comment]
@kamerynB I believe the archive collection name also needs to be bold to reflect the wireframe in the mockup. 

cc: @jffcamp

**Comment by kamerynB** [comment]
@roamye I've included that in #27. The current entity link has not been bolded since I deployed the SI changes as I accidentally removed that styling when making those changes. That bug was not introduced with this deployment.

cc: @jffcamp

**Comment by jffcamp** [comment]
@kamerynB - Thanks. Please deploy.

**Comment by kamerynB** [comment]
Deployed!

cc: @roamye @jffcamp

**Comment by roamye** [comment]
Approved by UAT

**Comment by roamye** [comment]
Looks good in prod, closing.
