### ISSUE TITLE
Modify the AS queries from HAL Link 

### ISSUE THREAD

**Issue by roamye** [project-lux/lux-frontend#290]
**Problem Description:**
Advanced Search queries from HAL links, such as the `show all X results`, usually display the single field of `Have all of` or `Have any of`. 

When the first line contains `Have any of` this causes an issue where any addition of an `add row` now creates an OR statement only. 

A User would then need to clear their search, recreate the system generate id searchs, and re-query it to display:
```
Have All of
| - Have any of 
|       [Sub query] 
|       Add row
Add row
```

So they can expand their search with AND and OR statements. 

**Expected Behavior/Solution:**
Default the top line with `Have All of` for those AS queries which open with `Have any of` so users can use both AND and OR statements within their search.  This allows users to refine system generated searches with additional criteria. 

**Requirements:**
For AS queries with `have any of`...
- default the top line with `Have All of`
- make the `have any of` block into a sub-block of `have all of`. 

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [x] Wireframe/Mockup - Mike
- [ ] Committee discussions - Sarah
- [ ] Feasibility/Team discussion - Sarah
- [ ] Backend requirements - TBD
- [ ] Frontend requirements- TBD
- [ ] ~Are new regression tests required for QA - Amy~
- [x] Questions
- List of questions for discussions. Answers should be documented within the issue.

**UAT/LUX Examples:**
- DEV: https://lux-front-dev.collections.yale.edu/view/results/works?q=%7B%22AND%22%3A%5B%7B%22OR%22%3A%5B%7B%22createdBy%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fperson%2F47dc8b26-b9e8-48d3-b3ef-db9308565b09%22%7D%7D%2C%7B%22publishedBy%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fperson%2F47dc8b26-b9e8-48d3-b3ef-db9308565b09%22%7D%7D%2C%7B%22creationInfluencedBy%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fperson%2F47dc8b26-b9e8-48d3-b3ef-db9308565b09%22%7D%7D%5D%7D%5D%7D&searchLink=true

**Dependencies/Blocks:**
- N/A

**Related Github Issues:**
- https://github.com/project-lux/lux-frontend/issues/265

**Related links:**
- N/A

**Wireframe/Mockup:**
![image](https://github.com/project-lux/lux-frontend/assets/163148482/5c772561-a72d-4e08-b36f-e025660cbde4)

**Comment by kamerynB** [comment]
Per 7/12/24 meeting:
This is feasible. HAL links should have a wrapping AND query around them. It also needs to be determined if there are any search links on the frontend that also require this wrapping in the frontend code.

**Comment by clarkepeterf** [comment]
The middle tier solution is possible. A similar situation is possible with many other queries though. My preference to solve this issue would be to make a button / gear option similar to "add row" but instead of adding a field on the inside of the current field, it adds a field on the outside of the current field.

**Comment by roamye** [comment]
@clarkepeterf - to clarify, would the benefit be that **all AS queries** (those from hal links/those being created from AS) will have the ability to add fields on the outside of its current field? Rather than what is being currently listed here? (which only applies to AS queries from HAL Links) 

If that is the case - then I think it should be part of a separate ticket.

**Comment by roamye** [comment]
@clarkepeterf Added this as a discussion topic for UAT.

**Comment by kamerynB** [comment]
> The middle tier solution is possible. A similar situation is possible with many other queries though. My preference to solve this issue would be to make a button / gear option similar to "add row" but instead of adding a field on the inside of the current field, it adds a field on the outside of the current field.

@clarkepeterf This was the original solution and it was deemed not feasible.

**Comment by clarkepeterf** [comment]
@kamerynB Why is it not feasible?

**Comment by clarkepeterf** [comment]
I don't like this approach but I'll go along with it if that's what everyone else wants

**Comment by kamerynB** [comment]
@clarkepeterf Discussing this with @prowns again, this issue only pertains to HAL links, not the advanced search directly. When following a HAL link, user's can add to the highest level of the search. By wrapping it in a `has All of`, it gives users a chance to append to the original search at its high level.

**Comment by roamye** [comment]
@kamerynB - will this be deployed before today @ 4pm? Uat is today during that time today and it still does not show the fix in lower environments.

**Comment by roamye** [comment]
Approved by UAT

**Comment by roamye** [comment]
Looks good in prod. Closing.
