### ISSUE TITLE
Fix front end and hierarchy rendering issues. 

### ISSUE THREAD

**Issue by roamye** [project-lux/lux-frontend#297]
**Problem Description:**
2. records are not re-rendering so it will show incorrect data under parents/children when going back to a previous record.
3.  Show More/Show Less button is showing even when there are only 5 parents

1. ~The explore record renders parent/childrens label when data does not exist.~ (has been moved to 332)  
~For the Concept record [Andy Warhol, 1928-1987](https://lux-front-dev.collections.yale.edu/view/concept/684a5568-f2fc-42f6-a339-eaa1fa7635b4) the explore section shows "Parents" but does not list any of it underneath it. This happens in all env.~
~Additionally, if you click on the component term `exhibitions` and click return then the original record now lists incorrect information under the explore section. However it still does not list any parent information.~ 
~This ticket serves as a research ticket to figure out why this is happening and to propose a potential solution.~

**Expected Behavior/Solution:**
- Issue 2: have the hierarchy records re-render when going back and forth to different records.
- Issue 3: the Show More/Show Less button will not render when there are 5 or less parents
- ~Issue 1: the explore section should not render information when parent/child data does not exist.~ (moved to 332) 

**Requirements:**

- [x] Issue 2: hierarchy records in the explore section will re-render to show the correct information of a previous record. 
- [x] Issue 3: Remove button is parents.length is less than or equal to 5
- [x] ~Issue 1: any record with an explore section will not render parent/child information if it does not exist~ moved to 332

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [x] Wireframe/Mockup - Mike
- [x] Committee discussions - Sarah
- [x] Feasibility/Team discussion - Sarah
- [x] Backend requirements - TBD
- [x] Frontend requirements - Kam
- [x] Are new regression tests required for QA - Amy | yes 
- [x] Questions
- List of questions for discussions. Answers should be documented within the issue.

**UAT/LUX Examples:**
Issue 2:
- View [Tepelenë](https://lux-front-sbx.collections.yale.edu/view/place/e74ebd92-a45c-4776-9cdb-26c278e26df5)
- Select the parent entity [Gjirokastër](https://lux-front-sbx.collections.yale.edu/view/place/5e5a5634-5126-48fc-88e0-c9a9ed3693f4)
- Hit the back button in the browser
- The hierarchy rendered when going back to Tepelenë should be its own and not the hierarchy for Gjirokastër

Issue 3:
- https://lux-front-tst.collections.yale.edu/view/place/9f0772aa-e75e-490c-8f4d-5b2ccd41162a
- - Explore widget doesn't display Show More under Parents
- PRD: https://lux.collections.yale.edu/view/place/9f0772aa-e75e-490c-8f4d-5b2ccd41162a
- - - Explore widget does display Show More under Parents

~Issue 1:~
- ~https://lux-front-dev.collections.yale.edu/view/concept/684a5568-f2fc-42f6-a339-eaa1fa7635b4~ (moved to #332) 

**Dependencies/Blocks:**
N/A

**Related Github Issues:**
N/A

**Related links:**
- Bugherd: https://www.bugherd.com/projects/284041/tasks/2348
- Bugherd: https://www.bugherd.com/projects/284041/tasks/2390
- Bugherd: https://www.bugherd.com/projects/284041/tasks/2436

**Wireframe/Mockup:**
Current Issue 2: 
![image](https://github.com/user-attachments/assets/42eaa1f4-3348-4668-b1e8-1326282ee8af)
Expected Issue 2: 
![image](https://github.com/user-attachments/assets/a51fdb80-7799-4e05-a39e-36f69c94828e)

Current when there are 5 parents:
<img width="943" alt="Screenshot 2024-07-30 at 2 18 32 PM" src="https://github.com/user-attachments/assets/7ce91bf8-fc7e-4301-99c9-d880e23d7eb0">

Expected:
<img width="943" alt="Screenshot 2024-07-30 at 2 18 47 PM" src="https://github.com/user-attachments/assets/721c7c73-4331-4aa6-a93e-df5c800f65ee">

**Comment by kamerynB** [comment]
@roamye 

1. There is no parent information in the record. The frontend issue is then that it should not render the hierarchy component if there are no parents and children.
2. That looks like a rendering issue on the frontend. That hierarchy component isn't being re-rendered upon going back.

The 2 issues are unrelated, as fixing one will not impact the other. However, the second one is a simple fix. I just tested it locally and it involves changing one line of code. They can be completed in one GH issue.

**Comment by roamye** [comment]
These will need to be separated into three issues. 1 important 2/3 critical (8/7 UAT)

**Comment by kamerynB** [comment]
@roamye These issues can remain as one issue. I will tackle them together. I would mark this issue as Critical if the majority are considered critical.

**Comment by roamye** [comment]
@kamerynB - I created this ticket: https://github.com/project-lux/lux-frontend/issues/332, it tackles the first issue on 297 and includes its separate UAT.

**Comment by roamye** [comment]
2. looks good in prod. 
3. looks good in prod. 
Closing.
