### ISSUE TITLE
Estimates do not display in Simple Search when coming from Advanced Search. 

### ISSUE THREAD

**Issue by roamye** [project-lux/lux-frontend#298]
**Problem Description:**
When a user creates a simple search and goes to  Advanced Search the number of records displays correctly within its tab. 
However if you switch to/go back to simple search this number no longer displays. Instead it displays the tab name + (-). For example: `Objects (-)`

**Expected Behavior/Solution:**
When a user switches to simple search from advanced search, the estimates should reflect the advanced search estimates as the other tabs should not have results. When a user then navigates to a different tab, an information alert will display a message telling the user to perform a new simple search to search under the current tab.

**Requirements:**
- The number of records on a simple search will display its previous advanced search tab state. 
- only one tab will be populated while the others remain as (-). 

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [ ] Wireframe/Mockup - Amy 
- [ ] Committee discussions - Sarah
- [ ] Feasibility/Team discussion - Sarah
- [ ] Backend requirements - TBD
- [ ] Frontend requirements- TBD
- [ ] Are new regression tests required for QA - Amy
- [ ] Questions
- Do we want all of the tabs to populate when we go from AS-> SS? 
   - Answer| 7/16 TF:  it is difficult to populate all tabs when a user goes from an AS to SS as it does not have the information of what is included in all the records. It is best to have it revert to the last previous search tab state. 

**UAT/LUX Examples:**
*AS and AS to SS examples will have matching tab counts once deployed. 
- AS: https://lux-front-dev.collections.yale.edu/view/results/people?q=%7B%22AND%22%3A%5B%7B%22name%22%3A%22Andy+warhol%22%7D%2C%7B%22recordType%22%3A%22person%22%7D%5D%7D 
- AS to SS: https://lux-front-tst.collections.yale.edu/view/results/people?q=%7B%22AND%22%3A%5B%7B%22recordType%22%3A%22person%22%7D%2C%7B%22name%22%3A%22andy%20warhol%22%7D%5D%7D&sq= 

**Dependencies/Blocks:**

**Related Github Issues:**

**Related links:**

- Bugherd: https://www.bugherd.com/projects/284041/tasks/2352

**Wireframe/Mockup:**
Current: 
![image](https://github.com/user-attachments/assets/7323eb6a-56db-40ab-896f-565edbb841ba)

Updated: 
![image](https://github.com/user-attachments/assets/4bcc4256-3aad-4a9a-ba46-fe3ea8a0c2cb)

![image](https://github.com/user-attachments/assets/e3e13962-dcce-4ffa-acdb-154b5ccfa821)

**Comment by prowns** [comment]
Discussion from ticket forming...  Should revert to the last previous search tab state.

**Comment by jffcamp** [comment]
@kamerynB - I agree with 1 & 2. For 3 can the trip back to simple search provide a message to alert the user that x terms will be dropped because it isn't available with Simple Search?

**Comment by roamye** [comment]
@kamerynB - 

Scenario 1: 
the expected behavior is: The estimates should show the previous estimates state from the simple search.
Question - does this imply the previous estimates across all tabs or just the tab which it was previously on? (ex: displaying the previous estimate on the Object tab only) 

Scenario 2: 
I have the same question from scenario 1,  but I am assuming in scenario 2 we would only want to display the previous estimate of the tab the AS was submitted on. 

Scenario 3: 
I think this ok with an error message somewhere to indicate this will happen. 

We can continue discussing later in a meeting.

**Comment by roamye** [comment]
From Meeting 9/18: 
*behavior reflected against all test environments

When a user switches back to simple search the FE is making a new search for each tab as it recognizes it as a simple search. 
Q: We tell the user that when they switch back to simple search all the info will be lost. As a user we would hope to not see the result. 

In either scenario (2&3) should we result to its default simple search that they had before? or do we maintain what they had for their advanced search and make sure the results do not come with the error? 
-> switching to a new tab will show a new blank simple search  when switching from AS back to SS.
-> error message for going back to simple search needs to be updated. As the message is not clear as you are not losing all input.

Next Steps: 
- Expected behavior for scenarios 2 & 3 will have a blank search results screen when moving across tabs in Simple Search. (after switching simple search from as)
-

**Comment by kamerynB** [comment]
@roamye @jffcamp @prowns 

Scenarios 2 & 3 Steps and Expected Behavior:

1. Submit a simple search for "andy warhol"
3. Switch to advanced search
5. Select `Add Row`
6. Select `Dimension` from the single field dropdown
7. Select less than from the comparator dropdown
8. Add "10" to the input for `Dimension`
9. Select `Add Row`
10. Select `Anywhere` from the single field dropdown
11. Add "painting" to the input for `Anywhere`
12. Submit the advanced search
13. Switch back to the simple search
    - User should see the estimates show as the last submitted search for that given results page (in this case, Objects) and no estimates for other tabs (`(-)`)
 14. Select "Works" tab
    - The works results will not render anything as the last submitted search was an advanced search in the Objects tab and does not apply to other results tabs. See screenshot below.

<img width="1436" alt="Screenshot 2024-09-18 at 4 06 01 PM" src="https://github.com/user-attachments/assets/1ddcf535-6e0d-458b-afac-81fd1abdfc0f">

**Comment by prowns** [comment]
Looks good to me.  Will the current pop-up continue to warn users that their Adv. Search input is about to disappear?

**Comment by roamye** [comment]
@kamerynB - Might be out of scope, but to keep consistency, if the user goes back to an AS (from the blank screen) should the AS also be blank? Currently it still shows the AS query used in objects in the AS Works tab. 

Based on our previous discussion the mockup looks good. But @prowns does bring up a good point.

**Comment by jffcamp** [comment]
I am ok with this but agree that if we can add a message to the blank grey screen that would be better. If that is problematic I'm fine with that being a standalone ticket.

**Comment by roamye** [comment]
IT Team Meeting 10/4: 
- Kam to make a separate issue to tackle other issues that arose from todays meeting. ([notes here](https://docs.google.com/document/d/1RMI3f2KKUTWH5iqN3b5MMgm5vO05AKKW2wSw9KmXL28/edit))

**Comment by roamye** [comment]
Approved by UAT

**Comment by roamye** [comment]
Looks good in PROD. Closing.
