### ISSUE TITLE
Add Professional Activity Categorized As in Advanced Search

### ISSUE THREAD

**Issue by roamye** [project-lux/lux-frontend#305]
**Problem Description:**
Currently there is no single field in Advanced Search to search for `Professional Activity Categorized As`. 

**Expected Behavior/Solution:**
Create a single field and facet for "Professional Activity  Categorized As " in Advanced Search.

**Requirements:**
- Single field "professional activity categorized as" will display as an option in AS People & Groups
- Icon for AS will be a lightbulb such as Categorized As does. 
- New Help Text will be added. 

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [x] Wireframe/Mockup - Mike
- [x] Committee discussions - Sarah
- [x] Feasibility/Team discussion - Sarah
- [x] Backend requirements - TBD
- [x] Frontend requirements- TBD
- [ ] Are new regression tests required for QA - Amy
- [x] Questions
- List of questions for discussions. Answers should be documented within the issue.

**UAT/LUX Examples:**

- TST AS: https://lux-front-tst.collections.yale.edu/view/results/people?q= (more specific example TBD) 

**Dependencies/Blocks:**

- Blocked By: Issues that are blocking the completion of the current issue.
- Blocking: Issues being blocked by the completion of the current issue.

**Related Github Issues:**
- FE SS: https://github.com/project-lux/lux-frontend/issues/268
- ML AS: https://github.com/project-lux/lux-marklogic/issues/248

**Related links:**
- Bugherd: https://www.bugherd.com/projects/284041/tasks/2231

**Wireframe/Mockup:**
![image](https://github.com/user-attachments/assets/ed787cae-17e7-4f21-ad75-58dd0d672024)

**Comment by kamerynB** [comment]
@roamye This change will most likely not require a frontend change. Once the ML config is deployed this change should be visible on the frontend.

**Comment by roamye** [comment]
@kamerynB - thanks Kam. I had thought there was a FE change needed for this. Based on your comment this should be fine to close.
