### ISSUE TITLE
Update birth date and death date parsing for people and groups

### ISSUE THREAD

**Issue by kamerynB** [project-lux/lux-frontend#310]
**Problem Description:**
The dates being rendered for birth/formation date and death/dissolution date are not consistent between BCE and CE dates.

**Expected Behavior/Solution:**
The dates should be consistent for BCE vs CE dates.

**Requirements:**

- [x] Update the getDates function to be consistent when returning formatted dates.

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [x] Wireframe/Mockup - Kam
- [x] ~Committee discussions - Sarah~
- [x] ~Feasibility/Team discussion - Sarah~
- [x] ~Backend requirements - TBD~
- [x] Frontend requirements- TBD
- [ ] Are new regression tests required for QA - Amy
- [x] ~Questions~

**UAT/LUX Examples:**

- https://lux-byunit1.collections.yale.edu/view/person/74a4a95a-0ff7-4a91-876a-97c75614ef61
- PRD: https://lux.collections.yale.edu/view/person/74a4a95a-0ff7-4a91-876a-97c75614ef61

**Dependencies/Blocks:**
N/A

**Related Github Issues:**
N/A

**Related links:**

- Bugherd: https://www.bugherd.com/projects/284041/tasks/2403

**Wireframe/Mockup:**
Current:
<img width="190" alt="Screenshot 2024-07-30 at 4 41 41 PM" src="https://github.com/user-attachments/assets/4be71ba7-142d-4974-9617-1b4bb918a141">

Expected:
<img width="190" alt="Screenshot 2024-07-30 at 4 41 56 PM" src="https://github.com/user-attachments/assets/b6f7625d-a119-474f-bdfb-8338daa60786">

**Comment by prowns** [comment]
https://www.bugherd.com/projects/284041/tasks/2513 notes problems with this issue.  Discussion with @kamerynB - this example is bad data.  But, also, a suggestion to only show the BCE label, and not the CE label.

We did not recognize that this issue (on person/group record) would also affect how dates appear in results list.

**Comment by kamerynB** [comment]
@prowns Should this be a hotfix then?

**Comment by prowns** [comment]
UAT -  hotfix approved.

**Comment by kamerynB** [comment]
@prowns @jffcamp @roamye The hot fix has been deployed.

**Comment by roamye** [comment]
Looks good in PROD. Closing. 

I also checked other records like andy warhol to ensure CE is no longer included.
