### ISSUE TITLE
Add images to activities

### ISSUE THREAD

**Issue by kamerynB** [project-lux/lux-frontend#311]
**Problem Description:**
Activities have images but are not being rendered.

**Expected Behavior/Solution:**
Render the images for activities.

**Requirements:**

- [x] Add the getImages function and component to activities in the About section

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [x] Wireframe/Mockup - Kam
- [x] ~Committee discussions - Sarah~
- [x] ~Feasibility/Team discussion - Sarah~
- [x] ~Backend requirements - TBD~
- [x] Frontend requirements - Kam
- [ ] Are new regression tests required for QA - Amy
- [x] ~Questions~

**UAT/LUX Examples:**

- https://lux-front-tst.collections.yale.edu/view/activity/f7619206-f77c-4f3a-85a1-22bb091cbb1f
- PRD: https://lux.collections.yale.edu/view/activity/f7619206-f77c-4f3a-85a1-22bb091cbb1f

**Dependencies/Blocks:**
N/A

**Related Github Issues:**
N/A

**Related links:**

- Bugherd: https://www.bugherd.com/projects/284041/tasks/2433

**Wireframe/Mockup:**
Current:
<img width="468" alt="Screenshot 2024-07-30 at 4 33 40 PM" src="https://github.com/user-attachments/assets/7d5989aa-8839-4978-b61b-dc597cfee52e">

Expected:
<img width="468" alt="Screenshot 2024-07-30 at 4 36 50 PM" src="https://github.com/user-attachments/assets/e0360d7c-cde9-4937-b437-bb40ae27e219">

**Comment by roamye** [comment]
Looks good in prod. Closing.
