### ISSUE TITLE
Fix breadcrumb hierarchy rendering issues

### ISSUE THREAD

**Issue by kamerynB** [project-lux/lux-frontend#312]
**Problem Description:**
The breadcrumb hierarchy is not rendering correctly when navigating through it.

**Expected Behavior/Solution:**
The breadcrumb hierarchy should render the correct hierarchy.

**Requirements:**

- [x] Add a `key` property with the value of the current entity's id to all instances of the breadcrumb hierarchy component

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [x] Wireframe/Mockup - Kam
- [x] ~Committee discussions - Sarah~
- [x] ~Feasibility/Team discussion - Sarah~
- [x] ~Backend requirements - TBD~
- [x] Frontend requirements - Kam
- [ ] Are new regression tests required for QA - Amy
- [x] ~Questions~

**UAT/LUX Examples:**

1. Go to [Catocala](https://lux-front-tst.collections.yale.edu/view/concept/082f8b89-0ca8-425b-9f32-fdadd193e685) | [PRD Catacola](https://lux.collections.yale.edu/view/concept/082f8b89-0ca8-425b-9f32-fdadd193e685)
2. In its breadcrumb hierarchy, select [Endopterygota](https://lux-front-tst.collections.yale.edu/view/concept/6bcba4a6-c861-45fe-a76f-6f69da504587)
3. The breadcrumb hierarchy for Endopterygota should be correct

**Dependencies/Blocks:**
N/A

**Related Github Issues:**
N/A

**Related links:**

- Bugherd: https://www.bugherd.com/projects/284041/tasks/2447 & https://www.bugherd.com/projects/284041/tasks/2448

**Wireframe/Mockup:**
Current:
![Screenshot 2024-07-31 at 10 17 05 AM](https://github.com/user-attachments/assets/93dab56d-7c24-41ee-9e1d-590549eb69f3)

Expected:
![Screenshot 2024-07-31 at 10 17 26 AM](https://github.com/user-attachments/assets/4893bdf3-f765-4b47-8f97-71daaeb017a7)

**Comment by roamye** [comment]
Looks good in prod. Closing.
