### ISSUE TITLE
Change the order of the related tabs on person and group pages

### ISSUE THREAD

**Issue by kamerynB** [project-lux/lux-frontend#313]
**Problem Description:**
The "Objects in Collection" tab is second in this list of tabs, therefore it is not the first tab shown.

**Expected Behavior/Solution:**
"Object in Collection" should appear first in the tab order.

**Requirements:**

- [x] Change the order of the HAL link config

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [x] Wireframe/Mockup - Kam
- [x] ~Committee discussions - Sarah~
- [x] ~Feasibility/Team discussion - Sarah~
- [x] ~Backend requirements - TBD~
- [x] Frontend requirements - Kam
- [x] Are new regression tests required for QA - Amy | No
- [x] ~Questions~

**UAT/LUX Examples:**
- https://lux-front-dev.collections.yale.edu/view/group/41310ca5-8137-45fe-ac2c-a6a04e2235f1
- PRD: https://lux.collections.yale.edu/view/group/41310ca5-8137-45fe-ac2c-a6a04e2235f1

**Dependencies/Blocks:**
N/A

**Related Github Issues:**
N/A

**Related links:**
- Bugherd: https://www.bugherd.com/projects/284041/tasks/2449

**Wireframe/Mockup:**
Current:
<img width="962" alt="Screenshot 2024-07-30 at 4 23 22 PM" src="https://github.com/user-attachments/assets/4cafdc0a-5b5a-4037-a67e-8df6144740dd">

Expected:
<img width="962" alt="Screenshot 2024-07-30 at 4 23 48 PM" src="https://github.com/user-attachments/assets/1990dd0e-e48a-4e7d-889c-3a4916da61a1">

**Comment by roamye** [comment]
Approved by UAT 9/12

**Comment by roamye** [comment]
Looks good in PROD. Closing.
