### ISSUE TITLE
Fix the search link for timelines

### ISSUE THREAD

**Issue by kamerynB** [project-lux/lux-frontend#314]
**Problem Description:**
The search link for each year's relationship in the timeline does not total all results from specific dates within the same year.

**Expected Behavior/Solution:**
The search link total should reflect the total from all dates within that year.

**Requirements:**

- [x] Fix parsing functions that add the totals for timeline search links

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [x] Wireframe/Mockup - Kam
- [ ] ~Committee discussions - Sarah~
- [ ] ~Feasibility/Team discussion - Sarah~
- [ ] ~Backend requirements - TBD~
- [x] Frontend requirements - Kam
- [ ] Are new regression tests required for QA - Amy
- [ ] ~Questions~

**UAT/LUX Examples:**
- PRD: https://lux.collections.yale.edu/view/concept/5270cad8-a5f7-442c-bf9a-a884c4fed8a8
- https://lux-front-dev.collections.yale.edu/view/concept/5270cad8-a5f7-442c-bf9a-a884c4fed8a8

**Dependencies/Blocks:**
N/A

**Related Github Issues:**
N/A

**Related links:**

- Bugherd: https://www.bugherd.com/projects/284041/tasks/2445
- Bugherd: https://www.bugherd.com/projects/284041/tasks/2475

**Wireframe/Mockup:**
Current:
<img width="943" alt="Screenshot 2024-07-30 at 4 19 27 PM" src="https://github.com/user-attachments/assets/5e7422d2-28cb-41dd-bdb6-aa9ba5987e7b">

Expected:
<img width="943" alt="Screenshot 2024-07-30 at 4 19 42 PM" src="https://github.com/user-attachments/assets/5eb560c4-9b24-4480-a1a8-e229653faafe">

**Comment by roamye** [comment]
Looks good in PROD. Closing.
