### ISSUE TITLE
Investigate Site Improve Bugs related to Landing Page. 

### ISSUE THREAD

**Issue by roamye** [project-lux/lux-frontend#316]
**Problem Description:**
Issue [222](https://github.com/project-lux/lux-frontend/issues/222) fixed the majority of the issues listed within the ticket. 
However, the remaining issue that continues to show "Unknown Page Name". This is caused by poor state management in the frontend.

**Expected Behavior/Solution:**
The frontend will be updated to allow SiteImprove to capture all page names. "Unknown page name" should no longer appear in SiteImprove unless an error occurs.

**Requirements:**

- [x] Page names will be retrieved on page render and passed to SiteImprove accordingly
- [x] Entering the site from ANY Lux url will capture that page name once the user starts interacting with elements on the page with SI events

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [ ] ~Wireframe/Mockup - Mike~
- [ ] ~Committee discussions - Sarah~
- [ ] ~Feasibility/Team discussion - Sarah~
- [ ] ~Backend requirements - TBD~
- [x] Frontend requirements- TBD
- [ ] ~Are new regression tests required for QA - Amy~
- [ ] ~Questions~

**UAT/LUX Examples:**

- https://docs.google.com/spreadsheets/d/1INlt1C-e3lnJ6ulDb_8w7akFcz9U8WCj1jn_EBzOW8c/edit?gid=404696812#gid=404696812 

**Dependencies/Blocks:**
N/A

**Related Github Issues:**

- https://github.com/project-lux/lux-frontend/issues/222

**Related links:**
N/A

**Wireframe/Mockup:**
N/A

**Comment by kamerynB** [comment]
@roamye For the first issue, selecting the "Apply" button, I see that it works in DEV. I've included a screenshot below of both the event and subsequent events. Below are the steps I took to get there.
1. Go to landing page
2. Search "andy warhol"
3. Select the `Creation Date` facet
4. Select a range
5. Select "Apply" (this event is captured in the first screenshot
6. Select the first returned results (this event is shown in the second screenshot)

Screenshot 1:
![Screenshot 2024-08-02 at 11 47 35 AM](https://github.com/user-attachments/assets/6693548f-474b-4f2b-a10f-c5fca8ce1f5d)

Screenshot 2:
![Screenshot 2024-08-02 at 12 02 31 PM](https://github.com/user-attachments/assets/92e16a28-1c41-4ec1-9c6c-04f9129ab2fc)

**Comment by roamye** [comment]
@kamerynB - you are correct! It works now so I updated the issue since the date facet is no longer an issue.

**Comment by kamerynB** [comment]
@roamye Thank you! I will continue looking into the landing page issue though.

**Comment by roamye** [comment]
From discussion with Kam 10/2/24: 
- a new update has been deployed to DEV, which seems to solve the issue above. However this will be brought up to it team meeting 10/4 to gain a team consensus. 
- The update includes adding a path "landing" to the lux landing page for user who navigate. back to the home page

Notes: 
Landing pages to....
- hero image: works successfully
- featured collection: works successfully 
- advanced search: works successfully
- search tips: works successfully
- external links: works successfully
- help options: work successfully

As noted above, going directly to a link (non home page) and then selecting any other link will result in an "unknown page"
ex: https://lux-front-dev.collections.yale.edu/view/person/85ab18e6-b208-4658-8ea4-abaca7a60812

**Comment by roamye** [comment]
From ITS Team Meeting 10/4/24: 
The solution above is not sufficient as we also need to get the correct label for starting on a non home page link. 
Next steps: 
- add one more API to get non home page links to work.

**Comment by roamye** [comment]
Approved by UAT

**Comment by prowns** [comment]
@roamye - can this be closed?

**Comment by roamye** [comment]
@prowns yes just finished reviewing it :)
