### ISSUE TITLE
Add Gear Box to the first field of Advanced Search 

### ISSUE THREAD

**Issue by roamye** [project-lux/lux-frontend#318]
**Problem Description:**
The first line of advanced search is displayed as: 
`Have multiple field` or `Have a single field` or Have name `Name`

where a gear box is NOT present at the end of `Name`. However, once you add a name in the field and select Search Lux, the Advanced Search defaults to: 
Have All of
  - Name: [Name] | [gear box]
  
 where it includes the gear box after the name field. In both instances a search is being done, but in only one instance is the gear box present. This needs to be updated to allow gear options to be selected on the very first Name field presented. 

**Expected Behavior/Solution:**
Gear box will appear next to the very first Name field presented in Advanced Search ONCE the user has entered at least one letter into the Name search bar . 
This will allow users to set gear option preferences before searching in LUX. 

**Requirements:**
- The first name field will have the gear icon and all the gear options available upon a user entering a minimum of one character into the name field. 
- This gear feature will be available to all tabs (Objects, Events, Works, Places, People & Groups, Events, and Concepts) 

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [x] Wireframe/Mockup - Amy
- [ ] Committee discussions - Sarah
- [x] Feasibility/Team discussion - Sarah
- [ ] Backend requirements - TBD
- [ ] Frontend requirements- TBD
- [ ] ~Are new regression tests required for QA - Amy~
- [x] Questions
- List of questions for discussions. Answers should be documented within the issue.

**UAT/LUX Examples:**

- https://lux.collections.yale.edu/view/results/objects?q= (Objects) | TST: https://lux-front-tst.collections.yale.edu/view/results/objects?q=

**Dependencies/Blocks:**
N/A

**Related Github Issues:**
N/A

**Related links:**
- Bugherd: https://www.bugherd.com/projects/284041/tasks/2439

**Wireframe/Mockup:**
Current: 
![image](https://github.com/user-attachments/assets/aaf28857-b1d1-4b26-b1e1-92494a9238a6)

Updated: *This will appear for all tabs
Closed Gear
![image](https://github.com/user-attachments/assets/95bc8325-c6e6-4ced-a0bf-eec73cbf3851)
Opened Gear
![image](https://github.com/user-attachments/assets/14f4896e-13e2-44e1-984b-c405cf8f01e9)

**Comment by kamerynB** [comment]
@roamye @prowns The screenshot of what is expected is not feasible. It is only after a user has started entering a name or has selected the name field that the gear icon should be visible.

**Comment by prowns** [comment]
@roamye - can you update screenshot to show that?

**Comment by roamye** [comment]
@prowns @kamerynB - updated. 

1 Q - by a user selecting the field, do you mean when they select as below: 
![image](https://github.com/user-attachments/assets/b6ec51c1-11fb-4650-8128-10ff402ef38a)

or do you mean when they select the field from the single field options? 

If it is the first one, then we can leave the first mockup and make a note it should appear once a user selects the field to write the name in. But if it is not then I can delete the first mockup.

**Comment by kamerynB** [comment]
The following screenshots are what I was thinking. The options dropdown can not be in the field selection row. That is the view that allows users to select `Have multiple fields or Have a single field or Have Name`.

![Screenshot 2024-08-19 at 2 22 54 PM](https://github.com/user-attachments/assets/752e83ea-6dd1-4c9d-91cc-a82ca52beff6)
![Screenshot 2024-08-19 at 2 24 17 PM](https://github.com/user-attachments/assets/da2de082-9312-402b-8b44-2679b71c986d)

**Comment by roamye** [comment]
Gotcha, I deleted the original wireframe and kept the two ones I recently added.

Thanks for the clarification. I also updated the issue to reflect it should appear after a user enters a _minimum_ of one character into the first name field. 

@kamerynB

**Comment by roamye** [comment]
Approved by UAT 9/27

**Comment by roamye** [comment]
Looks good in PROD. Closing
