### ISSUE TITLE
Add sort by artist/creator name on Objects and Works (from 1737)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-frontend#32]
**Problem Description:**
Users want to be able to sort results by the names of related resources. For example, sorting objects by the name of the person/group that created them (e.g. sort by artist name).  LUX does not allow this. 

NOTE: Per triage - very high dev costs/time

**Expected Behavior/Solution:**
Provide this functionality to users. 

**Requirements:**
Analysis / Discussion needed as to which relationships between which records should be sortable. 

Dependency on: https://github.com/project-lux/lux-marklogic/issues/10

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.
- [x] description of problem
- [ ] description of expected behavior
- [ ] requirements
- [ ] UAT examples
- [ ] Wireframe/Mockup - Heather
- [ ] Committee discussions - Sarah
- [ ] Feasibility/Team discussion - Sarah
- [ ] Backend requirements - TBD
- [ ] Frontend requirements- TBD
- [ ] Questions

**Dependencies/Blocks:**

Dependent on: 
- https://github.com/project-lux/lux-marklogic/issues/10 
- https://github.com/project-lux/lux-frontend/issues/80 (tbd)

**UAT/LUX Examples:**
- https://lux-front-tst.collections.yale.edu/view/results/objects?q=%7B%22AND%22%3A%5B%7B%22text%22%3A%22spreading%22%2C%22_lang%22%3A%22en%22%7D%2C%7B%22text%22%3A%22canvas%22%2C%22_lang%22%3A%22en%22%7D%5D%7D&sq=spreading+canvas (sort toggle) 

**Related links:**
- https://www.bugherd.com/projects/284041/tasks/1130
- https://www.bugherd.com/projects/284041/tasks/2438
- https://github.com/project-lux/lux-frontend/issues/80

**Wireframe/Mockup:**
Place wireframe/mockup for the proposed solution at end of ticket.

**Comment by roamye** [comment]
@jffcamp - I marked this as critical as the dependent issue is listed as critical. Although, I am unaware if this went through the UAT process or if there was a note somewhere that this passed the UAT before moving it into critical. I am going to move this back to forming for now as there is no UAT links I did see from the old ticket it was in the future status, unsure if it should go back there.  (https://git.yale.edu/lux-its/lux-web/issues/1737) 

cc: @prowns

**Comment by jffcamp** [comment]
@roamye @prowns - didn't we discuss this at UX/BA meeting and decide that we would prefer the investigate searching for facet values? #348

**Comment by azaroth42** [comment]
`critical` and `minor` ... uhhuh?

**Comment by roamye** [comment]
closing as this is already mentioned in the semantic fe ticket #80
