### ISSUE TITLE
Combine Works Created with Works Published on Place records. 

### ISSUE THREAD

**Issue by roamye** [project-lux/lux-frontend#320]
**Problem Description:**
Applicable place records have separate tabs for Works Published and Works Created. This is inconsistence with people & group records as they have Works Published/Created listed into one tab. People & Group records do this to minimize the amount of tabs listed within the record. Place records should do the same to free up space for future tabs. 

**Expected Behavior/Solution:**
- Combine search results from Works Published At and Works Created At into one Tab labeled as "Works Published or Created At". 

**Requirements:**
- Place records will have one tab labeled as "Works Published or Created At"
- The new tab will contain the combination of search results for Works Publish At and Works Created At. 

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [x] Wireframe/Mockup - Amy
- [ ] Committee discussions - Sarah
- [x] Feasibility/Team discussion - Sarah
- [ ] Backend requirements - TBD
- [ ] Frontend requirements- TBD
- [x] Are new regression tests required for QA - Amy | yes
- [ ] Questions
- List of questions for discussions. Answers should be documented within the issue.

**UAT/LUX Examples:**
- https://lux-data-dev.collections.yale.edu/view/place/c7723bdd-598e-458f-8e1c-4ee6b17e6c22

**Dependencies/Blocks:**

- Blocked By: Issues that are blocking the completion of the current issue.
- Blocking: Issues being blocked by the completion of the current issue.

**Related Github Issues:**

- Issues that contain similar work but are not blocking or being blocked by the current issue.

**Related links:**
- Bugherd: https://www.bugherd.com/projects/284041/tasks/2426

**Wireframe/Mockup:**
Current: 
![image](https://github.com/user-attachments/assets/5883284c-cf0c-4ae3-a8a6-2536a82f1a9b)

Updated: 
![image](https://github.com/user-attachments/assets/330bf77b-a087-4d68-8ff1-c19afad5a985)

**Comment by roamye** [comment]
@kamerynB - Added it to the Agenda topics for tmmrs meeting. 

cc: @prowns

**Comment by kamerynB** [comment]
@roamye Thank you! It shouldn't be a long discussion.

**Comment by jffcamp** [comment]
Close, won't 'fix'
