### ISSUE TITLE
Fix featured collections image links

### ISSUE THREAD

**Issue by kamerynB** [project-lux/lux-frontend#322]
**Problem Description:**
The featured collections links are displaying above their corresponding images.

**Expected Behavior/Solution:**
The links should not be visible.

**Requirements:**

- [x] Remove the `name` property from the link

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [x] Wireframe/Mockup - Kam
- [x] ~Committee discussions - Sarah~
- [x] ~Feasibility/Team discussion - Sarah~
- [x] ~Backend requirements - TBD~
- [x] Frontend requirements - Kam
- [x] ~Are new regression tests required for QA - Amy~
- [x] ~Questions~

**UAT/LUX Examples:**

- https://lux-front-dev.collections.yale.edu/

**Dependencies/Blocks:**
N/A

**Related Github Issues:**
N/A

**Related links:**

- Bugherd: https://www.bugherd.com/projects/284041/tasks/2474

**Wireframe/Mockup:**
Current:
<img width="1433" alt="Screenshot 2024-08-02 at 2 32 54 PM" src="https://github.com/user-attachments/assets/67fc4151-6c57-4df6-97e6-2ea1a7ca8625">

Expected:
<img width="1433" alt="Screenshot 2024-08-02 at 2 33 41 PM" src="https://github.com/user-attachments/assets/61e0c0e2-7000-452d-a4aa-ba4b50f84a76">

**Comment by roamye** [comment]
Approved by UAT 8/7

**Comment by roamye** [comment]
Looks good in PROD. Closing.
