### ISSUE TITLE
Add support for lux-byunit2 Bugherd

### ISSUE THREAD

**Issue by kamerynB** [project-lux/lux-frontend#327]
**Problem Description:**
The current Bugherd configuration for all envs goes to the same Bugherd board.

**Expected Behavior/Solution:**
The lux-byunit2 env should have its own Bugherd configuration that is not connected to the other envs.

**Requirements:**

- [x] Add support for the lux-byunit2 Bugherd key if the baseUrl matches

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [x] ~Wireframe/Mockup - Mike~
- [x] ~Committee discussions - Sarah~
- [x] ~Feasibility/Team discussion - Sarah~
- [x] ~Backend requirements - TBD~
- [x] Frontend requirements - Kam
- [x] ~Are new regression tests required for QA - Amy~
- [x] ~Questions~

**UAT/LUX Examples:**

- https://lux-byunit2.collections.yale.edu/

**Dependencies/Blocks:**
N/A

**Related Github Issues:**
N/A

**Related links:**
N/A

**Wireframe/Mockup:**
N/A

**Comment by roamye** [comment]
Closing, BH is now available on the by unit.
