### ISSUE TITLE
Fix search estimates requests

### ISSUE THREAD

**Issue by kamerynB** [project-lux/lux-frontend#337]
**Problem Description:**
The frontend fails to retrieve search estimates when the search string contains an ampersand.

**Expected Behavior/Solution:**
The frontend should show estimates when using special characters.

**Requirements:**

- [x] The getSearchEstimates function should convert params using the javascript URLSearchParams object

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [x] Wireframe/Mockup - Kam
- [x] ~Committee discussions - Sarah~
- [x] ~Feasibility/Team discussion - Sarah~
- [x] ~Backend requirements - TBD~
- [x] Frontend requirements - Kam
- [x] ~Are new regression tests required for QA - Amy~
- [x] ~Questions~

**UAT/LUX Examples:**

- https://lux-front-tst.collections.yale.edu/view/results/objects?q=%7B%22AND%22%3A%5B%7B%22text%22%3A%22McKinsey%22%2C%22_lang%22%3A%22en%22%7D%2C%7B%22text%22%3A%22%26%22%2C%22_lang%22%3A%22en%22%7D%2C%7B%22text%22%3A%22Company%22%2C%22_lang%22%3A%22en%22%7D%5D%7D&sq=McKinsey+%26+Company

**Dependencies/Blocks:**
N/A

**Related Github Issues:**
N/A

**Related links:**

- https://www.bugherd.com/projects/284041/tasks/2153

**Wireframe/Mockup:**
Current:
![Screenshot 2024-08-12 at 2 30 01 PM](https://github.com/user-attachments/assets/e722fcd9-a475-4b2e-9bf6-a493adfc8ba6)

Expected:
![Screenshot 2024-08-12 at 2 30 08 PM](https://github.com/user-attachments/assets/849718bf-dbc5-40d8-8b49-1cc0bcd51dfb)

**Comment by roamye** [comment]
Looks good in PROD. Closing
