### ISSUE TITLE
Add related list for People Active Here (from 1745)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-frontend#34]
**Problem Description:**
The Place page does not show people or groups who were professionally active at that location.

**Expected Behavior/Solution:**
Add the missing data in an accordion with an appropriate label.

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [x] Wireframe/Mockup 
- [x] Appropriate label - Heather
- [x] ~Committee discussions~ 
- [x] Feasibility/Team discussion - Sarah
- [x] ~Check for other related tickets in forming (Where is it, how do I see it?)~
- [x] ~Connect related tickets~
- [x] Backend requirements  - HAL Link needed - Peter
- [x] Frontend requirements

**Requirements:**

- The configuration for the HAL link will be added to the frontend once the HAL link is created.

**UAT/LUX Examples:**
prod: 
https://lux.collections.yale.edu/view/place/d8c3e262-187a-40f3-843f-cf618aefde4a
test: https://lux-front-tst.collections.yale.edu/view/place/d8c3e262-187a-40f3-843f-cf618aefde4a
Adv. search: https://lux.collections.yale.edu/view/results/people?q=%7B%22activeAt%22%3A%7B%22name%22%3A%22Malibu%22%7D%7D

**Dependencies/Blocks:**

- [x] Blocked by: https://github.com/project-lux/lux-middletier/issues/19

**Related Github Issues:**
-N/A
- Old ticket: https://git.yale.edu/lux-its/lux-web/issues/1745

**Related links:**
- Bugherd: https://www.bugherd.com/projects/284041/tasks/1236

**Wireframe/Mockup:**
![image](https://github.com/project-lux/lux-frontend/assets/160149818/8c58136a-13f8-4ffb-9d78-2b7c23cd5e65)

![image](https://github.com/project-lux/lux-frontend/assets/160149818/364c8ce4-8cb0-444a-8b4b-4ceb05f7da43)

**Comment by prowns** [comment]
From UAT/Peter: This page:
https://lux-front-dev.collections.yale.edu/view/place/d8c3e262-187a-40f3-843f-cf618aefde4a

Should have an accordion item whose query (and who show all link) is based on this search:
https://lux-front-dev.collections.yale.edu/view/results/people?q=%7B%22activeAt%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fplace%2Fd8c3e262-187a-40f3-843f-cf618aefde4a%22%7D%7D

**Comment by prowns** [comment]
May need middle tier ticket.  Need to sort out if a separate ML ticket is needed.  Normally, HAL link tix should go to middle tier.

**Comment by roamye** [comment]
Per UAT this is approved.

**Comment by roamye** [comment]
Looks good in prod, closing
