### ISSUE TITLE
Remove place of publication in related locations accordion

### ISSUE THREAD

**Issue by roamye** [project-lux/lux-frontend#343]
**Problem Description:**
From BH2493, it was proposed to NOT include the relationship `Place of Publication` in the related locations accordion as it is not a good proxy for the language of the work. It will also simplify the map view for map visualization in #53. 

**Expected Behavior/Solution:**
Remove the relationship from the `related locations` accordion. 

Note: This will be brought to interactions on 08/22. 

**Requirements:**
- Remove the relationship `Place of Publication of Works` from the `Related Locations` accordion. 

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [x] Wireframe/Mockup - Mike
- [ ] Committee discussions - Sarah
- [ ] Feasibility/Team discussion - Sarah
- [ ] Backend requirements - TBD
- [ ] Frontend requirements- TBD
- [ ] Are new regression tests required for QA - Amy
- [ ] Questions
- List of questions for discussions. Answers should be documented within the issue.

**UAT/LUX Examples:**
- Related Locations TST: https://lux-front-tst.collections.yale.edu/view/concept/d067d500-e6ea-4da2-9a2d-18bcd58e21dc 

**Dependencies/Blocks:**

- Blocked By: Issues that are blocking the completion of the current issue.
- Blocking: Issues being blocked by the completion of the current issue.

**Related Github Issues:**

- ML: https://github.com/project-lux/lux-marklogic/issues/284 

**Related links:**

- Bugherd: https://www.bugherd.com/projects/284041/tasks/2493

**Wireframe/Mockup:**
Current: 
![image](https://github.com/user-attachments/assets/df9c9cc7-47dc-4772-9612-0bd042292683)

Updated: 
![image](https://github.com/user-attachments/assets/1eb39687-c9f4-4897-8850-6073d3c7daf7)

**Comment by roamye** [comment]
Does this need a MT ticket as well since it would have to update the related list? 
@kamerynB

**Comment by kamerynB** [comment]
@roamye This will require a ML ticket as the HAL link used for this relationship is not formed in the MT, but in ML. 

The HAL link search: https://lux-front-tst.collections.yale.edu/api/related-list/place?name=relatedToConcept&uri=https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fconcept%2Fd067d500-e6ea-4da2-9a2d-18bcd58e21dc

I have some questions regarding this though.
1. How does this improve our ability to create a map visualization?
2. Will it be removed from this list and added to its own accordion component? Or is it just being removed as it is no longer useful?

Maybe @azaroth42 can help with these questions I have as well.

**Comment by roamye** [comment]
@kamerynB - I created: https://github.com/project-lux/lux-marklogic/issues/284, it may have to be updated as I am not 100% sure if what I wrote in the expected behavior is correct. 

I agree that @azaroth42 would be best to answer your questions above.

**Comment by clarkepeterf** [comment]
This can all be solved via https://github.com/project-lux/lux-marklogic/issues/284 - no action is needed in the FE or MT

**Comment by roamye** [comment]
@clarkepeterf - thanks, I marked this as propose-close since no action is needed.
