### ISSUE TITLE
Add Works about a Concept onto Concept records 

### ISSUE THREAD

**Issue by roamye** [project-lux/lux-frontend#344]
**Problem Description:**
Some concept records are not displaying Work records about the Concept record. 

**Expected Behavior/Solution:**
Ensure all Work records about the Concept record display on the `Works Related`. 

**Requirements:**
- Display the relationship of Works about a Concept on Concept records.
- Have this relationship appear in the tab 'Works Related'. 

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [ ] Wireframe/Mockup - Mike
- [ ] Committee discussions - Sarah
- [ ] Feasibility/Team discussion - Sarah
- [ ] Backend requirements - TBD
- [ ] Frontend requirements- TBD
- [ ] Are new regression tests required for QA - Amy
- [ ] Questions
- List of questions for discussions. Answers should be documented within the issue.

**UAT/LUX Examples:**

- https://lux-front-dev.collections.yale.edu/view/concept/9f25dadc-c441-4122-8ffe-66175b22d568
to include: https://lux-front-dev.collections.yale.edu/view/text/e99a18e5-4024-4bf7-9fd8-dfc910ee0cb5 

**Dependencies/Blocks:**
- Blocked By: https://github.com/project-lux/lux-middletier/issues/91 which is blocked by: 
- https://github.com/project-lux/lux-marklogic/issues/282

**Related Github Issues:**

- Issues that contain similar work but are not blocking or being blocked by the current issue.

**Related links:**

- Bugherd: https://www.bugherd.com/projects/284041/tasks/2492

**Wireframe/Mockup:**
Updated (note the number in the button is inaccurate): 
![image](https://github.com/user-attachments/assets/77248e79-3cdc-4abe-bb4e-54de613bea51)

**Comment by roamye** [comment]
From discussion with @kamerynB - we have an existing issue already for this: https://github.com/project-lux/lux-frontend/issues/324. 

Propose close.

**Comment by prowns** [comment]
Also needs WORK - look at  all the YUKON tickets

**Comment by kamerynB** [comment]
@prowns This issue requires a discussion. Can it please be added to the ticket forming meeting on 8/27?

**Comment by roamye** [comment]
Added to tomorrows ticket forming meeting. @kamerynB

**Comment by roamye** [comment]
Propose-close. The example in UAT has been moved to #324 and a seperate BH has been made to investigate the issue on why the event is also appears as a concept for some works.

**Comment by roamye** [comment]
Approved by UAT 9/12 to close.
