### ISSUE TITLE
Search within facets

### ISSUE THREAD

**Issue by dcheather** [project-lux/lux-frontend#348]
**Problem Description:**
Due to long lists within facets and pagination requirements, it makes sense to implement a search within a facet. 

Note: this is a higher priority than https://github.com/project-lux/lux-frontend/issues/32

**Expected Behavior/Solution:**
A user can search within a facet and the search will auto-complete to any facet available for the current query.

**Requirements:**
List of details required for the completion of the issue or requirements for the feature/bug. This can also include requirements that lie outside of the teams such as new design docs or clarification from an outside source.

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [ ] Wireframe/Mockup - Heather
- [ ] Committee discussions - Sarah
- [ ] Feasibility/Team discussion - Sarah
- [ ] Backend requirements - TBD
- [ ] Frontend requirements- TBD
- [ ] Are new regression tests required for QA - Amy
- [ ] Questions
- List of questions for discussions. Answers should be documented within the issue.

**UAT/LUX Examples:**

- Example endpoints from LUX to use for development and testing, if applicable.

**Dependencies/Blocks:**

- Blocked By: Issues that are blocking the completion of the current issue.
- Blocking: Issues being blocked by the completion of the current issue.

**Related Github Issues:**

- Issues that contain similar work but are not blocking or being blocked by the current issue.

**Related links:**

- These links can consist of resources, bugherds, etc.

**Wireframe/Mockup:**
Place wireframe/mockup for the proposed solution at end of ticket.

**Comment by prowns** [comment]
@dcheather - per UAT discussion, this is a non-starter and we should not pursue this idea further.
