### ISSUE TITLE
Support Receiving / Sending ISO 8601 Dates from/to ML

### ISSUE THREAD

**Issue by clarkepeterf** [project-lux/lux-frontend#359]
**Problem Description:**
https://github.com/project-lux/lux-marklogic/issues/256 updates the backend to send and receive ISO 8601 Dates. The frontend needs to be updated to do the same.

**Expected Behavior/Solution:**
The frontend supports ISO 8601 dates. User interface functionality remains the same.

~~**Requirements:**~~

~~**Needed for promotion:**~~

~~- [ ] Wireframe/Mockup - Mike~~
~~- [ ] Committee discussions - Sarah~~
~~- [ ] Feasibility/Team discussion - Sarah~~
~~- [ ] Backend requirements - TBD~~
~~- [ ] Frontend requirements- TBD~~
~~- [ ] Are new regression tests required for QA - Amy~~
~~- [ ] Questions~~
~~- List of questions for discussions. Answers should be documented within the issue.~~

**UAT/LUX Examples:**

- [Searching for the following](https://lux-front-tst.collections.yale.edu/view/results/objects?q=%7B%22AND%22%3A%5B%7B%22producedDate%22%3A%22-000001%22%2C%22_comp%22%3A%22%3C%3D%22%7D%5D%7D) creates a URL containing `"producedDate"%3A"-000001"`: ![Image](https://github.com/user-attachments/assets/1d3a51ba-9c14-49b3-87cd-2dd79d50adc6) 
- After doing the above search, applying the following facet [creates a URL ](https://lux-front-tst.collections.yale.edu/view/results/objects?q=%7B%22AND%22%3A%5B%7B%22producedDate%22%3A%22-000001%22%2C%22_comp%22%3A%22%3C%3D%22%7D%5D%7D&if=%7B%22AND%22%3A%5B%7B%22producedDate%22%3A%22-007000%22%2C%22_comp%22%3A%22%3E%3D%22%7D%2C%7B%22producedDate%22%3A%22-000001%22%2C%22_comp%22%3A%22%3C%3D%22%7D%5D%7D&facetRequest=true&ip=1)which also contains `"producedDate"%3A"-007000"`: ![Image](https://github.com/user-attachments/assets/ff51ebb5-294e-43a5-b2e6-f99c601facaf) 
 

~~**Dependencies/Blocks:**~~

~~- Blocked By: Issues that are blocking the completion of the current issue.~~
~~- Blocking: Issues being blocked by the completion of the current issue.~~

**Related Github Issues:**

- https://github.com/project-lux/lux-marklogic/issues/256
~~**Related links:**~~

~~- These links can consist of resources, bugherds, etc.~~

~~**Wireframe/Mockup:**~~
~~Place wireframe/mockup for the proposed solution at end of ticket.~~

**Comment by roamye** [comment]
@clarkepeterf - should this be moved to the 09-23 milestone?

**Comment by clarkepeterf** [comment]
@roamye  this was done this release. Some frontend changes were needed related to https://github.com/project-lux/lux-marklogic/issues/256

I just updated this ticket to have an approprate description and UAT

**Comment by roamye** [comment]
@clarkepeterf - thanks Peter, if it was done in this release can the status be changed to Reviewable?

**Comment by clarkepeterf** [comment]
@roamye Yes, done

**Comment by roamye** [comment]
Approved by UAT 9/12

**Comment by roamye** [comment]
Looks good in PROD. Closing.
