### ISSUE TITLE
Allow All Search Bots 

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-frontend#360]
**Problem Description:**
Currently we only allow Google bots to crawl our contents - per https://github.com/project-lux/lux-frontend/issues/24. Since it has been proven not to burden our system much, we want to open it to other search bots too. 

**Expected Behavior/Solution:**
LUX will allow all (legitimate) search bots. /view/results/ will keep being excluded from allowed paths.

**Tasks:**
- [x] Review the [recovery plan](https://yaleits.atlassian.net/wiki/spaces/DAT/pages/4237983832/Recovery+from+Backend+Crash).

**Comment by gigamorph** [comment]
https://github.com/project-lux/lux-frontend/pull/361

Deployed to non-prod envs.

**Comment by roamye** [comment]
From DEV 9/9 meeting: 
- this issue is OK to skip the UAT process.

**Comment by gigamorph** [comment]
Done.
