### ISSUE TITLE
Add access statement to Works pages

### ISSUE THREAD

**Issue by kamerynB** [project-lux/lux-frontend#364]
**Problem Description:**
Access statements are not visible on works pages.

**Expected Behavior/Solution:**
The access statement will be visible in the How Do I See It? section on works pages.

**Requirements:**

- [x] add getAccessStatement to the EntityParser and call it in the works How Do I See It section

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [x] Wireframe/Mockup - Kam
- [x] ~Committee discussions - Sarah~
- [x] ~Feasibility/Team discussion - Sarah~
- [x] ~Backend requirements - TBD~
- [x] Frontend requirements - Kam
- [x] Are new regression tests required for QA - Amy
- [x] ~Questions~

**UAT/LUX Examples:**
- https://lux-front-sbx.collections.yale.edu/view/set/00b108b8-0c40-4788-bcab-4f289d3a53e0
- PRD: https://lux.collections.yale.edu/view/set/00b108b8-0c40-4788-bcab-4f289d3a53e0

**Dependencies/Blocks:**
N/A

**Related Github Issues:**
N/A

**Related links:**

- Bugherd: https://www.bugherd.com/projects/284041/tasks/2538

**Wireframe/Mockup:**
Current:
![Screenshot 2024-09-10 at 3 36 18 PM](https://github.com/user-attachments/assets/d1cb9e8e-a672-4cf7-a138-b64d6b9f7f48)

Expected:
![Screenshot 2024-09-10 at 3 36 08 PM](https://github.com/user-attachments/assets/102fd409-59b4-4e0c-b4a6-2df3dd9d696e)

**Comment by roamye** [comment]
Looks good in prod. Closing.
