### ISSUE TITLE
Add new urls to Yale contributing records

### ISSUE THREAD

**Issue by kamerynB** [project-lux/lux-frontend#365]
**Problem Description:**
The frontend does not organize all contributing records correctly.

**Expected Behavior/Solution:**
The Contributing Records will have 2 new Yale URLs and any link with these base urls will be rendered as Yale Contributing Records.
 
**Requirements:**

- [x] add the following links to the getDataSources function
    - [x] https://data.paul-mellon-centre.ac.uk/
    - [x] https://paperbase.xyz/

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [x] Wireframe/Mockup - Kam
- [x] ~Committee discussions - Sarah~
- [x] ~Feasibility/Team discussion - Sarah~
- [x] ~Backend requirements - TBD~
- [x] Frontend requirements - Kam
- [x] Are new regression tests required for QA - Amy
- [x] ~Questions~

**UAT/LUX Examples:**

- Paul Mellon Center example: https://lux-front-sbx.collections.yale.edu/view/person/739d626e-3ba3-4386-9f78-8f5e2b37ea7a
- paperbase example: https://lux-front-sbx.collections.yale.edu/view/object/219d7f9f-45ae-4f13-a12b-bf4ce2ea90a1

**Dependencies/Blocks:**
N/A

**Related Github Issues:**
N/A

**Related links:**

- Bugherd: https://www.bugherd.com/projects/284041/tasks/2559
- Bugherd: https://www.bugherd.com/projects/284041/tasks/2560

**Wireframe/Mockup:**
Current:
![Screenshot 2024-09-10 at 4 00 49 PM](https://github.com/user-attachments/assets/4e6c2ef9-813a-4b01-8d81-9c4842c7a31f)

Expected:
![Screenshot 2024-09-10 at 4 01 41 PM](https://github.com/user-attachments/assets/78bc3729-e1f1-403c-b754-f0012ee3aeea)

**Comment by kkdavis14** [comment]
@kamerynB the two internal URI namespaces that need added:

`https://data.paul-mellon-centre.ac.uk/`

`https://paperbase.xyz/records/`

**Comment by roamye** [comment]
Approved by UAT 9/27

**Comment by roamye** [comment]
Looks good in PROD. Closing
