### ISSUE TITLE
Return 404 to endpoints that don't exist

### ISSUE THREAD

**Issue by kamerynB** [project-lux/lux-frontend#366]
**Problem Description:**
Endpoints that don't exist return a HTTP 200 code and show a blank page with just the LUX header.

**Expected Behavior/Solution:**
Endpoints that do not exist should return the standard 404 Not Found page.
 
**Requirements:**

- [x] fix routes to catch non-existing pages and return 404

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [x] Wireframe/Mockup - Kam
- [x] ~Committee discussions - Sarah~
- [x] ~Feasibility/Team discussion - Sarah~
- [x] ~Backend requirements - TBD~
- [x] Frontend requirements - Kam
- [x] Are new regression tests required for QA - Amy
- [x] ~Questions~

**UAT/LUX Examples:**

- https://lux-front-tst.collections.yale.edu/notarealpage

**Dependencies/Blocks:**
N/A

**Related Github Issues:**
N/A

**Related links:**

- Bugherd: https://www.bugherd.com/projects/284041/tasks/2590
- Bugherd: https://www.bugherd.com/projects/284041/tasks/2591 

**Wireframe/Mockup:**
Current:
![Screenshot 2024-09-10 at 4 16 59 PM](https://github.com/user-attachments/assets/1e086b5a-e918-4694-a8c9-6fbfac663aa1)

Expected:
![Screenshot 2024-09-10 at 4 15 27 PM](https://github.com/user-attachments/assets/cb6bd0d3-ef16-42f3-b8a5-364dbe71cf33)

**Comment by clarkepeterf** [comment]
The existing 404 page also says 404 on the page, but the actual status code is a 200. Can we change the status code to be 404?
![Screenshot 2024-09-30 at 10 11 13 AM](https://github.com/user-attachments/assets/8bb5311d-0de5-4c38-9e66-8a1abf817908)

**Comment by kamerynB** [comment]
@clarkepeterf Sorry, I'm not following where this is taking place. Is that how it looks currently in production or in the current PR? When I run it locally in the current branch for this issue, I see the following (screenshot below). The frontend handles that 404 code in the [ErrorPage component](https://github.com/project-lux/lux-frontend/blob/main/client/src/features/error/ErrorPage.tsx). I may be missing something though.
![Screenshot 2024-09-30 at 1 19 21 PM](https://github.com/user-attachments/assets/6f308fe1-5d4d-4933-830c-8b9714d8458e)

**Comment by clarkepeterf** [comment]
@kamerynB that is how it looks in production. You're seeing a http 304 on the frontend because my response is cached, so it is a 304 Not Modified. But if you try replacing "thisisnotreal" with something unique, the frontend will return a 200. I think the frontend should return a 404.

**Comment by kamerynB** [comment]
@clarkepeterf Ah, I see. Looking into this a bit, there are several blog and forum posts outlining how React Router doesn't/can't edit status codes. It has to be handled on a server. I've linked a few of them below. The last link outlines a possible solution with a server. We have the frontend server right now so I'm thinking the 404 pages would just be handled by the server. 

https://stackoverflow.com/questions/76129187/react-error-page-return-status-code-200-how-can-i-fix-it-and-show-404-page
https://stackoverflow.com/questions/42699690/using-reactrouter-how-send-an-actual-404-status-code-on-not-found-pages
https://github.com/react-boilerplate/react-boilerplate/issues/1409

Solution that involves adding server support:
https://stackoverflow.com/questions/54727226/react-returns-a-200-for-a-page-not-found

**Comment by roamye** [comment]
Approved by UAT

**Comment by roamye** [comment]
Looks good in PROD. Closing.
