### ISSUE TITLE
Event Date Facets Give Zero Results When Dates Are Valid (from 1768)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-frontend#37]
### Problem:
At present, sometimes when searching for Events, one of the date (Start Date or End Date) facets is pre-populated with values (which should be valid). However, if I click `Apply` using those default values, I get 0 results. I would like the default values to return results.

### Fix (technical info):

ML is being updated to only offer a single eventDate facet, rather than an initiated (start) date and completed (end) date. Frontend needs to update to use this new facet.

### ML Background:

Currently ML offers an eventInitiatedDate and eventCompletedDate each with it's own time range.

eventIntiated = `begin_of_the_begin` - `end_of_the_begin` in the data
eventCompleted = `begin_of_the_end` - `end_of_the_end` in the data

However many events only offer `begin_of_the_begin` and `end_of_the_end`. So, we can only reliably offer one single `eventDate`, which uses `begin_of_the_begin` and `end_of_the_end` as its endpoints.

Dependent on: https://git.yale.edu/lux-its/marklogic/issues/1032 (old tix) 
- https://github.com/project-lux/lux-marklogic/issues/37 (new tix) 

Links:
- https://www.bugherd.com/projects/284041/tasks/1698
- https://www.bugherd.com/projects/284041/tasks/1616
- https://www.bugherd.com/projects/284041/tasks/2324

**Comment by jffcamp** [comment]
Need to fix the index first so that it has only the single dates 
Then update the queries to use the single dates

**Comment by clarkepeterf** [comment]
Not sure if any FE changes will be needed. But yes this is linked to https://github.com/project-lux/lux-marklogic/issues/37 - bugherds should also be listed in that ticket

**Comment by roamye** [comment]
propose close label was added during ITS TEAM Meeting 8/23.

**Comment by roamye** [comment]
Approved by UAT 9/12 to close.
