### ISSUE TITLE
Fix rendering of entity page headers

### ISSUE THREAD

**Issue by kamerynB** [project-lux/lux-frontend#374]
**Problem Description:**
In some cases, the entity headers hit an error boundary due to a React error.

**Expected Behavior/Solution:**
The headers should render without React errors when navigating from entity page to entity page.

**Requirements:**

- [ ] Update the rendering of the AgentData component

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [x] Wireframe/Mockup - Kam
- [x] ~Committee discussions - Sarah~
- [x] ~Feasibility/Team discussion - Sarah~
- [x] ~Backend requirements - TBD~
- [x] Frontend requirements - Kam
- [ ] Are new regression tests required for QA - Amy
- [x] ~Questions~

**UAT/LUX Examples:**

1. Go to [Color line](https://lux-front-tst.collections.yale.edu/view/text/893b77b0-fe88-4c8b-b317-2994e946eac5)
2. Select [The North American review. V. 132 / edited by Allen Thorndike Rice](https://lux-front-tst.collections.yale.edu/view/text/531129a0-9c10-42d1-80bb-045c3133b075)
Expected: the header with the title of the entity and its icon should render as expected

**Dependencies/Blocks:**
N/A

**Related Github Issues:**
N/A

**Related links:**

- Bugherd: https://www.bugherd.com/projects/284041/tasks/2555

**Wireframe/Mockup:**
Current:
![Screenshot 2024-09-18 at 10 50 51 AM](https://github.com/user-attachments/assets/54d69465-f5a8-451a-b63c-ecd618587b6e)

Expected:
![Screenshot 2024-09-18 at 10 50 58 AM](https://github.com/user-attachments/assets/ea4280d6-f039-47f6-bda4-db0e2e08b9e0)

**Comment by roamye** [comment]
Approved by UAT

**Comment by roamye** [comment]
Looks good in PROD. Closing.
