### ISSUE TITLE
Fix rendering of snippet data when records can't be retrieved

### ISSUE THREAD

**Issue by kamerynB** [project-lux/lux-frontend#375]
**Problem Description:**
Rendering of results snippet data is skewed in PRD when one of the API requests for data points returns an error. The label will not align with its data point.

**Expected Behavior/Solution:**
The data point and its label should always align.

**Requirements:**

- [ ] Wrap each row in a react bootstrap Row and Col component to ensure alignment
    - [ ] This change will be added to all snippets

For Kam's reference:
![Screenshot 2024-09-18 at 11 06 44 AM](https://github.com/user-attachments/assets/4c5d30fc-1c7e-45e5-b7e7-005caf0d0d37)

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [x] Wireframe/Mockup - Kam
- [x] ~Committee discussions - Sarah~
- [x] ~Feasibility/Team discussion - Sarah~
- [x] ~Backend requirements - TBD~
- [x] Frontend requirements - Kam
- [ ] Are new regression tests required for QA - Amy
- [x] ~Questions~

**UAT/LUX Examples:**

- See the `Darmon, Paule` result in the results found [here](https://lux.collections.yale.edu/view/results/people?q=%7B%22AND%22%3A%5B%7B%22startAt%22%3A%7B%22partOf%22%3A%7B%22name%22%3A%22morocco%22%7D%7D%7D%2C%7B%22nationality%22%3A%7B%22name%22%3A%22french%22%7D%7D%5D%7D) 
- TST: https://lux-front-tst.collections.yale.edu/view/results/people?q=%7B%22AND%22%3A%5B%7B%22startAt%22%3A%7B%22partOf%22%3A%7B%22name%22%3A%22morocco%22%7D%7D%7D%2C%7B%22nationality%22%3A%7B%22name%22%3A%22french%22%7D%7D%5D%7D

**Dependencies/Blocks:**
N/A

**Related Github Issues:**
N/A

**Related links:**

- Bugherd: https://www.bugherd.com/projects/284041/tasks/2597

**Wireframe/Mockup:**
Current:
![Screenshot 2024-09-18 at 11 22 45 AM](https://github.com/user-attachments/assets/24d2d46c-bfd6-447e-807d-ddf3d395cd9e)

Expected:
![Screenshot 2024-09-18 at 11 06 25 AM](https://github.com/user-attachments/assets/44bb920f-3af8-4b5c-8c46-957c62327b56)

**Comment by roamye** [comment]
Approved by UAT

**Comment by roamye** [comment]
Looks good in PROD. Closing.
