### ISSUE TITLE
Review Results card data and labels (from 1771)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-frontend#38]
**Problem Description:**
Review the rendering of results entries when there's statements, roles, multiple places and people. How much detail do we expect in the card, vs the full record. Bears further thought and conversations with units.  

On results card labels, when the information is too long it follows with "..." rather than listing the full details of the record. This can be shown by the UAT examples below. However this only seems to happen with the Collection of an object. (Example below where this does not happen for Work Types on a Work) 

**Expected Behavior/Solution:**
TBD - 

**Requirements:**
TBD

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [ ] Wireframe/Mockup - Mike
- [ ] Committee discussions - Sarah
- [ ] Feasibility/Team discussion - Sarah
- [ ] Backend requirements - TBD
- [ ] Frontend requirements- TBD
- [ ] Research analysis 
- [ ] Questions
- Would we want it to show a certain number of applicable information or keep it as "..." to indicate that there is further information in the records?  
- Should we have People & Groups/other tab results reflect information on their cards? and if so what information? Should we have type/nationality/member of (people and groups)? Right now there is nothing: [example of People and Groups](https://lux-front-dev.collections.yale.edu/view/results/people?q=%7B%22AND%22%3A%5B%7B%22name%22%3A%22spanish%22%7D%5D%7D&ap=1&facetRequest=true&af=%7B%22AND%22%3A%5B%7B%22classification%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux-front-dev.collections.yale.edu%2Fdata%2Fconcept%2Fe70961d4-f6fe-4680-86f6-4922141430c5%22%7D%7D%5D%7D) , [example of concepts(should type be shown?)](https://lux-front-dev.collections.yale.edu/view/results/concepts?q=%7B%22text%22%3A%22colors%22%2C%22_lang%22%3A%22en%22%7D&sq=colors&pp=1&facetRequest=true&pf=%7B%22AND%22%3A%5B%7B%22partOf%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux-front-dev.collections.yale.edu%2Fdata%2Fplace%2F1d8ab58d-78cf-4601-8611-87b3e231df59%22%7D%7D%5D%7D&cp=1&cf=%7B%22AND%22%3A%5B%7B%22classification%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux-front-dev.collections.yale.edu%2Fdata%2Fconcept%2F9c7860cf-eddb-490c-a464-cf30b1cc54d4%22%7D%7D%5D%7D)
- 

**UAT/LUX Examples:**
Objects - [Portrait of Lynette Yiadom-Boakye](https://lux.collections.yale.edu/view/results/objects/?q=%7B%22AND%22%3A%5B%7B%22text%22%3A%22Portrait%22%2C%22_lang%22%3A%22en%22%7D%2C%7B%22text%22%3A%22of%22%2C%22_lang%22%3A%22en%22%7D%2C%7B%22text%22%3A%22Lynette%22%2C%22_lang%22%3A%22en%22%7D%2C%7B%22text%22%3A%22Yiadom-Boakye%22%2C%22_lang%22%3A%22en%22%7D%5D%7D&sq=+Portrait+of+Lynette+Yiadom-Boakye) : 
![image](https://github.com/project-lux/lux-frontend/assets/160149818/8e6f90a5-372a-414b-902f-dae087afe04e)

Record of  [Portrait of Lynette Yiadom-Boakye](https://lux-front-tst.collections.yale.edu/view/object/4a3d1b7d-9657-46dc-8363-18866dc4a6ed)
![image](https://github.com/project-lux/lux-frontend/assets/160149818/d54e4cc0-59c2-47fb-8cf0-f2ce4ecbbec6)

Possible to look more like the Work Types in a Work: 
[Lacaton & Vassal : espacio libre, transformación, habiter = Lacaton & Vassal : free space, transformation, habiter](https://lux-front-dev.collections.yale.edu/view/text/5944d826-5259-4b63-96f4-0641a70cc76d)
Results card of [Lacaton & Vassal](https://lux-front-dev.collections.yale.edu/view/results/works?q=%7B%22AND%22%3A%5B%7B%22language%22%3A%7B%22AND%22%3A%5B%7B%22name%22%3A%22spanish%22%7D%5D%7D%7D%5D%7D&wp=1&wf=%7B%22AND%22%3A%5B%7B%22classification%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux-front-dev.collections.yale.edu%2Fdata%2Fconcept%2F63662486-bb41-4daa-90c5-1d8b7a53a08d%22%7D%7D%2C%7B%22classification%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux-front-dev.collections.yale.edu%2Fdata%2Fconcept%2F4a172143-a50e-4d91-a88b-a9931bceecf1%22%7D%7D%2C%7B%22classification%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux-front-dev.collections.yale.edu%2Fdata%2Fconcept%2F7fca20bc-dd7a-468d-9a8b-ec4e11ed3998%22%7D%7D%2C%7B%22classification%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux-front-dev.collections.yale.edu%2Fdata%2Fconcept%2F8c2e1e6d-68ba-4427-b4b4-94ea1bc1cdba%22%7D%7D%5D%7D&facetRequest=true)

**Dependencies/Blocks:**

**Related Github Issues:**

**Related links:**
Bugherd: https://www.bugherd.com/projects/284041/tasks/931

**Wireframe/Mockup:**
Place wireframe/mockup for the proposed solution at end of ticket.

**Comment by prowns** [comment]
From 1771: the original ticket came about because Elijah Yeomans is 'possibly' the producer in the record view, but just 'produced_by' in the snippet.

an example for multiple collections:
https://lux.collections.yale.edu/view/object/4a3d1b7d-9657-46dc-8363-18866dc4a6ed
only YUAG shows in results snippet.

or this https://lux.collections.yale.edu/view/object/5bc81a9b-bc6f-4fcf-a9c4-125ff0d0809b
has an artist but also printers, they don't appear in snippets, should they?

there's probably other such possibilities.

**Comment by kamerynB** [comment]
@prowns Can this be added to the next ticket forming meeting?

**Comment by roamye** [comment]
closing, per uat as specific issues come up new tickets will be made.
