### ISSUE TITLE
Allow full dates to be entered in all date facets/single fields in SS/AS (from 1774)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-frontend#39]
**Problem description:**  
Encounter dates, are often full DD-MM-YYYY dates, but UI only allows users to enter YYYY dates for all date facets in Simple and Advanced Search.

**Expected behavior/Solution:** 
Provide a place for users to enter full dates.  May need discussion on how to handle dates/date ranges in ML. This will be for advanced search as well as facets on search results.

**Requirements**
- All date facets must allow users to enter mm/dd/yyy dates 
- All date single fields must allow a user to enter mm/dd/yyyy dates. 
- Search results must be within the listed mm/dd/yy date a user submits. 

**Needed for promotion:**

- [x] requirements/inventory of all places where this functionality is needed (heather) 
- [x] research (peter)
- [x] wireframes (heather)

**UAT/LUX Examples**
- TST SS facets: https://lux-front-dev.collections.yale.edu/view/results/objects?q=%7B%22text%22%3A%22colors%22%2C%22_lang%22%3A%22en%22%7D&sq=colors
- TST AS: https://lux-front-dev.collections.yale.edu/view/results/objects?q=%7B%22AND%22%3A%5B%7B%22text%22%3A%22colors%22%2C%22_lang%22%3A%22en%22%7D%2C%7B%22encounteredDate%22%3A%221900%22%2C%22_comp%22%3A%22%3E%3D%22%7D%5D%7D
- https://lux-front-dev.collections.yale.edu/view/results/objects?objectsAq=%7B%22encounteredDate%22%3A%221976%22%2C%22_comp%22%3A%22%3D%22%7D&objectsSort=itemEncounteredDate%3Aasc (from original tix, unsure if needed) 

**Dependencies/Blocks:**

- Blocked By: Issues that are blocking the completion of the current issue.
- Blocking: Issues being blocked by the completion of the current issue.

**Related Github Issues:**

**Related links:**

- Bugherd: https://www.bugherd.com/projects/284041/tasks/1214

**Wireframes/Mockups**
Facet:
![Screenshot 2024-08-14 at 10 56 58 AM](https://github.com/user-attachments/assets/4f5b1b72-f6ad-43be-a886-90540b6da6ff)

Updated Advanced Search: 
![Image](https://github.com/user-attachments/assets/93c791f8-d7db-4c97-9ea2-c0c059c4eee2)

~priority set at normal by LUX core team~

**Comment by kamerynB** [comment]
Notes 6/13:
This is going to take some work. 
1. This should be done for all date facets.
2. A normal date input type will not work for this as it does not support B.C. dates.
3. The date slider operates on a percentage based on the years chosen, which are currently number types. Changing them to either string or date types will require more refactoring.

Tagging @prowns @roamye so you both are aware this is being worked on.

**Comment by roamye** [comment]
@kamerynB I have re-scoped it to include this change for all date facets. 

Would it help to have this as a META ticket? we can then create sub tix for the work needed to make this change for all date facets. 

Let me know what works best for you.

**Comment by kamerynB** [comment]
@roamye Once I figure out how best to tackle this, then I'll be able to decide whether the ticket should be split. Thank you though!

**Comment by kamerynB** [comment]
@prowns Can this be an agenda topic this week? I have some issues with possible solutions but I'd like to go over them with the team.

**Comment by kamerynB** [comment]
Per the 7/19 meeting:

**Advanced search**
The advanced search dates will include the date input type along with an option for selecting `CE` or `BCE`. The frontend will then add a negative to the date if it is a BCE date.

Below is an example of the layout.
![Screenshot 2024-07-19 at 10 39 39 AM](https://github.com/user-attachments/assets/7676c87e-c151-42c9-93f6-59812dd3b363)

**Date Facets**
The frontend will offer input as the date input type, similar to the advanced search. The option for selecting `CE` or `BCE` will be conditional and based on the dates returned.

Examples of layout will be added to the issue shortly. It was suggested that the earliest date input and latest date input are on their own lines.

**Comment by kamerynB** [comment]
Old wireframes:
<img width="866" alt="image" src="https://github.com/project-lux/lux-frontend/assets/160149818/556e129d-4b0e-48ca-bac1-b447774d7844">

<img width="377" alt="image" src="https://github.com/project-lux/lux-frontend/assets/160149818/a9fb1121-9209-43da-8111-b9f50ec25bd0">

**Comment by kamerynB** [comment]
@prowns @jffcamp @roamye Please review the updated wireframes I've added to the `Wireframes` section of the top comment. Let me know if this is something I can move forward with.

**Comment by roamye** [comment]
@kamerynB - 
From UAT 7/22, 
The mockups were approved and it is fine to move forward with.

**Comment by roamye** [comment]
From Ticket Forming July 30: 
Note to self  (@roamye ) --- 
- There is a bugherd: https://www.bugherd.com/projects/284041/tasks/2453, which may be linked to this issue. When this issue is deployed in TST/PROD. Please review the BH to ensure it is fixed. If it is not a new BH issue will need to be made.

**Comment by kamerynB** [comment]
Discussed ML changes with Peter and a path forward has been cleared. The ML decision can be found [here](https://github.com/project-lux/lux-marklogic/issues/256#issuecomment-2271438841). 

The frontend will process the epoch times, which are in seconds, by converting them to a Javascript date object such as `new Date(epoch * 1000)`. It will use the epoch time to set the date range slider. It will be converted to the `yyyy-mm-dd` format for use by the HTML date input. The same date format will be submitted to ML.

**Comment by clarkepeterf** [comment]
This is supported by ML. ML's date format has been changed to the following:
> Marklogic will continue to return dates in string format. Full ISO String for years [-9999:9999]. Just the year outside of that range.

**Comment by kamerynB** [comment]
Per the 8/23/24 meeting:

Issue:

- Usability: Supporting dinosaur dates can impact frontend usability if we were to not allow users the enter the month and day if the year is less than -9999 or greater than 9999. The slider functionality would be impacted as it would be using epoch times for full dates, not years. 
- HTML Date Input: It does not accept negative dates.
- Date Formatting: Which format to use when submitting the search?

Solutions:

- Usability: The greatest range that is currently in ML is -9999 to 9999. Dinosaur dates will never be accurate down to the day and month and they may never use the `timespan`  property. It is feasible to support dates within the current ML range.
- HTML Date Input: The date input/picker will not be used. The wireframe will be updated to allow users to enter the month as a dropdown, the day as a number, and the year as a number. 
- Date Formatting: The frontend will receive ISO strings from ML and will pass ISO strings to ML upon a faceted search submit.

cc: @clarkepeterf @kkdavis14

**Comment by kamerynB** [comment]
Old Wireframes:
<img width="340" alt="Screenshot 2024-07-19 at 3 16 04 PM" src="https://github.com/user-attachments/assets/4eecbd2f-1373-4042-be17-e6b7a177a729">

**Comment by kamerynB** [comment]
@prowns @jffcamp @roamye @clarkepeterf @kkdavis14 @dcheather Now that we have clarification on what the frontend should present to users, please confirm that the requirements listed below are clear and I can proceed with continuing working on this issue.

Requirements for facets:
1. A user will be allowed to enter a full date for facets.
2. There will be 2 input groups, `earliest` and `latest`.
3. There will be 3 input fields for both `earliest` date and `latest` date.
4. A user can enter the month by selecting from the dropdown Month field.
5. The default month will be based on the month returned from the ML date.
6. A user can enter the day by entering a number.
7. The default day will be based on the day returned from the ML date.
8. The day input will be configured to only offer the appropriate number of days for the selected month.
9. If a user selects `January` then enters the day `31`, and then switches to a month that does not have 31 days, the day input field will be reset to 1.
10. A user can enter a year by entering a number.
11. The default year will be based on the year returned from the ML date.
12. The maximum date allowed for `earliest` is the value of `latest`
13. The minimum date allowed for `earliest` is the earliest date returned from ML.
14. The maximum date allowed for `latest` is the latest date returned from ML.
15. The minimum date allowed for `latest` is the value of `earliest`.
16. The date slider will allow users to select the earliest and latest fields.
17. The date slider will be implemented using epoch time.
18. The frontend will parse ISO string formatted dates from ML.
19. The frontend will send facet requests in the ISO string format. 

Requirements for Advanced Search:
1. A user will be allowed to enter a full date in the advanced search date fields.
2. There will be 3 input fields for the date field selected.
3. A user can enter the month by selecting from the dropdown Month field.
5. The default month will be January.
6. A user can enter the day by entering a number.
7. The default day will be 1.
8. The day input will be configured to only offer the appropriate number of days for the selected month.
9. If a user selects `January` then enters the day `31`, and then switches to a month that does not have 31 days, the day input field will be reset to 1.
10. A user can enter a year by entering a number.
11. The default year will be the current year.
12. Negative years will represent BCE dates.
13. All three fields will be required.
14. The frontend will submit ISO string formatted dates to ML.
15. The frontend will parse ISO string formatted dates when displaying the advanced search after it has been submitted.

**Comment by roamye** [comment]
Comments to Kams question can be found in this teams thread: https://teams.microsoft.com/l/message/19:351e0281aaa144d0812b960d216958c6@thread.tacv2/1724442322814?tenantId=dd8cbebb-2139-4df8-b411-4e3e87abeb5c&groupId=4620eac6-0955-4c69-93e8-b493b21f0df6&parentMessageId=1724442322814&teamName=ML%2F%20Cultural%20Heritage%20Support&channelName=1%20-%20LUX_ML&createdTime=1724442322814

**Comment by roamye** [comment]
@kamerynB - the reqs look good to me. I also like the mockup. Also - the month/year will also have this as well, yes ? 
![image](https://github.com/user-attachments/assets/ff20e89a-cf85-400f-98cc-0900b16a8acb)

**Comment by roamye** [comment]
Some feedback from testing it in DEV: 
1. when you select the created date (objects) and let it default to its fields it will not update the results when selecting "Search Lux". You would have to change one of the date fields for this button to work OR change the date field and change it back to its default for it to work. It is a problem for those that want to do a search with its default date fields. 
2. If I look for objects that have the text "colors" listed anywhere within the record AND add the created date field to less than jan 1 2024, no records appear. if I do after jan 1 2024 no records appear. I also checked the json of each record before adding the field and cannot find a time stamp for any dates. Possibly the reason why it does not work? (https://lux-front-dev.collections.yale.edu/view/results/objects?q=%7B%22AND%22%3A%5B%7B%22text%22%3A%22colors%22%2C%22_lang%22%3A%22en%22%7D%2C%7B%22producedDate%22%3A%222024-01-01T00%3A00%3A00.000Z%22%2C%22_comp%22%3A%22%3C%22%7D%5D%7D) 
3. The selection of single fields has a functionality which closes the drop down after selecting a value. The new date fields do not do this. Is this something we can update so it matches the functionality of the other AS fields? (Ex: if I select the month feb, the drop down does not close and remains open until I re-click on the button. BUT if I select greater than it will close the drop down) 
4. I get an error of "field not defined": https://lux-front-dev.collections.yale.edu/view/results/works?q=%7B%22AND%22%3A%5B%7B%22text%22%3A%22andy+warhol%22%7D%2C%7B%22publishedDate%22%3A%222024-01-01T00%3A00%3A00.000Z%22%2C%22_comp%22%3A%22%3C%22%7D%5D%7D . This also happens in People & Groups and events. 

I have also made this comment on the teams thread [here.](https://teams.microsoft.com/l/message/19:351e0281aaa144d0812b960d216958c6@thread.tacv2/1725043619356?tenantId=dd8cbebb-2139-4df8-b411-4e3e87abeb5c&groupId=4620eac6-0955-4c69-93e8-b493b21f0df6&parentMessageId=1724961793315&teamName=ML%2F%20Cultural%20Heritage%20Support&channelName=1%20-%20LUX_ML&createdTime=1725043619356)

**Comment by roamye** [comment]
Old AS mockup: 
![Screenshot 2024-07-19 at 10 39 39 AM](https://github.com/user-attachments/assets/7676c87e-c151-42c9-93f6-59812dd3b363)

I have updated the issue above to contain the new mockup (what it currently looks like in DEV)

**Comment by roamye** [comment]
FYI; @kamerynB - depending on the progress this may have to be pushed to the 09/23 milestone. Let me know.

**Comment by clarkepeterf** [comment]
My feedback, first couple of things have been discussed in Teams:

1. We need to decide how BCE dates are represented to users. Does year -1 represent 1 BCE? Or does year 0 represent 1 BCE ?
    - regardless of how it is represented on the frontend, MarkLogic is using ISO 8601 dates, where year 0000 represents 1BCE, year -000001 represents 2BCE, etc.
2. 1 BCE should be a leap year. This is more easily represented by ISO years such that year 0 can be a leap year, and other years divisible by 4 are leap years. (Excluding years divisible by 100, including years divisible by 400). If using -1 to represent 1 BCE on the frontend, it's probably easier to calculate leap years by converting to ISO 8601 first (negativeYear +1) and then calculate leap years based on ISO.
3. Entering Valid dates - Currently If I choose Jan 31 as a date, I can change the month to Feb and have Feb 31. Something on the frontend should prevent this.

**Comment by roamye** [comment]
Unsure if this has to do with different date issue(s), but: 

Issue 1 - Error Message: 
1. submit a [simple search](https://lux-front-dev.collections.yale.edu/view/results/objects?q=%7B%22text%22%3A%22colors%22%2C%22_lang%22%3A%22en%22%7D&sq=colors) for colors 
2. change the earliest date to jan 1 2020 and the latest date to jan 1 2021.
3. go back to creation date and type in 2021 for the latest date. (notice the error message below) 
![Image](https://github.com/user-attachments/assets/3ffbe967-2955-45d6-ac00-0e20f170f342)


Issue 2 - Incorrect Search Results:
1. submit a [simple search](https://lux-front-dev.collections.yale.edu/view/results/objects?q=%7B%22text%22%3A%22colors%22%2C%22_lang%22%3A%22en%22%7D&sq=colors) for colors 
2. change the earliest date to jan 1 2020 and the latest date to dec 31 2021.
4. Notice the creation dates does not match those in the selected filters. (which I believe is an already known issue and is tackled within a different issue) 
5. Notice the records displayed does not show the original intended creation dates, but instead what is listed in the accordion (2020 to 2020) 
Example: https://lux-front-dev.collections.yale.edu/view/object/2f46cbb3-25ef-4d88-a728-01bf4e4c75ef has an end of end of: 2021-12-31 and begin of: 2020-01-1. This should show when I do the earliest date of jan 1 2020 and latest date of dec 31 2021 BUT only shows if the latest date is jan 1 2022. 
Example of results that do show: https://lux-front-dev.collections.yale.edu/view/object/b42fed2a-059d-46cd-afa1-741830b67e61 which only contain end_of_the_end and begin_of_the_begin of 2020-12-31 and 2020-01-1.

Issue 3 - Slide Bar extends further than expected. 
1. submit a [simple search](https://lux-front-dev.collections.yale.edu/view/results/objects?q=%7B%22text%22%3A%22colors%22%2C%22_lang%22%3A%22en%22%7D&sq=colors) for colors 
2. change the earliest date to jan 1 2020 and the latest date to dec 31 2021. Click Apply.
3. change the latest date to june 1 2021. 
4. Notice the slide bar extends. 

![Image](https://github.com/user-attachments/assets/957c2a4e-f219-4821-9d50-ea39be0d54c2)


Issue 4 - Drop downs do not close after a selection. 
1. submit a [simple search](https://lux-front-dev.collections.yale.edu/view/results/objects?q=%7B%22text%22%3A%22colors%22%2C%22_lang%22%3A%22en%22%7D&sq=colors) for colors
2. change the earliest date to May 1 -9999. 
3. Notice the drop down for month remains open. 
4. the same happens when changing the day.

**Comment by roamye** [comment]
AS: 

Issue 1 - Text for `year`  is cut off on the desktop view for all dates across tabs
1. https://lux-front-dev.collections.yale.edu/view/results/objects?q=
2. select  `Created Date`

Issue 2 - Outputs results greater than the current date. (might be a different date issue) 
1. https://lux-front-dev.collections.yale.edu/view/results/objects?q=
2. select  `Created Date`
3. change options to greater than | may | 3 | 2028 
4. click apply

Issue 3 - Outputs results from simple search are not equivalent to its simple search. (unsure if this is to be expected) 
1. [Advanced Search](https://lux-front-dev.collections.yale.edu/view/results/objects?q=%7B%22AND%22%3A%5B%7B%22producedDate%22%3A%222020-01-01T00%3A00%3A00.000Z%22%2C%22_comp%22%3A%22%3E%22%7D%2C%7B%22producedDate%22%3A%222021-12-31T00%3A00%3A00.000Z%22%2C%22_comp%22%3A%22%3C%22%7D%2C%7B%22text%22%3A%22colors%22%7D%5D%7D) vs [Simple Search](https://lux-front-dev.collections.yale.edu/view/results/objects?q=%7B%22text%22%3A%22colors%22%2C%22_lang%22%3A%22en%22%7D&sq=colors&if=%7B%22AND%22%3A%5B%7B%22producedDate%22%3A%222020-01-01T00%3A00%3A00.000Z%22%2C%22_comp%22%3A%22%3E%3D%22%7D%2C%7B%22producedDate%22%3A%222021-12-31T00%3A00%3A00.000Z%22%2C%22_comp%22%3A%22%3C%3D%22%7D%5D%7D&facetRequest=true&ip=1)

Issue 4 - same as simple search issue 4 (see above comment)

**Comment by kamerynB** [comment]
In response to [this comment](https://github.com/project-lux/lux-frontend/issues/39#issuecomment-2369051795):

Issue 1:
This is expected for that search. The [results returned for that facet request](https://lux-front-dev.collections.yale.edu/api/facets/item?q=%7B%22AND%22%3A%5B%7B%22text%22%3A%22colors%22%2C%22_lang%22%3A%22en%22%7D%2C%7B%22AND%22%3A%5B%7B%22producedDate%22%3A%222020-01-01T00%3A00%3A00.000Z%22%2C%22_comp%22%3A%22%3E%3D%22%7D%2C%7B%22producedDate%22%3A%222021-01-01T00%3A00%3A00.000Z%22%2C%22_comp%22%3A%22%3C%3D%22%7D%5D%7D%5D%7D&name=itemProductionDate&sort=asc&page=1) only return `2020-01-01T00:00:00.000Z` as a date. The frontend renders the date range based on what is returned in ML. Here is the [same search but in PRD](https://lux.collections.yale.edu/api/facets/item?q=%7B%22AND%22%3A%5B%7B%22text%22%3A%22colors%22%2C%22_lang%22%3A%22en%22%7D%2C%7B%22AND%22%3A%5B%7B%22producedDate%22%3A%222020%22%2C%22_comp%22%3A%22%3E%3D%22%7D%2C%7B%22producedDate%22%3A%222021%22%2C%22_comp%22%3A%22%3C%3D%22%7D%5D%7D%5D%7D&name=itemProductionDate&sort=asc&page=1) and only with years, not full dates.

Right now, we are using `>` and `<` comparators and not `>=` and `<=`. This may be having an impact as well.

Issue 2:
Same as issue 1 and probably has to do with the comparators as they are not inclusive.

Issue 3:
(Sigh) I thought I figured out how to fix that. I'll take a deeper dive into that.

Issue 4:
It's something to do with the function I'm using. It overwrites the default React Bootstrap behavior. I can fix that.

Issue 5:
I think I messed up the day change function so I will fix that.

**Comment by roamye** [comment]
From IT Meeting 9/27: 
- Issue 5 would be a hot fix priority. Further discussion will be had at UAT 9/27.

**Comment by roamye** [comment]
SS Issues: 
1. Error message still appears. 
2. Still an issue but unsure if this can be resolved through the FE or if something else is needed. 
3. Slide bar still extends. 
4. Days works fine, but month continues to have this issue. 
5. Works well :) | Selected filters now show the exact date ranges, rather than the years. Refine objects appears, and results still show. No error message! **BUTTT this is not working for Events -> Start Date**. ( [link](https://lux-front-dev.collections.yale.edu/view/results/events?q=%7B%22text%22%3A%22dog%22%2C%22_lang%22%3A%22en%22%7D&sq=dog&ef=%7B%22AND%22%3A%5B%7B%22startDate%22%3A%221414-11-09T00%3A00%3A00.000Z%22%2C%22_comp%22%3A%22%3E%3D%22%7D%2C%7B%22startDate%22%3A%222015-09-25T00%3A00%3A00.000Z%22%2C%22_comp%22%3A%22%3C%3D%22%7D%5D%7D&facetRequest=true&ep=1) -> select start date -> earliest date nov 9 1414 -> apply ) 

AS Issues: 
1. Works well. 
2. N/A as data issue
3. N/A was an error with my search. 
4. Same as above. Days work fine but months continue to have an issue. 

@kamerynB

**Comment by kamerynB** [comment]
@roamye I only fixed what was mentioned in [this comment](https://github.com/project-lux/lux-frontend/issues/39#issuecomment-2379527496).

**Comment by roamye** [comment]
Looks good in PROD. Closing. 

New tickets will have to be made to combat the remaining issues.
