### ISSUE TITLE
Add wikidata images parsing and universal viewer to objects pages

### ISSUE THREAD

**Issue by kamerynB** [project-lux/lux-frontend#390]
**Problem Description:**
The frontend does not display wikidata images on object pages.

**Expected Behavior/Solution:**
The frontend should display wikidata images within the universal viewer in the same manner as works pages.

**Requirements:**

- [x] Add wikidata image parsing function to object pages

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [x] Wireframe/Mockup - Kam
- [x] ~Committee discussions - Sarah~
- [x] ~Feasibility/Team discussion - Sarah~
- [x] ~Backend requirements - TBD~
- [x] Frontend requirements - Kam
- [ ] Are new regression tests required for QA - Amy
- [x] ~Questions~

**UAT/LUX Examples:**
- [Search results for Fragments of heads](https://lux-front-tst.collections.yale.edu/view/results/objects?q=%7B%22AND%22%3A%5B%7B%22text%22%3A%22fragments%22%2C%22_lang%22%3A%22en%22%7D%2C%7B%22text%22%3A%22of%22%2C%22_lang%22%3A%22en%22%7D%2C%7B%22text%22%3A%22heads%22%2C%22_lang%22%3A%22en%22%7D%5D%7D&sq=fragments+of+heads)
- https://lux-front-tst.collections.yale.edu/view/object/3864b788-c695-4dd9-bdf7-587538ef7ccd (record) 

**Dependencies/Blocks:**
N/A

**Related Github Issues:**
N/A

**Related links:**

- Bugherd: https://www.bugherd.com/projects/284041/tasks/2586

**Wireframe/Mockup:**
Current:
![Screenshot 2024-10-07 at 12 11 28 PM](https://github.com/user-attachments/assets/3ff161f8-065d-466c-b392-e239ef7db3d5)

Expected:
![Screenshot 2024-10-07 at 12 12 27 PM](https://github.com/user-attachments/assets/9b55443a-dec8-42c9-8cf9-a08a1bd3a4c9)

**Comment by roamye** [comment]
Approved by UAT

**Comment by roamye** [comment]
looks good in prod. closing.
