### ISSUE TITLE
Events: Expose Related Object Type Accordion (from 376)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-frontend#4]
Problem description: for any event show a related list of Types of Objects that are part of the event set.

Expected behavior: expose an accordion for Object Type as a related list. Should look/behave like other related list accordions

Exhibitions:
 - Object Types = Types of  Objects used in the set for this Event

Periods:
 - Object Types = Types of Objects that carry a Work that is about Concepts influenced by this Event

Needed:

- [x] Facet HAL Link - backend ticket - Peter
- [x] Wireframe - Heather
- [x] Examples/Links

**Blocked by**
[ ][ HAL Links: Object Types In Events (from 118) #13](https://github.com/project-lux/lux-middletier/issues/13)
[Old HAL Link ticket - 118](https://git.yale.edu/lux-its/lux-backend/issues/118)

Wireframe example exhibit: https://lux-front-dev.collections.yale.edu/view/activity/6e09857c-6b08-4155-a3b9-c7055d688d92
![image](https://github.com/project-lux/lux-frontend/assets/118475196/dbe667bf-8699-4f9c-b963-eddcaa9eb3c7)

Wireframe example period: https://lux-front-dev.collections.yale.edu/view/activity/4a97be41-41fc-48a1-a218-32795b534277
![image](https://github.com/project-lux/lux-frontend/assets/118475196/645b2450-be90-4575-9f6d-b231bb80512a)

Related: #1884 (important)

Links:

event - https://lux-front-dev.collections.yale.edu/view/activity/6e09857c-6b08-4155-a3b9-c7055d688d92
period - https://lux-front-dev.collections.yale.edu/view/activity/4a97be41-41fc-48a1-a218-32795b534277

**Comment by ar2674** [comment]
Approved per UAT

**Comment by prowns** [comment]
deployed
