### ISSUE TITLE
Improve/expand use of item type icons (from 1776)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-frontend#40]
**Problem Description:**
There is a disconnect between item type (eg. sound recording) and icon (book/textual work). Can we start using more icons? If this object type is sound, isn't there an audio icon that could be applied?   This expansion should probably happen on Work Types rather than Object Types.

**Expected Behavior/Solution:**
Use the most relevant icon for each object/work type. The mapping from classification to icons is here:
https://docs.google.com/spreadsheets/d/1gsVcsR-_b1kPbGi-Xz7w_GUJ8BHvmOjFW28ZZ9JGt6Y/edit#gid=0

**Requirements:**
- Icons will match their item type correctly(ex: records of books will contain the book icon, objects will contain object icon and so on) 

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [x] updated list of icons
- [x] Analyze number of object types in the data/generate list (Peter, Kelly) - not all, but analyzed the top classifications
- [x] creating an ordered system solution for icons (peter and kelly) 
- [x] Decision about mapping/effort 
- [x] icon/data mapping
- [x] Review new icons with Heather
- clothing
- newspaper/periodical
- photographs
- furniture
- [x] Request new icons from POW - Heather
- [ ] ~~UI design that accommodates multiple icons - Heather~~
- [x] requirements for calling the correct icon (Kam, Peter, Rob)
- [x] Data constants/ML  https://github.com/project-lux/lux-marklogic/issues/59
- [x] examples for UAT testing
- [x] Wireframe/Mockup - Mike
- [x] Committee discussions - Sarah
- [x] Feasibility/Team discussion - Sarah
~~- [ ] Backend requirements - TBD~~
~~- [ ] Frontend requirements- TBD~~
- [x] Questions
- What to do when there are multiple types/icons?
  - only show one, based a given priority 
- Should there be more specific icons for YPM specimens (e.g, plant specimens)
  - no 
- What new icons are needed?
  - see icons below
- Who needs to review/sign off on icons?
  - icons below are approved   

**UAT/LUX Examples:**
<img width="330" alt="image" src="https://github.com/project-lux/lux-frontend/assets/160149818/d3ef83d5-c913-4341-b60b-e567934ac557)">

Priority: 

1. [Scores and Notation](https://lux-front-tst.collections.yale.edu/view/results/objects?q=%7B%22text%22%3A%22video%22%2C%22_lang%22%3A%22en%22%7D&sq=video&ip=1&if=%7B%22AND%22%3A%5B%7B%22hasDigitalImage%22%3A0%7D%2C%7B%22classification%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux-front-tst.collections.yale.edu%2Fdata%2Fconcept%2F553abb46-340c-46b0-9a19-aa9eb912db78%22%7D%7D%5D%7D&facetRequest=true)
2. [Photographs](https://lux-front-tst.collections.yale.edu/view/results/objects?q=%7B%22text%22%3A%22robe%22%2C%22_lang%22%3A%22en%22%7D&sq=robe&ip=1&if=%7B%22AND%22%3A%5B%7B%22classification%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux-front-tst.collections.yale.edu%2Fdata%2Fconcept%2Fd9a18306-8983-4bef-b15d-aca7641b818c%22%7D%7D%5D%7D&facetRequest=true)
3. [Furniture](https://lux-front-tst.collections.yale.edu/view/results/objects?q=%7B"text"%3A"robe"%2C"_lang"%3A"en"%7D&sq=robe&ip=1&if=%7B"AND"%3A%5B%7B"classification"%3A%7B"id"%3A"https%3A%2F%2Flux-front-tst.collections.yale.edu%2Fdata%2Fconcept%2Ff2f3bfa3-97e2-46d6-a01c-55969e08991e"%7D%7D%5D%7D&facetRequest=true)
4. [Journals & Newspapers](https://lux-front-tst.collections.yale.edu/view/results/objects?q=%7B%22AND%22%3A%5B%7B%22text%22%3A%22washington%22%2C%22_lang%22%3A%22en%22%7D%2C%7B%22text%22%3A%22post%22%2C%22_lang%22%3A%22en%22%7D%5D%7D&sq=washington+post&ip=1&if=%7B%22AND%22%3A%5B%7B%22classification%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux-front-tst.collections.yale.edu%2Fdata%2Fconcept%2F5ef5aa2a-669c-449e-8a32-5582c5f96514%22%7D%7D%5D%7D&facetRequest=true)
5.  [Clothing](https://lux-front-tst.collections.yale.edu/view/results/objects?q=%7B%22text%22%3A%22garment%22%2C%22_lang%22%3A%22en%22%7D&sq=garment&ip=1&if=%7B%22AND%22%3A%5B%7B%22hasDigitalImage%22%3A0%7D%2C%7B%22memberOf%22%3A%7B%22curatedBy%22%3A%7B%22OR%22%3A%5B%7B%22memberOf%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux-front-tst.collections.yale.edu%2Fdata%2Fgroup%2F41310ca5-8137-45fe-ac2c-a6a04e2235f1%22%7D%7D%2C%7B%22id%22%3A%22https%3A%2F%2Flux-front-tst.collections.yale.edu%2Fdata%2Fgroup%2F41310ca5-8137-45fe-ac2c-a6a04e2235f1%22%7D%5D%7D%7D%7D%5D%7D&facetRequest=true)
6. [Numismatics](https://lux-front-tst.collections.yale.edu/view/results/objects?q=%7B%22text%22%3A%22coin%22%2C%22_lang%22%3A%22en%22%7D&sq=coin&ip=1&if=%7B%22AND%22%3A%5B%7B%22hasDigitalImage%22%3A0%7D%2C%7B%22classification%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux-front-tst.collections.yale.edu%2Fdata%2Fconcept%2F7d74b40b-467d-45c0-876a-9a7a66b2b457%22%7D%7D%5D%7D&facetRequest=true)
7.  [Cartography](https://lux-front-tst.collections.yale.edu/view/results/objects/?q=%7B%22text%22%3A%22map%22%2C%22_lang%22%3A%22en%22%7D&sq=map&ip=1&if=%7B%22AND%22%3A%5B%7B%22classification%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux-front-tst.collections.yale.edu%2Fdata%2Fconcept%2F6e901924-9ff3-4056-a1ce-71dce5424b33%22%7D%7D%5D%7D&facetRequest=true)
8. [Video](https://lux-front-tst.collections.yale.edu/view/results/objects?q=%7B%22text%22%3A%22video%22%2C%22_lang%22%3A%22en%22%7D&sq=video&ip=1&if=%7B%22AND%22%3A%5B%7B%22hasDigitalImage%22%3A0%7D%2C%7B%22classification%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux-front-tst.collections.yale.edu%2Fdata%2Fconcept%2Facf2cace-57e0-4237-b9f9-6b6b5dc4c51c%22%7D%7D%5D%7D&facetRequest=true)
9. [Audio](https://lux-front-tst.collections.yale.edu/view/results/objects?q=%7B%22text%22%3A%22box%22%2C%22_lang%22%3A%22en%22%7D&sq=box&ip=1&if=%7B%22AND%22%3A%5B%7B%22hasDigitalImage%22%3A0%7D%2C%7B%22classification%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux-front-tst.collections.yale.edu%2Fdata%2Fconcept%2F912de2b2-e751-4d25-9290-7e67a45ec34c%22%7D%7D%5D%7D&facetRequest=true)
10.  [Software & Electronic Media](https://lux-front-tst.collections.yale.edu/view/results/objects?q=%7B%22AND%22%3A%5B%7B%22text%22%3A%22software%22%2C%22_lang%22%3A%22en%22%7D%2C%7B%22text%22%3A%22electronic%22%2C%22_lang%22%3A%22en%22%7D%2C%7B%22text%22%3A%22media%22%2C%22_lang%22%3A%22en%22%7D%5D%7D&sq=software+and+electronic+media&ip=1&if=%7B%22AND%22%3A%5B%7B%22classification%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux-front-tst.collections.yale.edu%2Fdata%2Fconcept%2F9eae32b4-1c3f-4323-84b1-e58ac8007a62%22%7D%7D%2C%7B%22hasDigitalImage%22%3A0%7D%5D%7D&facetRequest=true)
11. [Visual Works](https://lux-front-tst.collections.yale.edu/view/results/works?q=%7B%22text%22%3A%22o%27keeffe%22%2C%22_lang%22%3A%22en%22%7D&sq=o%27keeffe&ip=1&if=%7B%22AND%22%3A%5B%7B%22classification%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux-front-tst.collections.yale.edu%2Fdata%2Fconcept%2Ff205dced-45a6-46d4-a4c5-efec14705c55%22%7D%7D%5D%7D&facetRequest=true&wp=1&wf=%7B%22AND%22%3A%5B%7B%22hasDigitalImage%22%3A0%7D%2C%7B%22classification%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux-front-tst.collections.yale.edu%2Fdata%2Fconcept%2Ff205dced-45a6-46d4-a4c5-efec14705c55%22%7D%7D%5D%7D)
12. [Textual Works](https://lux-front-tst.collections.yale.edu/view/results/works?q=%7B%22text%22%3A%22o%27keeffe%22%2C%22_lang%22%3A%22en%22%7D&sq=o%27keeffe&ip=1&if=%7B%22AND%22%3A%5B%7B%22classification%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux-front-tst.collections.yale.edu%2Fdata%2Fconcept%2Ff205dced-45a6-46d4-a4c5-efec14705c55%22%7D%7D%5D%7D&facetRequest=true&wp=1&wf=%7B%22AND%22%3A%5B%7B%22hasDigitalImage%22%3A0%7D%2C%7B%22recordType%22%3A%22LinguisticObject%22%7D%5D%7D)
13. [Objects](https://lux-front-tst.collections.yale.edu/view/results/objects?q=%7B%22AND%22%3A%5B%7B%22text%22%3A%22cultural%22%2C%22_lang%22%3A%22en%22%7D%2C%7B%22text%22%3A%22artifacts%22%2C%22_lang%22%3A%22en%22%7D%5D%7D&sq=cultural+artifacts&ip=1&if=%7B%22AND%22%3A%5B%7B%22classification%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux-front-tst.collections.yale.edu%2Fdata%2Fconcept%2F8eede6bc-e29e-4bc7-a70c-dabdfbcdcf25%22%7D%7D%2C%7B%22hasDigitalImage%22%3A0%7D%5D%7D&facetRequest=true)
14. [Specimens](https://lux-front-tst.collections.yale.edu/view/results/objects?q=%7B%22AND%22%3A%5B%7B%22text%22%3A%22lawrence%22%2C%22_lang%22%3A%22en%22%7D%2C%7B%22text%22%3A%22gall%22%2C%22_lang%22%3A%22en%22%7D%5D%7D&sq=lawrence+gall&ip=1&if=%7B%22AND%22%3A%5B%7B%22classification%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux-front-tst.collections.yale.edu%2Fdata%2Fconcept%2F5f857a13-add4-4c25-ae8b-019975e75bcd%22%7D%7D%2C%7B%22hasDigitalImage%22%3A0%7D%5D%7D&facetRequest=true)
15. [Collections](https://lux-front-tst.collections.yale.edu/view/results/works?q=%7B%22text%22%3A%22o%27keeffe%22%2C%22_lang%22%3A%22en%22%7D&sq=o%27keeffe&ip=1&if=%7B%22AND%22%3A%5B%7B%22classification%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux-front-tst.collections.yale.edu%2Fdata%2Fconcept%2Ff205dced-45a6-46d4-a4c5-efec14705c55%22%7D%7D%5D%7D&facetRequest=true&wp=1&wf=%7B%22AND%22%3A%5B%7B%22hasDigitalImage%22%3A0%7D%5D%7D)

**Dependencies/Blocks:**
- Blocking: https://git.yale.edu/lux-its/lux-web/issues/1746 (closed) 
- Blocking:  https://github.com/project-lux/lux-frontend/issues/22
- Blocked by: https://github.com/project-lux/lux-marklogic/issues/55

**Related Github Issues:**

**Related links:**
- https://www.bugherd.com/projects/284041/tasks/1350
- https://lux-front-sbx.collections.yale.edu/view/object/735d8b00-b93e-48b3-8327-4eb5986a2814
- https://docs.google.com/spreadsheets/d/1gsVcsR-_b1kPbGi-Xz7w_GUJ8BHvmOjFW28ZZ9JGt6Y/edit#gid=573072421 (Most Common Object Types and Work Types) 
- https://docs.google.com/spreadsheets/d/1gsVcsR-_b1kPbGi-Xz7w_GUJ8BHvmOjFW28ZZ9JGt6Y/edit#gid=573072421 (Type Icon Association) 
- https://git.yale.edu/lux-its/lux-web/tree/main/client/src/resources/images/type (Viewing Icons in Git) 
-[ POW icon design](https://drive.google.com/file/d/1oQ0onK8tq_P9uyPuIPZ4yRnymA6nL4cv/view?usp=drive_link)

**Wireframe/Mockup:**
Place wireframe/mockup for the proposed solution at end of ticket.

Priority set by LUX core team.

**Comment by prowns** [comment]
first pass of a straight ranking of the icons:

- scores-notation: 1
- photographs: 2
- furniture: 3
- journals/newspapers: 4
- clothing: 5
- numismatics: 6
- cartography: 7
- specimen: 8
- video: 9
- audio: 10
- software-electronic-media: 11
- visual-works: 12
- textual-works: 13
- object: 14
- collections: 15

**Comment by roamye** [comment]
This ticket is no longer blocked as https://github.com/project-lux/lux-marklogic/issues/55 was closed today during [IT team meeting](https://docs.google.com/document/d/1XpuIsmff59T7jo_iT-uksfniFUexWJqNeT3iLFBrW_4/edit). 

From team meeting we will need to add AAT references.

**Comment by kkdavis14** [comment]
@prowns I hate to throw any part of this back to the design phase, but did we ever have a design for fossil, that is different from the butterfly/specimen? I can imagine YPM would like to distinguish and fossils getting a butterfly icon doesn't work that well.

**Comment by kkdavis14** [comment]
Also, I've reordered the priority list slightly and place specimen lower down. I updated the priority list in the ticket description to reflect this change.

**Comment by kkdavis14** [comment]
Kelly to create concordance of {icon type: [AAT, AAT, AAT]}

**Comment by kkdavis14** [comment]
[ObjWorksIconAATs.csv](https://github.com/project-lux/lux-frontend/files/15169730/ObjWorksIconAATs.csv)
@clarkepeterf see attached csv for icon type >> AAT(s)

**Comment by prowns** [comment]
On agenda for 5/7/24 Data WG.

**Comment by kkdavis14** [comment]
@prowns I think this can move forward without having the YPM fully classifications sorted, FYI

**Comment by prowns** [comment]
@roamye - I am moving this to prioritization.

**Comment by kamerynB** [comment]
@kkdavis14 @clarkepeterf This issue is blocked until the frontend removes data constants and implements AATs correct? It would be time consuming to update this only to change it again.

**Comment by prowns** [comment]
Yes - need list of AATs, so yes blocked until that is available.   @clarkepeterf  will add additional information here from teams messages with @kkdavis14

**Comment by clarkepeterf** [comment]
@kkdavis14 I remember discussing a while ago that some of the classifications we want to use for icons do not have AATs

- Does that mean this is not possible with AATs?
- Or is it possible to add AATs or some other constant identifier for those classifications?
- Or do any of those classifications overlap with other classifications that do have AATs?

**Comment by kkdavis14** [comment]
@clarkepeterf yeah, many YPM taxon will not have AATs and it isn't possible to add them (as the concepts don't exist in AAT). If YPM has given a GBIF, we could use that as the constant identifier, this probably covers most of the cases.

**Comment by clarkepeterf** [comment]
@kkdavis14 can we assume that there is a GBIF for the YPM taxon that do not have AATs? Do we need to confirm or do some work to ensure that is the case?

**Comment by kkdavis14** [comment]
@clarkepeterf I don't think we can assume it. I'll run a script to check the uris from the icon mapping sheet that are YPM taxon and see which have GBIF equivs and which don't. The GBIF equivs could then be added to my csv of April 30.

There's not going to be a way to ensure they have GBIF equivs--if they're not there, they probably don't exist either.

Could expand to include Wikidata if not GBIF if no AAT. What do you think?

**Comment by prowns** [comment]
Can we default to "Objects" for any YPM items that don't have a more specific designation?

**Comment by kkdavis14** [comment]
I think it does this already, yes.

**Comment by clarkepeterf** [comment]
@kkdavis14 as long as we have some sort of unique identifier that will stick with the record across datasets, it meets our requirements. Could be AAT, GBIF, wikidata, or something else. It just needs to continue to exist in the record over time

**Comment by clarkepeterf** [comment]
@kkdavis14 and the pipeline needs to be able to include that unique id in the Object/Work that references the concept.

E.g. :
```
{
    "id": "https://lux.collections.yale.edu/data/object/abcdefghijklmnopqrstuvwxyz",
    "type": "HumanMadeObject",
    "_label": "Some YPM Artifact",
    "classified_as": {
        "id": "https://lux.collections.yale.edu/data/concept/abcdefghijklmnopqrstuvwxyz",
        "type": "Type",
        "_label": "Some YPM Taxon",
        "equivalent": [
            {
                "id": "<AAT, GBIF, Wikidata, or etc.>"
            }
        ]
    }
}
```

**Comment by kkdavis14** [comment]
@clarkepeterf We only do AATs as data constants right now. Adding Wikidata or GBIF would need Rob's approval. 

just a reminder that "It just needs to continue to exist in the record over time" is reliant on the unit's changing their data. e.g. they decide it's a different GBIF or AAT, it will break our icon code. We would just have to find them and fix them if/when that happens.

**Comment by kamerynB** [comment]
@kkdavis14 @clarkepeterf Correct me if I'm wrong, but the [spreadsheet](https://docs.google.com/spreadsheets/d/1gsVcsR-_b1kPbGi-Xz7w_GUJ8BHvmOjFW28ZZ9JGt6Y/edit?gid=0) linked above is now outdated as we no longer use data constants. I will have to get each one of those entries's AATs. I believe the frontend process will be as followed:

1. For a given object or work, get the `classified_as` ids.
2. For each `classified_as/id` get the full record.
3. Check each `classified_as/id` record's `equivalent`
4. Determine the icon by finding if `equivalent` matches one of the values in the Types column of the spreadsheet.

Does this make sense as a solution?

**Comment by kkdavis14** [comment]
@kamerynB I think I did that in my April 30 comment.

**Comment by kamerynB** [comment]
@kkdavis14 Thank you! I did not read through all the comments, clearly. 😬

**Comment by kkdavis14** [comment]
@kamerynB np, if there's anything missing/that needs updated, let me know.

**Comment by clarkepeterf** [comment]
@kamerynB please don't check in the separate document, just check the `/classified_as/equivalent/id`

E.g. the snippet below from the data for [undet. Vertebrata](https://lux-front-dev.collections.yale.edu/view/object/d725d00e-a5b3-452a-b9c4-be2852b13fc0)

```
"classified_as": [
{
"id": "https://lux-front-dev.collections.yale.edu/data/concept/05a41429-8a18-4911-854e-eae804b7d46f",
"type": "Type",
"_label": "Fossils",
"equivalent": [
{
"id": "http://vocab.getty.edu/aat/300247919",
"type": "Type",
"_label": "Fossils"
}
]
},
```

**Comment by kamerynB** [comment]
@clarkepeterf Oh right!! I honestly completely forgot about that. Thank you for reminding me!

**Comment by kamerynB** [comment]
@prowns @roamye @jffcamp Can you please confirm that the change in icons will occur on the [results snippets](https://lux-front-tst.collections.yale.edu/view/results/works?q=%7B%22AND%22%3A%5B%7B%22text%22%3A%22andy%22%2C%22_lang%22%3A%22en%22%7D%2C%7B%22text%22%3A%22warhol%22%2C%22_lang%22%3A%22en%22%7D%5D%7D&sq=andy+warhol) and [entity pages](https://lux-front-tst.collections.yale.edu/view/visual/72eaa0a9-7c71-4af2-8baa-03683de11ad5), and not within the advanced search.

Here are screenshots where these icons appear on the results page and entity pages:
<img width="1055" alt="Screenshot 2024-08-20 at 4 55 56 PM" src="https://github.com/user-attachments/assets/5fe61102-d012-4fff-b33b-6c34c94ddfcd">
<img width="1439" alt="Screenshot 2024-08-20 at 4 56 09 PM" src="https://github.com/user-attachments/assets/54b36dbe-e4a5-4cd6-a61f-08a5ec794c45">

**Comment by roamye** [comment]
@kamerynB - Wanted to confirm this will occur for [advanced search result snippets,](https://lux.collections.yale.edu/view/results/objects?q=%7B%22name%22%3A%22sun%22%7D) but not necessarily the advanced search itself (single fields) , yes?

**Comment by kkdavis14** [comment]
@kamerynB That makes sense to me. The overall Class is not changing, so the icons in AS can stay the same.

**Comment by jffcamp** [comment]
@kamerynB , this change should occur for all results snippets (simple and advanced search) and entity pages, but not when constructing an Advanced Search.

**Comment by kamerynB** [comment]
> @kamerynB - Wanted to confirm this will occur for [advanced search result snippets,](https://lux.collections.yale.edu/view/results/objects?q=%7B%22name%22%3A%22sun%22%7D) but not necessarily the advanced search itself (single fields) , yes?

@roamye Results snippets are a reusable component. Anything below the search input for both advanced search and simple search are shared between the pages. That's the power of React 😃 

<img width="1439" alt="Screenshot 2024-08-21 at 2 19 59 PM" src="https://github.com/user-attachments/assets/0a515b04-c77d-4da6-99d2-238a685940c4">

**Comment by kamerynB** [comment]
@roamye @prowns As discussed in Teams, the icons for furniture, photography, journals and newspapers, and clothing are currently not available. This issue has been merged with what is available currently and will be deployed on 9/9. I'm not sure when those additional icons will be available.

**Comment by roamye** [comment]
@kamerynB - want to confirm the new icons will also be deployed as they were found on Wed. Also do you have the link where these new icons live in github?

**Comment by kamerynB** [comment]
@roamye Yes.

**Comment by roamye** [comment]
The clothing UAT needs to be re-done. I am trying to find something, but when I try: https://lux-front-tst.collections.yale.edu/view/results/objects?q=%7B%22text%22%3A%22shirt%22%2C%22_stemmed%22%3Afalse%2C%22_lang%22%3A%22en%22%7D&sq=%22shirt%22&ip=1&if=%7B%22AND%22%3A%5B%7B%22hasDigitalImage%22%3A1%7D%2C%7B%22classification%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux-front-tst.collections.yale.edu%2Fdata%2Fconcept%2Ff817ddd9-6527-45c6-8cb7-8aa734051250%22%7D%7D%5D%7D&facetRequest=true and look at the blouses/shirts the clothing icon does not appear. Maybe I am not searching correctly? @prowns

**Comment by kamerynB** [comment]
@roamye 

Clothing: The icons may not show because the frontend does not search through all of the classified_as/equivalent values before returning the classified_as value to be used to get the icon. This has been the existing functionality for some time. 

Collections: [This link](https://lux-front-tst.collections.yale.edu/view/results/works?q=%7B%22text%22%3A%22o%27keeffe%22%2C%22_lang%22%3A%22en%22%7D&sq=o%27keeffe&ip=1&if=%7B%22AND%22%3A%5B%7B%22classification%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux-front-tst.collections.yale.edu%2Fdata%2Fconcept%2Ff205dced-45a6-46d4-a4c5-efec14705c55%22%7D%7D%5D%7D&facetRequest=true&wp=1&wf=%7B%22AND%22%3A%5B%7B%22hasDigitalImage%22%3A0%7D%5D%7D) should show collections icons.

**Comment by roamye** [comment]
@kamerynB - thank you, that link for collections works! 

Clothing - in that case will it usually never show up as the clothing icon? Or are there instances which they will?

**Comment by clarkepeterf** [comment]
@roamye some items show up as clothing. It just depends on which classified_as the frontend grabs. [Here are some examples of objects that have a clothing icon](https://lux-front-tst.collections.yale.edu/view/results/objects?q=%7B%22AND%22%3A%5B%7B%22classification%22%3A%7B%22OR%22%3A%5B%7B%22identifier%22%3A%22http%3A%2F%2Fvocab.getty.edu%2Faat%2F300209263%22%7D%2C%7B%22identifier%22%3A%22http%3A%2F%2Fvocab.getty.edu%2Faat%2F300209261%22%7D%2C%7B%22identifier%22%3A%22http%3A%2F%2Fvocab.getty.edu%2Faat%2F300238962%22%7D%2C%7B%22identifier%22%3A%22http%3A%2F%2Fvocab.getty.edu%2Faat%2F300178802%22%7D%2C%7B%22identifier%22%3A%22http%3A%2F%2Fvocab.getty.edu%2Faat%2F300266810%22%7D%2C%7B%22identifier%22%3A%22http%3A%2F%2Fvocab.getty.edu%2Faat%2F300055811%22%7D%2C%7B%22identifier%22%3A%22http%3A%2F%2Fvocab.getty.edu%2Faat%2F300266639%22%7D%5D%7D%7D%5D%7D&ip=1&if=%7B%22AND%22%3A%5B%7B%22hasDigitalImage%22%3A0%7D%5D%7D&facetRequest=true)

**Comment by clarkepeterf** [comment]
@roamye @kamerynB Part of the requirements of this ticket were that if there is more than one classification, the icon shown will be based on a priority order of icon type. This is not the case in the code right now. The frontend just returns the first icon classification that it finds in the data. Do we want to leave this ticket open or make a follow up ticket to show an icon based on the priority list?

**Comment by roamye** [comment]
@kamerynB - do we have the other icon for [numinstic](https://lux-front-tst.collections.yale.edu/view/results/objects?q=%7B%22text%22%3A%22coin%22%2C%22_lang%22%3A%22en%22%7D&sq=coin&ip=1&if=%7B%22AND%22%3A%5B%7B%22hasDigitalImage%22%3A0%7D%2C%7B%22classification%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux-front-tst.collections.yale.edu%2Fdata%2Fconcept%2F7d74b40b-467d-45c0-876a-9a7a66b2b457%22%7D%7D%5D%7D&facetRequest=true)? UAT need it to match, hot fix?

**Comment by kamerynB** [comment]
@roamye That was the numismatics icon I had. Do you have the expected one? Maybe @dcheather or @prowns has it.

**Comment by roamye** [comment]
Looks good in prod. Closing.
