### ISSUE TITLE
Add priority to existing icons. 

### ISSUE THREAD

**Issue by roamye** [project-lux/lux-frontend#401]
**Problem Description:**
Icon priority was not set for new icon additions in: https://github.com/project-lux/lux-frontend/issues/40. This causes issues for records with multiple classifications as they are not prioritized correctly. 

**Expected Behavior/Solution:**
Set priority for icons to ensure records will be classified based on its hierarchy. 

**Requirements:**
- Records with multiple priorities will display the icon that has the highest priority. 
- Priority must be set as the following order below: 

1. Scores and Notation
2. Photographs
3. Furniture
4. Journals & Newspapers
5. Clothing
6. Numismatics
7. Cartography
8. Video
9. Audio
10. Software & Electronic Media
11. Visual Works
12. Textual Works
13. Objects
14. Specimens
15. Collections

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [ ] Wireframe/Mockup - Mike
- [ ] Committee discussions - Sarah
- [ ] Feasibility/Team discussion - Sarah
- [ ] Backend requirements - TBD
- [ ] Frontend requirements- TBD
- [ ] Are new regression tests required for QA - Amy
- [ ] Questions
- List of questions for discussions. Answers should be documented within the issue.

**UAT/LUX Examples:**
Should have an icon of musical notations rather than textual works: 
- https://lux-front-tst.collections.yale.edu/view/object/ab5f42b8-5a18-4581-b89f-c362db317bf2
- PRD: https://lux.collections.yale.edu/view/object/ab5f42b8-5a18-4581-b89f-c362db317bf2

**Dependencies/Blocks:**
N/A

**Related Github Issues:**
- https://github.com/project-lux/lux-frontend/issues/40

**Related links:**
- Bugherd: https://www.bugherd.com/projects/284041/tasks/2606

**Wireframe/Mockup:**
Current: 
![image](https://github.com/user-attachments/assets/f35a47fe-9602-4e2d-834d-aa70159b69c4)

Expected:
![Image](https://github.com/user-attachments/assets/f70d6bcc-1b43-49ef-bd14-52ef55b8e203)

**Comment by roamye** [comment]
@miketullo95 - can you please create a mockup that includes the [musical notation icon](https://lux-front-tst.collections.yale.edu/view/results/objects?q=%7B%22text%22%3A%22video%22%2C%22_lang%22%3A%22en%22%7D&sq=video&ip=1&if=%7B%22AND%22%3A%5B%7B%22hasDigitalImage%22%3A0%7D%2C%7B%22classification%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fconcept%2F553abb46-340c-46b0-9a19-aa9eb912db78%22%7D%7D%5D%7D&facetRequest=true) rather than the book icon currently listed in the URL under UAT example. Thank you.

**Comment by miketullo95** [comment]
@roamye wireframe uploaded, is that what was expected?

**Comment by roamye** [comment]
@miketullo95 yes, thanks!

**Comment by roamye** [comment]
Approved by UAT

**Comment by roamye** [comment]
this looks good in prod. Closng.

**Comment by roamye** [comment]
Sorry accidently closed this after lookin at it in tst.

**Comment by roamye** [comment]
Closing looks good in PROD.
