### ISSUE TITLE
Update AAT Used For Archive Sort Value

### ISSUE THREAD

**Issue by clarkepeterf** [project-lux/lux-frontend#408]
**Problem Description:**

Archive Sort Value used to be http://vocab.getty.edu/aat/300451544

New Sort Value will be http://vocab.getty.edu/aat/300456575

**Expected Behavior/Solution:**

Frontend uses new sort value http://vocab.getty.edu/aat/300456575

~~**Requirements:**~~
~~List of details required for the completion of the issue or requirements for the feature/bug. This can also include requirements that lie outside of the teams such as new design docs or clarification from an outside source.~~

~~**Needed for promotion:**~~
~~If an item on the list is not needed, it should be crossed off but not removed.~~

~~- [ ] Wireframe/Mockup - Mike~~
~~- [ ] Committee discussions - Sarah~~
~~- [ ] Feasibility/Team discussion - Sarah~~
~~- [ ] Backend requirements - TBD~~
~~- [ ] Frontend requirements- TBD~~
~~- [ ] Are new regression tests required for QA - Amy~~
~~- [ ] Questions~~
~~- List of questions for discussions. Answers should be documented within the issue.~~

**UAT/LUX Examples:**

- https://lux.collections.yale.edu/view/set/7b2c542b-5741-43d0-a4ea-cc288b279447
  - PRD items are out of order (after FHS/3/1 - 1, 10, 100)
- https://lux-front-tst.collections.yale.edu/view/set/7b2c542b-5741-43d0-a4ea-cc288b279447
  - TST items are in order (after FHS/3/1 - 1, 2, 3)

~~**Dependencies/Blocks:**~~

~~- Blocked By: Issues that are blocking the completion of the current issue.~~
~~- Blocking: Issues being blocked by the completion of the current issue.~~

**Related Github Issues:**

- https://github.com/project-lux/lux-marklogic/issues/325

~~**Related links:**~~

~~- These links can consist of resources, bugherds, etc.~~

~~**Wireframe/Mockup:**~~
~~Place wireframe/mockup for the proposed solution at end of ticket.~~

**Comment by roamye** [comment]
@kkdavis14 - is there an example for this issue? 

cc: @clarkepeterf

**Comment by clarkepeterf** [comment]
updated UAT example

**Comment by roamye** [comment]
Approved by UAT

**Comment by roamye** [comment]
looks good in prod. closing.
