### ISSUE TITLE
Show the image of the entity in the Open Graph Card (from 1781)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-frontend#41]
**Problem Description:**
Sharing LUX links uses the astrolabe image as the open graph card. It would be nice to use the actual LUX image (when available) instead.

**Expected Behavior/Solution:**
The open graph card should accurately reflect the page the user is sharing.

**Requirements:**

- [ ] install react-helmet-async
- [ ] Set open graph image, title, and url based on the current page
- [ ] Remove open graph tags and title tag from index.html in frontend-resources

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [ ] Wireframe/Mockup - Kam
- [x] ~Committee discussions - Sarah~
- [x] ~Feasibility/Team discussion - Sarah~
- [x] ~Backend requirements - TBD~
- [ ] Frontend requirements- Kam
- [x] Questions
- List of questions for discussions. Answers should be documented within the issue.
- Can this be done dynamically or not?

**UAT/LUX Examples:**

 - https://lux-front-tst.collections.yale.edu/view/person/526abc40-ef9f-4053-9520-dd34de408a8c
 - Any LUX page should work

**Dependencies/Blocks:**
N/A

**Related Github Issues:**
N/A

**Related links:**

- BugHerd:  https://www.bugherd.com/projects/284041/tasks/1624

**Wireframe/Mockup:**
Current: 
![image](https://github.com/project-lux/lux-frontend/assets/163148482/25f4b9a1-6ef5-4943-bbfe-b99aa2c6ee6a)

Updated: 
TBD

**Comment by kamerynB** [comment]
There are 2 questions to be answered:
Can React update meta tags dynamically?
Answer: Yes but I am still unsure of the feasibility within the middle tier.
Resources:
https://create-react-app.dev/docs/title-and-meta-tags/#generating-dynamic-meta-tags-on-the-server
https://blog.logrocket.com/adding-dynamic-meta-tags-react-app-without-ssr/

Is it possible to use IIIF images and wikidata images in open graph meta tags?
Answer: Possibly? I believe as long as they are being served from somewhere accessible with an image URL, then we can use them but I have not found concrete evidence that suggests this is possible. However, would there be a problem using wikidata images that require giving credit to the artist/published/the person that owns the image?

**Comment by kamerynB** [comment]
@prowns Agenda for the 3/7 meeting??

**Comment by kamerynB** [comment]
Update 3/22:
Test out adding the tags dynamically.

**Comment by kamerynB** [comment]
@prowns @jffcamp @roamye This is something that just needs to be tested in DEV. I can attempt to work on it now.

**Comment by prowns** [comment]
@kamerynB - fine to work on in DEV. Once it is defined, we can promote.

**Comment by kamerynB** [comment]
@prowns Why not just promote it then? I'd rather have it in the backlog than placed back into forming.

**Comment by roamye** [comment]
@kamerynB ---

From the UAT meeting, this is a research tix as it is unsure how this will be implemented. Putting it in forming allows you figure out a solution in DEV. After the proposed solution is added we can then put it into backlog (after reviewing again). 

If this is not a research tix, then we would need a mockup of what it is to look like + requirements + how it will be implemented  before it could go into backlog. 

cc: @prowns

**Comment by roamye** [comment]
bringing this to ticket forming 9/10 to confirm we are all on the same page. (issue being a research tix)

**Comment by clarkepeterf** [comment]
This would require using something like Helmet (outdated lib - also not sure if it is effective) or do something like server side rendering (higher server costs)

**Comment by clarkepeterf** [comment]
@kamerynB  you could also try something like the `useTitle` hook. But instead of setting document.title you would update the document.head.meta tags with og properties

**Comment by kamerynB** [comment]
@clarkepeterf I found sources that say that can't be done. Meta tags behave differently. I have to revisit this issue though.

**Comment by kamerynB** [comment]
Notes from 10/16/24:
I attempted to use the library [react-helmet-async](https://www.npmjs.com/package/react-helmet-async) but this failed because the `<meta>` tags require server side rendering in order to work.

A discussion will take place in the 10/18 team meeting to discuss the pros and cons of adding server side rendering for the frontend.

cc: @roamye @jffcamp

**Comment by jffcamp** [comment]
Propose close. Won't do.

**Comment by roamye** [comment]
approved by UAT to close.
