### ISSUE TITLE
Migrate from create-react-app to a different library

### ISSUE THREAD

**Issue by kamerynB** [project-lux/lux-frontend#412]
**Problem Description:**
Creat-react-app is deprecated and we should not be using it going forward.

**Expected Behavior/Solution:**
Migration from create-react-app to Vite should take place.

**Requirements:**

For forming:
- [x] Testing of 3 libraries
    - [Vite](https://vite.dev/) - Winner!
    - [Next.js](https://nextjs.org/)
    - [Remix](https://remix.run/)

For development:
- [ ] Update documentation to reflect change
- [ ] Migrate test suite from Jest to Vitest
- [ ] Update additional packages/dependencies

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [x] ~Wireframe/Mockup - Mike~
- [x] ~Committee discussions - Sarah~
- [x] ~Feasibility/Team discussion - Sarah~
- [x] ~Backend requirements - TBD~
- [x] Frontend requirements - Kam
- [x] ~Are new regression tests required for QA - Amy~
- [x] Questions
    - What build tool should be used? ANSWER: Vite

**UAT/LUX Examples:**
N/A

**Dependencies/Blocks:**
N/A

**Related Github Issues:**

- #2 

**Related links:**

- [Steps for migration](https://www.freecodecamp.org/news/how-to-migrate-from-create-react-app-to-vite/)

**Wireframe/Mockup:**
N/A

**Comment by kamerynB** [comment]
Notes on Vite:

Notes on Next.js:

Notes on Remix:

**Comment by roamye** [comment]
From yesterday's dev meeting 
- it was announced that VITE was the preferred library to migrate to.

**Comment by kamerynB** [comment]
Update 11/14:
The test suite still has failing tests which are most likely due to mocking issues. The project was deployed to DEV with the Vite configuration.

**Comment by roamye** [comment]
Certain links in DEV no longer show an error 404 message for pages, for example: https://lux-front-dev.collections.yale.edu/view/results/people?q=%7B%22AND%22%3A%5B%7B%22name%22%3A%22Andy+warhol%22%7D%2C%7B%22recordType%22%3A%22person%22%7D%5D%7D returns as a completely blank screen. However, there are no steps to this other than clicking the link.

**Comment by roamye** [comment]
From discussion with @kamerynB - this will be moved to the next milestone 12/02

**Comment by roamye** [comment]
Approved by UAT
