### ISSUE TITLE
Change dates in events to be consistent with other dates

### ISSUE THREAD

**Issue by kamerynB** [project-lux/lux-frontend#454]
**Problem Description:**
Dates on events pages and where events are references are not consistent with other occurrences of dates on other entity pages. Their formatting is off.

**Expected Behavior/Solution:**
Make dates rendering consistent across all entities.

**Requirements:**
- [ ] parse `timespan/being_of_the_begin_epoch` instead of `timespan/identified_by/content`

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [x] Wireframe/Mockup - Mike
- [x] Committee discussions - Sarah
- [ ] Feasibility/Team discussion - Sarah
- [ ] ~Backend requirements - TBD~
- [x] Frontend requirements- TBD
- [ ] ~Are new regression tests required for QA - Amy~
- [ ] ~Questions~
- ~List of questions for discussions. Answers should be documented within the issue.~

**UAT/LUX Examples:**
Dates in Editor and Creation of entity pages: https://lux-front-tst.collections.yale.edu/view/text/0c165928-0893-4379-b4b1-35d84550566b will display in the same format as birth/death dates on: 
- https://lux-front-tst.collections.yale.edu/view/person/939ede51-eb87-4a6a-8a92-ba5b0e4395b6

**Dependencies/Blocks:**
N/A

**Related Github Issues:**
N/A

**Related links:**
- Bugherd: https://www.bugherd.com/projects/284041/tasks/2688

**Wireframe/Mockup:**
Existing: 
![image](https://github.com/user-attachments/assets/649c7ac3-e185-4ed5-8402-84caa098c7e8)

Expected: 
![image](https://github.com/user-attachments/assets/238e31d4-a438-4815-b750-20a43702be3b)

**Comment by prowns** [comment]
Per UAT - @azaroth42 says this solution won't work.  Propose wontfix.

**Comment by roamye** [comment]
Per UAT, closing.
