### ISSUE TITLE
Fix wonky spacing in Person Page  (from 1845)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-frontend#46]
Problem Description: In this example, the lists for Formed By, Display Biography, and Descriptive Note are double space, where all other lists are single spaced.

Expected behavior: All lists contained within the about sections on Person, Group, Concept, Place, Collections (sets that are rendered as collections), and Event pages will contain extra space between each list element.

Needed:

- [X ] Confirmation by Heather

should look like (updated):

<img width="330" alt="image" src="https://github.com/project-lux/lux-frontend/assets/160149818/6beb3d8e-33d3-4faf-a8b5-1593af79eecd)">

Links:
- https://www.bugherd.com/projects/284041/tasks/1753
- https://lux-front-tst.collections.yale.edu/view/group/350ae566-3be8-4a13-afe2-35a91fa5a98e

**Comment by ar2674** [comment]
Approved per UAT

**Comment by prowns** [comment]
deployed
