### ISSUE TITLE
Add Contextual Help for "Have Name" field on Advanced Search (from 1866)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-frontend#50]
Problem Description: There is no contextual help for the recently added "Have Name" option in Advanced Search

Expected Behavior:  Field should display "Help for Name" when user ~~hovers~~/clicks to operate the same as all the other contextual help fields.

Current:
![image](https://github.com/project-lux/lux-frontend/assets/140102078/fe6f2b73-1e8e-43a9-9e90-22ce5e2530e6)

Should show this help block instead:
![image](https://github.com/project-lux/lux-frontend/assets/140102078/30266bf0-b289-43bd-864d-24ab95bbe57d)

Links:
- https://www.bugherd.com/projects/284041/tasks/1778
- https://lux-front-tst.collections.yale.edu/view/results/objects?q=

**Comment by prowns** [comment]
Per Kam - Hover action isn't possible over an input and its and accessibility issue if there is a hover on text

**Comment by prowns** [comment]
deployed
