### ISSUE TITLE
List view for timelines (from 1872)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-frontend#52]
**Problem Description:**
The current list view for timeline data is not clear and needs work. It is not clear that the years are indeed years. 

**Expected Behavior/Solution:**
The years will have B.C.E. or C.E. after them to clarify that they are years.

**Requirements:**

- [x] Add `B.C.E.` for negative years
- [x] `C.E.` for positive years

**Needed for promotion:**
- [x] Wireframe/Mockup - Kam
- [ ] ~Committee discussions - Sarah~
- [ ] ~Feasibility/Team discussion - Sarah~
- [ ] ~Backend requirements~
- [x] Frontend requirements - Kam
- [ ] ~Questions~

**UAT/LUX Examples:**

- https://lux-front-tst.collections.yale.edu/view/person/34f4eec7-7a03-49c8-b1be-976c2f6ba6ba (tst) 
- https://lux.collections.yale.edu/view/person/34f4eec7-7a03-49c8-b1be-976c2f6ba6ba (prod)
- https://lux-front-dev.collections.yale.edu/view/concept/4a172143-a50e-4d91-a88b-a9931bceecf1 (dev)
    - Note: This is the record for `Visual Works` but this UUID may change with the latest data. 
- https://lux.collections.yale.edu/view/concept/4a172143-a50e-4d91-a88b-a9931bceecf1 (prod) 

**Dependencies/Blocks:**
N/A

**Related Github Issues:**

- https://github.com/project-lux/lux-frontend/issues/15

**Related links:**

- Bugherd: https://www.bugherd.com/projects/284041/tasks/1708

**Wireframe/Mockup:**
Current:
<img width="845" alt="Screenshot 2024-03-28 at 2 19 32 PM" src="https://github.com/project-lux/lux-frontend/assets/140102078/54d129aa-d6b5-447b-85c3-b97f63d9ea16">

Expected:
<img width="845" alt="Screenshot 2024-03-28 at 2 23 42 PM" src="https://github.com/project-lux/lux-frontend/assets/140102078/294f0802-f759-40e5-9bda-2425e6a63243">

**Comment by roamye** [comment]
@kamerynB was this deployed? the prod link does not show the B.C.E or C.E after the years: https://lux.collections.yale.edu/view/person/34f4eec7-7a03-49c8-b1be-976c2f6ba6ba

Also, the dev link of: https://lux.collections.yale.edu/view/concept/4a172143-a50e-4d91-a88b-a9931bceecf1 was in the UAT examples, I think this UAT is for a different ticket (#15) , correct?
