### ISSUE TITLE
Update the advanced search date inputs and help text for date inputs (from 1878)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-frontend#54]
**Problem Description:**
The backend/Marklogic requires an update to the date search for advanced search.  With 1032, we will use range inputs for all date fields, so advanced search fields so should match the facet date entry.  Every date is a range with two dates.  

**Proposed Solution:**
The frontend advanced search components will be updated to reflect the change.  There will be no more comparators.   Help text will need to be updated.  New JSON format will need to be handled:
```
{
   "createdDate": {
      "start": "1782",
      "end": 2020
   }
}
```

"start" or "end" inside date search terms may be excluded or `null`:

(e.g.  these are also valid):
```
{
   "createdDate": {
      "start": "1782"
   }
}
```
```
{
   "createdDate": {
      "start": "1782"
      "end": null
   }
}
```

**Needed for Promotion:**

- [x] Requirements - team
- [x] Wireframes - heather
- [x] help text updates - sarah
- [x] implementation plan - Peter, Kameryn
- [x] examples for UAT - Sarah

**Blocked by:**

- [ ] [ML #1032](https://github.com/project-lux/lux-marklogic/issues/37)
- [ ] [ML #1129](https://github.com/project-lux/lux-marklogic/issues/47)

**Related Links:**
[Advanced Search Spreedsheet](https://docs.google.com/spreadsheets/d/1PPr-AS9MEKBBa0I4iEFe4GZnATrn1DMM/edit#gid=1393461789)
**Wireframe/Mockup**
![image](https://github.com/project-lux/lux-frontend/assets/160149818/6d2a5593-fec4-4fa7-8a90-a828c4d2ba42)

should have this as an option: 
![image](https://github.com/project-lux/lux-frontend/assets/163148482/f55a0d03-4c87-4daf-a52b-71d783b33baf)

**Comment by clarkepeterf** [comment]
This form of searching in ML was abandoned. Propose close.

**Comment by roamye** [comment]
Approved by UAT 9/12 to close.
