### ISSUE TITLE
Remove Has Digital Image facet from Concepts and Places (from 1881)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-frontend#55]
Problem Description: LUX shows positive results for using Has Digital Image facet on Places and Concepts, even a decision was made not to render these thumbnails, as they mostly stink.

Expected behavior:  Users will not see Has Digital Image facet on Concepts and Places.  Remove facet from UI

![image](https://github.com/project-lux/lux-frontend/assets/160149818/a9bbd001-3bd4-4184-aec6-6f12dc29be39)

Links:
- https://www.bugherd.com/projects/284041/tasks/1785
- https://www.bugherd.com/projects/284041/tasks/2033
- https://www.bugherd.com/projects/284041/tasks/1968
For testing
Removed
- https://lux-front-tst.collections.yale.edu/view/results/concepts?cp=1&facetRequest=true&q=%7B%22AND%22%3A%5B%7B%22text%22%3A%22oil%22%2C%22_lang%22%3A%22en%22%7D%2C%7B%22text%22%3A%22paint%22%2C%22_lang%22%3A%22en%22%7D%5D%7D&sq=oil+paint
Not removed (PRD)
https://lux.collections.yale.edu/view/results/concepts?cp=1&facetRequest=true&q=%7B%22AND%22%3A%5B%7B%22text%22%3A%22oil%22%2C%22_lang%22%3A%22en%22%7D%2C%7B%22text%22%3A%22paint%22%2C%22_lang%22%3A%22en%22%7D%5D%7D&sq=oil+paint

**Comment by ar2674** [comment]
Approved per UAT

**Comment by prowns** [comment]
deployed
