### ISSUE TITLE
Events: Expose Related Work Type accordion (from 1890)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-frontend#57]
Problem description: add a related list Work Types to Events

Expected behavior: expose an accordion for Work Type as a related list. Should look/behave like other related list accordions.  This may need two different HAL links to handle exhibitions AND period events

Questions

- What are related Work types in this context?  

Exhibitions:
 - Work Types = Types of Works depicted by Objects used in the set for this Event

Periods:
 - Work Types = Types of Works about Concepts influenced by this Event

Needed:

- [x] Wireframe/mock - Heather
- [x] Additional Requirements for HAL Link (if needed) - Peter, team
- [x] Facet HAL Link - backend ticket - Peter https://github.com/project-lux/lux-middletier/issues/25
- [x] Examples/Links

Related: #1884 (important)

Mock example (exhibition): https://lux-front-dev.collections.yale.edu/view/activity/6e09857c-6b08-4155-a3b9-c7055d688d92
![image](https://github.com/project-lux/lux-frontend/assets/118475196/bc0e1e9c-b008-4004-b005-812e6c1a5c9e)

Mock example (period): https://lux-front-tst.collections.yale.edu/view/activity/4a97be41-41fc-48a1-a218-32795b534277
![image](https://github.com/project-lux/lux-frontend/assets/118475196/0ac8bf8a-2ba4-41c0-83d6-53c93e54a15c)

Links:
- Period: https://lux-front-tst.collections.yale.edu/view/activity/4a97be41-41fc-48a1-a218-32795b534277
- Exhibition: https://lux-front-dev.collections.yale.edu/view/activity/6e09857c-6b08-4155-a3b9-c7055d688d92

**Comment by ar2674** [comment]
Approved per UAT

**Comment by prowns** [comment]
deployed
