### ISSUE TITLE
Review Used option in Events/Advanced Search (from 1892)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-frontend#58]
**Problem Description:**
  The menu options for "Used" do not appear to be working correctly.  A related part of this ticket is to review the contextual help statements for each of these options.

**Expected behavior:** 
TBD (should clarify each)

**Requirements:** 
Spreadsheet: https://docs.google.com/spreadsheets/d/1PPr-AS9MEKBBa0I4iEFe4GZnATrn1DMM/edit#gid=1393461789

**Needed for promotion:** 
Test and document any changes to each of these (functionality and help text) when a user selects the Used option under events in advanced search.

- [x] Name
- [x] Anywhere
- [x] Categorized As <-- cannot find working example
- [x] Contain
- [ ] Curated by <--- cannot find working example.  What is the relationship between this and the "Carried Out by" group listed on an event/exhibtion page? [example](https://lux-front-tst.collections.yale.edu/view/activity/36c39534-5908-4297-979a-194d5fd4a8b7)
- [x] ID
- [ ] Identifier <-- what would be an identifier on an event?
- [x] Member of 
- [ ] ~Used for Exhibitions~

**UAT/LUX Examples:**
- https://lux-front-tst.collections.yale.edu/view/results/events?q=&qt=objects
![image](https://github.com/user-attachments/assets/f6141d38-7be1-473f-af6e-ab3d4fe3102b)

**Dependencies/Blocks:**

- Blocked By: Issues that are blocking the completion of the current issue.
- Blocking: Issues being blocked by the completion of the current issue.

**Related Github Issues:**
- https://git.yale.edu/lux-its/lux-web/issues/1928 (META)
~Related back-end ticket: https://git.yale.edu/lux-its/marklogic/issues/1097~ (non-issue)

**Related links:**
- https://www.bugherd.com/projects/284041/tasks/1800

**Wireframe/Mockup:**
Place wireframe/mockup for the proposed solution at end of ticket.

**Comment by roamye** [comment]
@prowns from tf 7/16 - Sarah will look at this to see how to move forward.

**Comment by prowns** [comment]
@roamye - I have reviewed and left some questions at the top.  Also there are some new bugherds that tie into this ticket.

**Comment by roamye** [comment]
TF 8/27
~Carried out by should be on events for Advanced Search.~ (it is on it) 

Q: what would be an identifier on an event?
-> identifier field pulls from the equivalent section of JSON. So if it marked as equivalents then it is an identifier (AATs). To be expected. 

Q; Is there anything that needs to be turned into a FE/ML ticket? No? 
->We need an example for curated by in events. If there is an example of this we can close this ticket. 
-> there is no curated information for events instead there is carried out by information. So this is operating as expected. 


propose close.

**Comment by roamye** [comment]
Approved by UAT 9/12 to close.
