### ISSUE TITLE
Add error message to empty entity pages with no Yale objects or works (from 1896)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-frontend#59]
Problem description: We have event pages for events that did not include any objects or works from Yale holdings.  There are also People pages that should show the same message

Expected behavior: We will provide an error message which should be applied at the top for all entity pages (person, group, concept, event) if there aren't any, even if there are other boxes in the UI.

The message should be:
"Yale University does not have any objects or works directly related to this [ type of entity ]" (e.g. Place, Person, Group, Event, Concept)

For public repo & future use by others, "Yale University" should be a configurable option to allow ease of customization by other organizations.

- [x] confirm error message text - interactions
- [x] wireframe - heather

Wireframe of https://lux.collections.yale.edu/view/activity/b91bd265-8537-49e7-90a8-5adc8747666f
![image](https://github.com/project-lux/lux-frontend/assets/160149818/f35c6964-e7da-4e04-b6f0-2f6191f1db62)

Examples:
- exhibition: https://lux-front-tst.collections.yale.edu/view/activity/b91bd265-8537-49e7-90a8-5adc8747666f
- person/group: https://lux-front-tst.collections.yale.edu/view/person/e55abc1e-d095-458a-908b-0250a41b7ae7 
- places: https://lux-front-tst.collections.yale.edu/view/place/093db312-3942-4fa1-903c-2810520c512a

Recommendation/Decision from Interactions:

- Put in no Yale Objects
- Add Links to works if known
- Add Links for exhibitions to unit data  if there’s a link (eg YUAG page above)
- Units can have internal discussion about this to see if there are other approaches

For more details see [notes from 10/4 Interactions meeting](https://docs.google.com/document/d/1MWOL6yTeVsQbbWQSX8GO5tkLq5KBa7XvO8s2AAT4M_Y/edit?skip_itp2_check=true)

**Comment by kamerynB** [comment]
@prowns Is this specifically if there are no related objects/works _tabs_ or does this span across all related components such as timelines and accordions too? For example, an entity has a timeline but doesn't have related objects/works tabs. Would this message still appear? Maybe Rob can answer this too.

cc: @azaroth42

**Comment by prowns** [comment]
I believe both scenarios:

1. empty content - show message
2. no objects/works, but has other related components - show message

Scenario 2 marks this a page where users can continue exploring, but there are no directly related collection items.

**Comment by jffcamp** [comment]
The Person/Group link generates a 404. Do we have another example?

**Comment by ar2674** [comment]
Approved per UAT
