### ISSUE TITLE
Events: Expose Related Related Materials Accordion (from 400)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-frontend#6]
Problem description: for any event show a related list of Materials of objects that are part of the event set. 

Expected behavior: expose an accordion for Materials as a related list.  Should look/behave like other related list accordions

Needed:

- [x] Decision about HAL link vs faceted search
- [x] https://git.yale.edu/lux-its/lux-backend/issues/108 - Peter
- [x] Wireframe - Heather
- [x] Examples/Links

![image](https://github.com/project-lux/lux-frontend/assets/160149818/9cbf6904-dae7-4aad-be3b-b4f0d838bc18)

UAT
 - https://lux-front-dev.collections.yale.edu/view/activity/6e09857c-6b08-4155-a3b9-c7055d688d92
- Andy warhol/materials: 
- - generates a 404 https://lux-front-tst.collections.yale.edu/view/person/783e7e6f-6863-4978-8aa3-9e6cd8cd8e83 
- - this one works: https://lux-front-tst.collections.yale.edu/view/person/34f4eec7-7a03-49c8-b1be-976c2f6ba6ba

Blocked By: 
- [x] [ Create HAL Link For Events Related Materials (from 108) #10](https://github.com/project-lux/lux-middletier/issues/10)
[Old ticket - 108](https://git.yale.edu/lux-its/lux-backend/issues/108)

**Comment by ar2674** [comment]
Approved per UAT

**Comment by prowns** [comment]
deployed
