### ISSUE TITLE
Update Advanced Search Help with new examples (from 1901)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-frontend#60]
**Problem Description:**
Rescoped to align with #1942 .  The list of Advanced Search examples is limited and could be improved to show more examples of different kinds of searches.    

**Expected Behavior/Solution:**
Update https://lux.collections.yale.edu/content/advanced-search#faq-header with new content and sections for Advanced Search Help. 

**Requirements:**
LUX Advocates working on a new set of examples https://docs.google.com/document/d/13HVnnLLaB668THafWkOp4cXNKSZpWcxJIDkHU7KUnDg/edit

**Needed for promotion:**

- [x] Compile list of examples and help text - LUX Advocates + Sarah
- [x] Mockup of new content and ordering (N/A)
- [x] Confirm feasibility in Drupal - Seong
- [x] Confirm text with interactions, UAT

**UAT/LUX Examples:**
- https://lux.collections.yale.edu/content/advanced-search#faq-header

**Related links:**
- google doc: https://docs.google.com/document/d/13HVnnLLaB668THafWkOp4cXNKSZpWcxJIDkHU7KUnDg/edit

**Wireframe/Mockup:**

**Comment by roamye** [comment]
closing as this is complete.
