### ISSUE TITLE
Add link to Advanced Search Help from contextual help block (from 1942)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-frontend#65]
Problem: LUX Advocates suggested adding more examples to contextual help.   

Expected behavior: Add a link to the Advanced Search Help from the Adv. Search block.  Given the hover changes to this block, the suggestion is to create a new static block below the help text.

Needed:

- [x] Update Mock -Heather
- [N/A ] ~Updated Adv. Search examples - Sarah/Advocates~
- [N/A ] ~CMS updates~

UAT: 
New block shows in TST: https://lux-front-tst.collections.yale.edu/view/results/objects?q=
New block is missing from PRD: https://lux.collections.yale.edu/view/results/objects?q= 

**Related Links:** 
BugHerd: https://www.bugherd.com/projects/284041/tasks/2036

Wireframe:
![Screenshot 2024-02-27 at 11 39 11 AM](https://github.com/project-lux/lux-frontend/assets/140102078/d7489224-bc36-4a7a-88fa-75cb7820350d)

**Comment by kamerynB** [comment]
As part of this issue, add the sets icon for the advanced search as seen here:
https://www.bugherd.com/projects/284041/tasks/2036

**Comment by ar2674** [comment]
Approved per UAT

**Comment by prowns** [comment]
deployed
