### ISSUE TITLE
Make "search tips" link more prominent (from 1949)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-frontend#67]
Problem Description: The link for search tip is not very visible where it lives on the homepage given the light nature of the font.

Expected Behavior: Change the font weight to match the text in the Advanced Search button (1rem, weight is 400) and also add the link to the header.

UAT: Compare TST and DEV

- https://lux-front-tst.collections.yale.edu/
- https://lux.collections.yale.edu/

- [x] Mock of Search Bar and Header
![image](https://github.com/project-lux/lux-frontend/assets/160149818/4b01f1df-b416-4764-ab7f-cab93b62407f)
![image](https://github.com/project-lux/lux-frontend/assets/160149818/9a7c4546-763f-454b-8cc1-63c7807a7dca)

Current Design: 
![image](https://github.com/project-lux/lux-frontend/assets/160149818/fc347717-d0a4-4c34-8020-831115f74d95)

**Comment by ar2674** [comment]
Approved per UAT

**Comment by prowns** [comment]
deployed
