### ISSUE TITLE
Add component terms facet to concept results (from 1960)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-frontend#68]
**Problem Description:**
User's can't facet on component terms on the concept results page.

**Expected Behavior/Solution:**
Add a facet for component terms as a checklist. This work requires a ML supported facet.

**Requirements:**
- Component terms are individual facets with the names of: Influenced by Concept, Influenced by Events, Influenced by People & Groups, and Influenced by Places. 
- Functions the same as the Part Of facet. 

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [ ] ~~Committee discussions  ~~
- [x] Wireframe/Mockup
- [x] Feasibility/Team discussion
- [x] Check for other related tickets in forming
- [x] Connect related tickets
- [x] Backend requirements
- [x]  Frontend requirements

**Questions:**

**UAT/LUX Examples:**
PRD: https://lux.collections.yale.edu/view/results/concepts/?q=%7B%22AND%22%3A%5B%7B%22text%22%3A%22George%22%2C%22_lang%22%3A%22en%22%7D%2C%7B%22text%22%3A%22Washington%22%2C%22_lang%22%3A%22en%22%7D%5D%7D&sq=George+Washington

TST: https://lux-front-tst.collections.yale.edu/view/results/concepts/?q=%7B%22AND%22%3A%5B%7B%22text%22%3A%22George%22%2C%22_lang%22%3A%22en%22%7D%2C%7B%22text%22%3A%22Washington%22%2C%22_lang%22%3A%22en%22%7D%5D%7D&sq=George+Washington

**Dependencies/Blocks:**

- [x] Blocked By: https://github.com/project-lux/lux-marklogic/issues/27

**Related Github Issues:**
N/A

**Related links:**
N/A

**Wireframe/Mockup:**
![image](https://github.com/project-lux/lux-frontend/assets/163148482/d3454378-cb89-4dfe-8fea-856ff82e217f)

**Comment by kamerynB** [comment]
Update 6/14:
This issue is blocked as it requires ML configuration to be implemented. The ML issue has been prioritized for the 6/24 milestone deadline.

**Comment by clarkepeterf** [comment]
@kamerynB  per discussion in https://github.com/project-lux/lux-marklogic/issues/27 

there are 4 exisiting facets that can be used by the frontend.

The facets are called (and I'm guessing the facet labels should be called)

conceptInfluencedByAgentId (Influencing Person or Group)
conceptInfluencedByConceptId (Influencing Concept)
conceptInfluencedByEventId (Influencing Event)
conceptInfluencedByPlaceId (Influencing Place)

**Comment by clarkepeterf** [comment]
I'm removing blocked tag from this ticket

**Comment by roamye** [comment]
Approved by UAT

**Comment by roamye** [comment]
Looks good in PROD. Closing.
