### ISSUE TITLE
Events: Expose Related Subjects Accordion (from 401)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-frontend#7]
**Problem description:** 
For any event show a related list of subjects of works carried by objects that are part of the event set.

**Expected Behavior/Solution:** 
Expose an accordion for Related Subjects as a related list. Should look/behave like other related list accordions

**Requirements:** 
List of details required for the completion of the issue or requirements for the feature/bug. This can also include requirements that lie outside of the teams such as new design docs or clarification from an outside source.

**Needed for promotion:**

- [x] Facet HAL Link - backend ticket - Peter https://github.com/project-lux/lux-middletier/issues/24
- [x] Wireframe - Heather
- [x] Examples/Links

**UAT/LUX Examples:**

- https://lux-front-tst.collections.yale.edu/view/activity/6297d4d4-ea61-45b2-8c47-9a0e6298fdcc (concepts influenced)
- https://lux-front-dev.collections.yale.edu/view/activity/6e09857c-6b08-4155-a3b9-c7055d688d92 (related subjects)

**Dependencies/Blocks:** 
Dependency: https://github.com/project-lux/lux-middletier/issues/24

**Related Github Issues:**
-  https://github.com/project-lux/lux-frontend/issues/56 (important)

**Related Links:** 

**Wireframe/Mockup:** 
Wireframe Period - https://lux-front-tst.collections.yale.edu/view/results/works?q=%7B%22aboutConcept%22%3A%7B%22name%22%3A%22Ming+dynasty%2C+1368-1644%22%7D%7D&qt=works
![image](https://github.com/project-lux/lux-frontend/assets/118475196/0b577ad9-aa7a-4174-924c-d030689d460f)

Example search period: https://lux-front-tst.collections.yale.edu/view/results/concepts?q=%7B%22influencedByEvent%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Factivity%2F6297d4d4-ea61-45b2-8c47-9a0e6298fdcc%22%7D%7D

Wireframe exhibit - https://lux-front-dev.collections.yale.edu/view/activity/6e09857c-6b08-4155-a3b9-c7055d688d92
![image](https://github.com/project-lux/lux-frontend/assets/160149818/3f16e5f4-1e69-465e-9576-434d1ef295e0)

Example search exhibit: https://lux-front-dev.collections.yale.edu/view/results/concepts?q=%7B%22subjectOfConcept%22%3A%7B%22carriedBy%22%3A%7B%22memberOf%22%3A%7B%22usedForEvent%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Factivity%2F6e09857c-6b08-4155-a3b9-c7055d688d92%22%7D%7D%7D%7D%7D

**Comment by jffcamp** [comment]
@clarkepeterf - requires HAL Link ticket for Related Subjects

**Comment by jffcamp** [comment]
@kamerynB - per the mock, this accordion is supposed to have Show all # results on the right side.
Can this be added as a Hot Fix or added to the next milestone?

**Comment by prowns** [comment]
Leaving OPEN following 3/4 deployment; moving back to on Deck.  @kamerynB - is any further front-end work needed here?

**Comment by kamerynB** [comment]
@prowns There shouldn't be any frontend work required. Unless the HAL link name changes the change on the frontend will be visible once the HAL link is updated on the middletier.

**Comment by roamye** [comment]
@kamerynB @prowns  should this be on the 04/01 milestone? 

Also HAL link is checked off but I can't find the middle-tier tix for it on the issue or in the middle tier repo.

**Comment by prowns** [comment]
Propose close - replaced by https://github.com/project-lux/lux-frontend/issues/180

**Comment by roamye** [comment]
closing as this ticket is replaced by [#180 ](https://github.com/project-lux/lux-frontend/issues/180)
