### ISSUE TITLE
Enable schema.org structured data markup for Google (from 1975)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-frontend#72]
### Problem Description
We need to provide a schema.org markup for Google search results to show rich description of each page.

### Expected Behavior/Solution
- Each LUX page will provide schema.org data for the Google crawler to process.

### Requirements
- Mapping provided by @rs2668: https://deploy-preview-540--linked-art.netlify.app/cookbook/mappings/schema.org/

### Needed for promotion
If an item on the list is not needed, it should be crossed off but not removed.

- [x] Wireframe/Mockup - Heather - N/A
- [ ] Committee discussions - Sarah
- [ ] Feasibility/Team discussion - Sarah
- [x] Backend requirements - N/A
- [ ] Frontend requirements- TBD
- [ ] Questions
  - *List of questions for discussions. Answers should be documented within the issue.*

### UAT/LUX Examples

*Example endpoints from LUX to use for development and testing, if applicable*

### Dependencies/Blocks

- Blocked By
  - https://git.yale.edu/lux-its/lux-web/issues/1976 (old tix) 
  - https://github.com/project-lux/lux-frontend/issues/73 (new tix) 
- Blocking
  - https://git.yale.edu/lux-its/lux-web/issues/1687
  - new tix: https://github.com/project-lux/lux-frontend/issues/24

### Related Github Issues

*Issues that contain similar work but are not blocking or being blocked by the current issue.*

### Related links
- [Introduction to structured data markup in Google Search](https://developers.google.com/search/docs/appearance/structured-data/intro-structured-data)
- [Generate structured data with JavaScript](https://developers.google.com/search/docs/appearance/structured-data/generate-structured-data-with-javascript)
- [Rich Results Test](https://search.google.com/test/rich-results)

### Wireframe/Mockup
N/A

**Comment by jffcamp** [comment]
Ok to close
