### ISSUE TITLE
Test out schema.org markups (from 1976)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-frontend#73]
### Problem Description
We need to make sure Google crawler/search does what we expect it to do with LUX - that is, show the information we provide in Google search results.

### Expected Behavior/Solution
We will set up a test website and ask Google to crawl it, and Google Search should show the results we want.

### Requirements
- Test if Google can process schema.org markup that is produced asynchronously with JavaScript, as is the case for LUX.

### Needed for promotion
*If an item on the list is not needed, it should be crossed off but not removed.*

- [x] Wireframe/Mockup - Heather - N/A
- [ ] Committee discussions - Sarah
- [ ] Feasibility/Team discussion - Sarah
- [x] Backend requirements - N/A
- [x] Frontend requirements- N/A
- [ ] Questions
  - *List of questions for discussions. Answers should be documented within the issue.*

### UAT/LUX Examples
*Example endpoints from LUX to use for development and testing, if applicable.*

### Dependencies/Blocks

- Blocked By: *Issues that are blocking the completion of the current issue.*
- Blocking: https://git.yale.edu/lux-its/lux-web/issues/1975

### Related Github Issues

*Issues that contain similar work but are not blocking or being blocked by the current issue.*

### Related links

*These links can consist of resources, bugherds, etc*

### Wireframe/Mockup
N/A

**Comment by roamye** [comment]
Per ticket forming: Propose-close.

**Comment by jffcamp** [comment]
Ok to close
