### ISSUE TITLE
Add accordion for groups founded  (from 1992)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-frontend#74]
**Problem Description:**
A group that was founded by a person is not linked on the person's page.

**Expected Behavior/Solution:**
Add an accordion to show groups that were founded by a person on the person page.

**Requirements:**

- [x] Add config

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [x] Wireframe/Mockup - Heather
- [ ] ~Committee discussions - Sarah~
- [ ] ~Feasibility/Team discussion - Sarah~
- [x] Backend requirements - Peter is creating a HAL link per the linked ML issue below
- [x] Frontend requirements - Kameryn
- [ ] ~Questions~

**UAT/LUX Examples:**

- [Steve Wozniak](https://lux-front-dev.collections.yale.edu/view/person/ae825eb3-ae9e-4359-bb73-814937bd71db)

**Dependencies/Blocks:**
- [ HAL Link - Agent Founded By Agent (from 123) #16](https://github.com/project-lux/lux-middletier/issues/16)
[Old Ticket - 123](https://git.yale.edu/lux-its/lux-backend/issues/123)
 
**Related Github Issues:**
N/A

**Related links:**
Bugherd: https://www.bugherd.com/projects/284041/tasks/1869

**Wireframe/Mockup:**
![image](https://github.com/project-lux/lux-frontend/assets/160149818/14279ad2-44cb-4f6b-8469-e6ac9fe5ee96)

**Comment by roamye** [comment]
Approved per UAT

**Comment by roamye** [comment]
Looks good in prod, closing.
