### ISSUE TITLE
data not appearing in front end of the works page DUMMY AR (from 2005)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-frontend#75]
**Problem Description:**
Information should appear under  'Works.2023;' as there is data in the backend but nothing appears in the front end. 

**Expected Behavior/Solution:**
Information on 'works.2023;' should appear below it instead of a blank page. 

**Requirements:**
TBD

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [ ] Wireframe/Mockup - Heather
- [ ] Committee discussions - Sarah
- [ ] Feasibility/Team discussion - Sarah
- [ ] Backend requirements - TBD
- [ ] Frontend requirements- TBD
- [ ] Questions
- List of questions for discussions. Answers should be documented within the issue.

**UAT/LUX Examples:**

https://lux-front-sbx.collections.yale.edu/view/text/767dd2a2-1a54-4d7c-b0b6-78e4d9061c74

**Dependencies/Blocks:**

- Blocked By: Issues that are blocking the completion of the current issue.
- Blocking: Issues being blocked by the completion of the current issue.

**Related Github Issues:**

- Issues that contain similar work but are not blocking or being blocked by the current issue.

**Related links:**

https://www.bugherd.com/projects/284041/tasks/1887

**Wireframe/Mockup:**
Place wireframe/mockup for the proposed solution at end of ticket.

**Comment by kamerynB** [comment]
I think this can be closed as this was fixed?? Maybe I forgot to move it?? @prowns @jffcamp Please confirm that this can be closed.

**Comment by prowns** [comment]
fixed.
