### ISSUE TITLE
Create parameterization of imported scripts  (from 2015)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-frontend#77]
**Problem Description:**
SI (and google analytics, and various Yale-specific meta tags) is hardcoded into the main page of LUX. If we migrate this to the public repo other university's will have access to Yale information, which we do not want. 

**Expected Behavior/Solution:**
create the ability to substitute scripts/meta tags into the index.html (home page of lux) 

**Requirements:**
substituting the script

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

~~- [ ] Wireframe/Mockup - Heather~~
~~- [ ] Committee discussions - Sarah~~
~~- [ ] Feasibility/Team discussion - Sarah~~
- [ ] Backend requirements - TBD
- [ ] Frontend requirements- TBD
- [ ] Questions
- List of questions for discussions. Answers should be documented within the issue.

**UAT/LUX Examples:**
https://github.com/project-lux/lux-frontend/tree/main/client/public should only contain a `uv/` folder and `index.html.template`

**Dependencies/Blocks:**
N/A

**Related Github Issues:**
- #78 

**Related links:**
N/A

**Wireframe/Mockup:**
N/A

**Comment by clarkepeterf** [comment]
Comments from the old repo -

**Peter's idea**:
The goal of this ticket is to remove all of the Yale-specific scripts, icons, meta tags, etc. from the index.html and make it configurable for consumers of the open source repo.

I have one proposal: what if we remove index.html from the repo (and add to .gitignore), then create an example index.html that looks like the one below. Then anyone who uses the repo is free to customize in whatever way they want. How do you like that idea?

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Place your <title>, <style>, <meta>, <link>, and <script> tags here -->
  </head>
  <body>
    <noscript>You need to enable JavaScript to run this app.</noscript>
    <-- Place your optional additional elements here -->
    <-- div with id="root" is necessary for React -->
    <div id="root"></div>
  </body>
</html>
```

**Seong's response**:
It makes sense but it doesn't seem like a simple thing to do: we have to think about

- is there code dependent on those optional index.html entires?
- where to maintain yale specific resources (each HTML tag or index.html as a whole, icons, etc.), e.g. a separate yale git repo
- how to generate yale index.html easily for both local development and CI deployment
- whether we should go as far as implementing a theme or plugin mechanism

**Comment by kamerynB** [comment]
@clarkepeterf @gigamorph We can use parameters in index.html that use environment variables. For example, for SiteImprove, instead of having:

```
<script async src="https://siteimproveanalytics.com/js/siteanalyze_66356571.js"></script>
```

It would be:
```
<script async src=%REACT_APP_SITE_ANALYTICS%></script>
```

**Comment by clarkepeterf** [comment]
Decision from meeting with Rob, Seong, and Peter:

- Use a index.html.template file (with contents below)
- add index.html to .gitignore.
- Users of the codebase will be required to create their own index.html, and can use the template as a starting point.
- Add documentation explaining that creating index.html is required
- The Yale-Specific index.html and resources will be moved into a separate repository and incorporated at build time. Other users of the repository can do something similar

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Place your <title>, <style>, <meta>, <link>, and <script> tags here -->
  </head>
  <body>
    <noscript>You need to enable JavaScript to run this app.</noscript>
    <-- Place your optional additional elements here -->
    <-- div with id="root" is necessary for React -->
    <div id="root"></div>
  </body>
</html>
```

**Comment by prowns** [comment]
Blocked - pending conversation regarding need to hook up multiple git repos to Jenkins.  @gigamorph to follow up with ITS team.

**Comment by clarkepeterf** [comment]
Also removing other public resources (e.g. opengraph.png, favicon.ico) and moving to Internal frontend-resources repo

**Comment by roamye** [comment]
Approved per UAT

**Comment by roamye** [comment]
Looks good in prod, closing.
