### ISSUE TITLE
Create event tracking abstraction  (from 2016)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-frontend#78]
**Problem Description:**
Currently the event logging function includes Siteimprove specific code and we want to make it extensible for other university's.

**Expected Behavior/Solution:**
Event logging function will no longer include Siteimprove specific code and will have a placeholder for where university's can add the software of their choice. 

**Requirements:**
Siteimprove specific event code is replaced with generic events code. 

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

~~- [ ] Wireframe/Mockup - Heather~~
~~- [ ] Committee discussions - Sarah~~
~~- [ ] Feasibility/Team discussion - Sarah~~
~~- [ ] Backend requirements - TBD~~
~~-[ ] Frontend requirements- TBD~~
~~- [ ] Questions~~

**UAT/LUX Examples:**
What it currently looks like: 
```
pushSiteImproveEvent(
  'Results Tab',
  'Selected',
  tabToLinkLabel[key],
)
```

What it should look like: 
```
pushClientLogs(
  'Results Tab',
  'Selected',
  tabToLinkLabel[key],
)
```

**Dependencies/Blocks:**
N/A

**Related Github Issues:**
- #77 
- Meta issue: #51

**Related links:**
SI Support Tix: https://help.siteimprove.com/support/tickets/3201927

**Wireframe/Mockup:**
N/A

**Comment by jffcamp** [comment]
From the original ticket: 
All of the events scattered through the code call into pushSiteImproveEvent(), which is a single function imported from a separate file. So we can just rename the function to pushClientLogs(). Consumers can just update the single function pushClientLogs() to integrate with whatever event tracking system they like.

**Comment by clarkepeterf** [comment]
Decision from meeting with Rob, Seong, and Peter:

Similar to decision from #77 
- Use a pushClientEvent.ts.template file with an empty function
- add pushClientEvent.ts to .gitignore.
- Users of the codebase will be required to create their own pushClientEvent.ts, and can use the template as a starting point.
- Add documentation explaining that creating pushClientEvent.ts is required
- The Yale-specific code currently in src/lib/siteImprove.ts will be moved into a separate repository and incorporated at build time. Other users of the repository can do something similar

**Comment by prowns** [comment]
Blocked - pending conversation regarding need to hook up multiple git repos to Jenkins. @gigamorph to follow up with ITS team.

**Comment by clarkepeterf** [comment]
This can follow the example for #77, but not enough time to get this change into this release. Pushing to next release

**Comment by roamye** [comment]
@clarkepeterf is there any way to verify the UAT? or is this done by the developers only?

**Comment by roamye** [comment]
@kamerynB so it is unreviewable? or are you saying it should be pushed to a different milestone?

**Comment by kamerynB** [comment]
@roamye Both. I just moved it to the latest milestone. When this change is pushed with the 6/10 milestone, we would just want to ensure Site Improve tracking works the same exact way it did before implementing this.

**Comment by prowns** [comment]
Per @jffcamp - At SI last meeting: SI is developing event abstraction at their level. Next step - contact SI to see what is planned, when, and then decide if this ticket is still needed.  May be able to remove event tracking (not mandatory, but can be done).  

@roamye will start support ticket with SI.

**Comment by roamye** [comment]
Support tix has been made: https://help.siteimprove.com/support/tickets/3201927

and @kamerynB has been CC'd on it.

**Comment by kamerynB** [comment]
@roamye @jffcamp @prowns Propose that this be closed as it can't be reviewed. The site improve tracking should behave the same as it did before this change.

**Comment by roamye** [comment]
Approved by UAT

**Comment by roamye** [comment]
Unreviewable in UAT - Closing.
