### ISSUE TITLE
Hierarchy should not render in archives if the current entity has no parent(s) and children (from 2018)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-frontend#79]
**Problem Description:**
Within the explore section there is a deadlink. If you click on the link it will leave you on the same page since the link refers to itself. This happens because the front end is not checking if the current entity has both parents and children. 

**Expected Behavior/Solution:**
The hierarchy will not render if there are no parents or children of the current entity.

**Requirements:**

- [x] Update the hierarchy to check if the current entity has parents and children before rendering the hierarchy

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [x] Wireframe/Mockup - Kam
- [ ] ~Committee discussions - Sarah~
- [ ] ~Feasibility/Team discussion - Sarah~
- [ ] ~Backend requirements - N/A~
- [x] Frontend requirements - Kam
- [ ] ~Questions~

**UAT/LUX Examples:**
What it looks like now: https://lux-front-sbx.collections.yale.edu/view/set/ff564a7e-b7be-4665-a872-c688e346c499
https://lux.collections.yale.edu/view/set/ff564a7e-b7be-4665-a872-c688e346c499 (prod) 

**Dependencies/Blocks:**
N/A

**Related Github Issues:**
N/A

**Related links:**
Bugherd - https://www.bugherd.com/projects/284041/tasks/1876

**Wireframe/Mockup:**
Current:
![image](https://github.com/project-lux/lux-frontend/assets/160149818/7e16430c-3c99-4a95-822f-8216767516b0)

Expected:
The hierarchy will not render.
![Screenshot 2024-03-21 at 2 37 57 PM](https://github.com/project-lux/lux-frontend/assets/140102078/351bb9b2-02ce-47cf-8d38-322ee890476e)

**Comment by kamerynB** [comment]
Update 2/23/24: Still determining a fix for this on the frontend.

**Comment by roamye** [comment]
Closing, looks good in prod.
