### ISSUE TITLE
Change the parsing of the data for the View this item links on event pages (from 2028)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-frontend#83]
**Problem Description:**
The frontend is not parsing the links for `View this item on the <unit name> website` on event pages. In some cases the unit name does not match the destination of the link.

**Expected Behavior/Solution:**
The frontend should read the data provided in `subject_of > digitally_carried_by > identified_by > content` to render the text for the link and the link will be retrieved from `subject_of > digitally_carried_by > access_point > id`.

"How Do I See It?" section will be removed and Web Pages will be added to the About section. (See wireframes below)

**Requirements:**

- [x] update the getLinktoUnitSite function in the EventParser
- [x] the How do I see it? section will be removed from events pages 
- [x] the web pages in the event data will appear alongside the About data

Example data to be parsed:
![image](https://github.com/project-lux/lux-frontend/assets/140102078/151c98bc-f123-4105-ac0a-ab0b75fdf5d2)

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [x] Wireframe/Mockup
- [ ] Committee discussions - Sarah
- [ ] Feasibility/Team discussion - Sarah
- [ ] Backend requirements - N/A
- [x] Frontend requirements- Kameryn
- [x] Questions
- Should this issue also include a discussion regarding the naming of the "How do I see it?" section on the events pages as mentioned in the attached Bugherd? ANSWER: The How do I see it section will be moved out of events pages and the web pages will instead be placed with the about data for the event in the same fashion as People about sections. The label containing bolded text saying "Web Pages" and the web pages listed below it.

**UAT/LUX Examples:**

- https://lux-front-tst.collections.yale.edu/view/activity/a36bcf00-699b-4ebc-bdc4-091568ce9858

**Dependencies/Blocks:**
N/A

**Related Github Issues:**
N/A

**Related links:**

- https://www.bugherd.com/projects/284041/tasks/1961

**Wireframe/Mockup:**
- What it looks like [now](https://lux-front-tst.collections.yale.edu/view/activity/a36bcf00-699b-4ebc-bdc4-091568ce9858): 
![image](https://github.com/project-lux/lux-frontend/assets/140102078/71363cbf-1b3c-40e6-a95e-60092a038edc)

- What it should look like ([Person Web Pages example](https://lux.collections.yale.edu/view/person/9ac41dd2-3702-4fa4-a65b-c53f681e7ec8)): 
![image](https://github.com/project-lux/lux-frontend/assets/140102078/bb2545ac-4584-48a3-a7eb-e6d58bb82e63)

**Comment by ar2674** [comment]
Approved per UAT

**Comment by prowns** [comment]
deployed
