### ISSUE TITLE
Update "Show More" to display all results instead of the first 20 (from 2030)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-frontend#84]
**Problem Description:**
Santiago is a child of Chile and should appear as a result under Explore -> Children. However, since there is a search cap limit of 20, this prevents Santiago from being displayed.  

**Expected Behavior/Solution:**
Shift to a "show all" search button option that executes a search when there are more than 5 results. Parents will be rendered in the component as the data is in the record. The Children Show All button will render the results page. This solution is needed for list view.  

**Requirements:**

- The default number of parents and children will be 5
- Both parent and children links will have their link attached to the text rather than to the "view" link. View link will be removed.
- Text will also need to reflect the color change of a link. 

For Parents:
- The Show More/Less button will render the next 5 parents or remove 5 parents as parent data is in the record

For Children
- The ~Show All X Children~ Show All X Child Results text link will redirect users to the results page to view all children
- There will be a < HR > to separate parents and child blocks

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [x] Wireframe/Mockup - Mike
- [x] Update wireframe wording to: **Show all X Child Results**
- [x] ~Committee discussions - Sarah~
- [x] ~Feasibility/Team discussion - Sarah~
- [x] ~Backend requirements - TBD~
- [x] Frontend requirements - Kam
- [x] ~Questions~

**UAT/LUX Examples:**

TST: https://lux-front-tst.collections.yale.edu/view/place/9f0772aa-e75e-490c-8f4d-5b2ccd41162a
PRD: https://lux.collections.yale.edu/view/place/9f0772aa-e75e-490c-8f4d-5b2ccd41162a

**Dependencies/Blocks:**
N/A

**Related Github Issues:**

**Related links:**
- https://www.bugherd.com/projects/284041/tasks/1922
- [Location in Lux tst](https://lux-front-tst.collections.yale.edu/view/results/places?q=%7B%22text%22%3A%22santiago%22%2C%22_lang%22%3A%22en%22%7D&sq=santiago)
- Example of [Santiago not listed as a children of Chile](https://lux-front-tst.collections.yale.edu/view/place/9f0772aa-e75e-490c-8f4d-5b2ccd41162a

**Wireframe/Mockup:**
Original: 
![image](https://github.com/project-lux/lux-frontend/assets/163148482/ebd5e04e-8f06-4682-a92b-5fd7e23eb627)

Updated: 
The bottom link will be displayed as "Show all X Child results"
![84](https://github.com/project-lux/lux-frontend/assets/98550395/2f3b9374-e353-46ed-8004-e69b0f1da66b)

**Comment by prowns** [comment]
@kamerynB - the consensus was that the button should align right to be in-line with the other "Show all X results" button on an entity page.  Since there is only the one button for showing children, it will match the layout of the top component.

**Comment by roamye** [comment]
@miketullo95 please see comment above for wireframe/mockup modifications.

**Comment by roamye** [comment]
this still needs an updated mockup @miketullo95

**Comment by kamerynB** [comment]
@roamye This should be all set now.

**Comment by roamye** [comment]
@kamerynB it originally had it under the childen list but per comment: https://github.com/project-lux/lux-frontend/issues/84#issuecomment-1984034322 it said it needed to be off to the right. I added a version where it is off to the right.

**Comment by kamerynB** [comment]
@roamye That doesn't make sense to the user though. That button corresponds to the list of children and that list of children _only_. It can cause confusion if the button is off to the right as it doesn't really correspond with anything when it is pushed to the right. The user will expect to see all the results, parents and children, when they select that button. 

Parents are currently rendered from the [record](https://lux-front-tst.collections.yale.edu/data/place/9f0772aa-e75e-490c-8f4d-5b2ccd41162a) in the `part_of` property. (screenshot below)

Children are rendered via the HAL link `placeParts` which gets this API call: https://lux-front-tst.collections.yale.edu/api/search/place? (screenshot below) q=%7B%22partOf%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fplace%2F9f0772aa-e75e-490c-8f4d-5b2ccd41162a%22%7D%7D.

Parent data:
![Screenshot 2024-04-15 at 11 29 46 AM](https://github.com/project-lux/lux-frontend/assets/140102078/e03974da-d157-4ab5-91af-452240e2d0f1)

Children data:
![Screenshot 2024-04-15 at 11 29 25 AM](https://github.com/project-lux/lux-frontend/assets/140102078/eb9bee63-607e-41d2-a33a-1d0c9f595a2e)

cc: @prowns

**Comment by roamye** [comment]
Thanks Kam, this will be brought up in tmmrs UAT @kamerynB

**Comment by roamye** [comment]
Per UAT,  we wanted to know if the following mockup/FE changes were possible: 

- Can we put a visual separator between parents & children? (should be address with https://github.com/project-lux/lux-frontend/issues/25) 
- Can button be next to the Children? Such as 
- Children [Show all X Children]
  - Biobio
  - Tirana
  - etc

- Names under children and parents should be linked. This would remove the [view] next to each place. 
   - Ex: Argentina [[view](https://lux.collections.yale.edu/view/place/9e73910b-a8fc-47aa-9246-dcc1191310ee)] -> [Argentina](https://lux.collections.yale.edu/view/place/9e73910b-a8fc-47aa-9246-dcc1191310ee)
- Have "show all" under the parents appear if it will show all results after selection. Have "show more" results if it will not show all results after selection. 

cc: @prowns

**Comment by roamye** [comment]
From discussion today the following changes will need to be made for the mockup: 
- The "show more" link will continue to stay under the Parents section as it is currently pictured in the Mock. 
- The "Show All" button will be replaced to reflect as a text link "Show all X children results". Similar to the text link in Concepts Influenced [accordion](https://lux.collections.yale.edu/view/person/34f4eec7-7a03-49c8-b1be-976c2f6ba6ba).  It will also be under the children's list.  d Put show all X Children results under list (as bold text, not a button)
- Will need updated wireframe to show <HR> and placement of links, also change of links to color 
@miketullo95 

I have also added these to the req above.

**Comment by miketullo95** [comment]
mocks updated per last comment by @roamye and new requirements. One very small thing, i couldn't get the exact style of an indented bulleted item. If you look at lux the bullet is empty in the center and in figma the only style allowed is a filled bullet. Hopefully that shouldnt be an issue with UAT.

**Comment by roamye** [comment]
the req's commented above were also listed in the req section of the issue where it went into more detail of what was needed. 

There are a couple of things missing:
- there needs to be a  <hr> line to separate the children from the parents. 
- Text will also need to reflect the color change of a link. Meaning, we are removing the [View] next to the text as the text will now be a link. 

Apologies I should have made it more clear that these were also listed in the req section of the issue + what the color change of a link meant. 

Let me know if u have any questions.

cc: @miketullo95 @prowns

**Comment by miketullo95** [comment]
@roamye wireframes fixed :)

**Comment by prowns** [comment]
5/2 Per UAT: Show all X Child results.

**Comment by prowns** [comment]
@kamerynB - can you remove the brackets from [Show all] under parents as a hotfix?

**Comment by roamye** [comment]
Approved by UAT with the removal of the brackets from [Show all]. Should display as `Show all` rather than `[Show all]` for consistency.

**Comment by roamye** [comment]
Closing as it looks good in PROD, will need to create a tix to update the [show more] as the brackets are not needed. will link this ticket to the new tix once it is created.
