### ISSUE TITLE
Provide context for results under About/Depicts sections (from 2032)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-frontend#86]
**Problem Description:**
The About section does not provide users context on whether the results is an object, work, person, place, etc... which makes it hard to identify what the search result is before clicking the link. 

**Expected Behavior/Solution:**
Display the results in a manner that includes concepts and objects within the list as a result.    The functionality should match #2031.  Show five results cards, with a show all option. Result card should show icons.  ~Possibly group the results by type.~

**Requirements:**
- Results shall include context such as concepts and objects. 

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [x] Wireframe/Mockup - Mike
- [x] Update Mockup - Mike
- [ ] ~Committee discussions - Sarah (likely core team or Interactions)~
- [x] Locate additional examples to UAT: People, Events, Places, Works
- [ ] ~Feasibility/Team discussion - TBD~
- [ ] ~Backend requirements - TBD~
- [ ] ~Frontend requirements- TBD~
- [ ] Questions
- List of questions for discussions. Answers should be documented within the issue.

**UAT/LUX Examples:**
Should see icons under about on each of these
- [Example with Objects](https://lux-front-tst.collections.yale.edu/view/text/3da53ad9-478e-4395-b27a-71ad1520f5c5)
- [Example with Works](https://lux-front-tst.collections.yale.edu/view/text/9c795ff6-0aa8-45a0-910a-ae6581df75ef)
- [Example with People & Groups](https://lux-front-tst.collections.yale.edu/view/visual/bd1512c0-f8ae-4d5a-afc0-8243ad6807f0)
- [Example with Places](https://lux-front-tst.collections.yale.edu/view/visual/51e142d8-799a-4178-8706-4435253a355c)
-  [Example with Concepts](https://lux-front-tst.collections.yale.edu/view/text/3da53ad9-478e-4395-b27a-71ad1520f5c5)
-  [Example with Events](https://lux-front-tst.collections.yale.edu/view/text/3da53ad9-478e-4395-b27a-71ad1520f5c5) - show all, last item

**Dependencies/Blocks:**

**Related Github Issues:**
- https://github.com/project-lux/lux-frontend/issues/85

**Related links:**
- https://www.bugherd.com/projects/284041/tasks/1972
- https://lux-front-tst.collections.yale.edu/view/text/3da53ad9-478e-4395-b27a-71ad1520f5c5

**Wireframe/Mockup:**
What it [looks like now](https://lux-front-tst.collections.yale.edu/view/text/3da53ad9-478e-4395-b27a-71ad1520f5c5): 
![image](https://github.com/project-lux/lux-frontend/assets/160149818/9ae32942-f548-4834-96e6-e21af1f8ed8d)

What it should look like: 
![86](https://github.com/project-lux/lux-frontend/assets/98550395/9a68c100-0710-4e69-badc-27097ff484bc)

**Comment by prowns** [comment]
From 2032:  @miketullo95-  Per UAT, we need an updated mock up. Either to show icons by the results or provide a one liner below the result. We cannot have the [Show all [num] results] within the about section.

**Comment by miketullo95** [comment]
@prowns updated mocks with icons. will note that with the current example we don't have people, events, works, and places examples. would need to confirm in testing that those icons work as well

**Comment by roamye** [comment]
Looks good in prod, closing.
