### ISSUE TITLE
Add Objects Influenced to people and group pages (from 2037)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-frontend#87]
**Problem Description:**
The person page is missing ~Objects Influenced~ Influenced Creation Of.

**Expected Behavior/Solution:**
Based on discussion with @jffcamp @azaroth42 

The data will be merged with exisiting HAL links to create tabs called:

"Objects Created or Encountered or Influenced By" and "Works Created, Published, or Influenced By"

**Requirements:**

1. The configuration for relatedObjectsAndWorks will include the config for concepts influenced.

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [x] Wireframe/Mockup - Mike
- [ ] ~Committee discussions - Sarah~
- [ ] ~Feasibility/Team discussion - Sarah~
- [x] Backend requirements - Peter, HAL link
- [x] Frontend requirements- TBD
- [ ] ~Questions~

**UAT/LUX Examples:**

- https://lux-front-tst.collections.yale.edu/view/person/0573429b-32ef-4a42-99e6-fd4b382d7e8e
  - Should show this: https://lux.collections.yale.edu/view/object/8de540c0-64cc-4abb-b253-dc5d0062544a

- https://lux-front-tst.collections.yale.edu/view/person/bf461170-26c9-4c95-b72e-63fdd47a8746
  - Should have more Objects Created/Encountered/Influenced and same for Works Created/Published/Influenced compared to PRD (greater numbers)

**Dependencies/Blocks:**

- Blocked By: https://github.com/project-lux/lux-middletier/issues/27 - @clarkepeterf 
which is blocked by: https://github.com/project-lux/lux-marklogic/issues/65

**Related Github Issues:**
N/A

**Related links:**

- Bugherd: https://www.bugherd.com/projects/284041/tasks/1943
- Bugherd: https://www.bugherd.com/projects/284041/tasks/2270

**Wireframe/Mockup:**
Expected layout:
NOTE: The label(s) will be "Objects Created or Encountered or Influenced By" and "Works Created, Published, or Influenced By" rather than `Objects Influenced`.
![image](https://github.com/project-lux/lux-frontend/assets/118475196/2b5f1af5-dd1a-4181-a9f7-b3e612737a6d)

**Comment by ar2674** [comment]
Per UAT: Needs a new title for the tab: Influenced Creation Of rather Objects Influenced @kamerynB @miketullo95

**Comment by kamerynB** [comment]
@ar2674 This doesn't need a wireframe update. We can just update the ticket to include that.

cc: @jffcamp @prowns

**Comment by clarkepeterf** [comment]
@prowns @jffcamp @roamye there are actually two new HAL links, one for Objects Influenced and one for Works Influenced. Can these be two separate tabs and how should we call them? The title `Influenced Creation Of` could apply to either Objects or Works, but since they are separate tabs we need two names

**Comment by clarkepeterf** [comment]
@jffcamp @azaroth42 based on our conversation I'm moving forward with the following:

The data will be merged with exisiting HAL links to create tabs called:

"Objects Created or Encountered or Influenced By" and "Works Created, Published, or Influenced By"

**Comment by roamye** [comment]
Approved by UAT

**Comment by roamye** [comment]
Looks good in PROD. Closing.
