### ISSUE TITLE
Events: Expose Related Locations Accordion (from 403)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-frontend#9]
**Problem description:** 
Related Locations information is missing from events.

**Expected behavior:** 
For any event show related locations through the objects/works that were part of the exhibition or Activity.  This will include locations for Objects used in the set for this Event (exhibition) or Locations for Works about this Event/Period

**Requirements:**
Events, such as, [Everything is Dada](https://lux-front-tst.collections.yale.edu/view/activity/36c39534-5908-4297-979a-194d5fd4a8b7),  will contain related locations with information of...
- Where the Objects used in the event were **created** from...  Example: ([Premiere Nut creation is USA](https://lux-front-tst.collections.yale.edu/view/activity/36c39534-5908-4297-979a-194d5fd4a8b7)) 
- I think the last bullet meant to reference ([Premiere Nuit creation is USA](https://lux-front-dev.collections.yale.edu/view/object/c035ab33-4695-4999-822b-286cc78d8f67)) 
- Where the Objects used in the event were **encountered** from... Example: TBD as we do not have YPM exhibit info. But eventually it would be Nebraska. 

Where the works used in the event such as [Monolith](https://lux-front-tst.collections.yale.edu/view/visual/4d19d3cc-5d7b-432e-a888-6baad294d451) contains
- the aboutness/depicts.. Example: [Yosemite Valley](https://lux-front-dev.collections.yale.edu/view/activity/3b5eb85d-c559-4784-9c3c-e6db75ac7f50)  
- published... Example: TBD. Need YUL exhibition data. 

**Needed for Completion:**
- [x] Updated mockup
- [x] Facet HAL Link - middle tier ticket - Peter (https://github.com/project-lux/lux-middletier/issues/45) - unformed
- [x] Marklogic ticket - Peter (TBD)
- [x] Wireframe - Mike
- [x] Examples/Links

**UAT Examples:**
- https://lux-front-dev.collections.yale.edu/view/activity/d8de5723-0473-4727-b6ee-e6e0ab904905

**Related:** 
#56 (important)

**Dependencies/Blocks:**
- [ ] Blocked by: https://github.com/project-lux/lux-middletier/issues/45

**Wireframe:**
![9](https://github.com/project-lux/lux-frontend/assets/98550395/f4963da5-a3e1-4871-b8bf-21d8a5724697)

When Object and Work results are available, they should be rendered as such (note that this example is from Related Concepts on Andy Warhol person page, not a mockup of this content):
![image](https://github.com/project-lux/lux-frontend/assets/140099762/24ab82cf-a31e-418b-8f4d-6670beabb873)

**Comment by jffcamp** [comment]
@clarkepeterf - requires HAL Link ticket

**Comment by prowns** [comment]
Faceted search, so mock needs to be updated to show:|

Related Locations

- Place --- Show All
 - Object Encountered Here
 - Object Created Here
 - Work Published Here
 - Work Created Here

**Comment by miketullo95** [comment]
updated wireframe with a new accordion labeled "related locations" on an event page @prowns

**Comment by prowns** [comment]
@miketullo95 - it's not a straight list, but needs to be in this format.  Take a look at the top scope for examples on how this should be worded for these examples.    To get the data, go to the WORKS page for each of the objects used in [This Exhibition](https://lux-front-dev.collections.yale.edu/view/activity/d8de5723-0473-4727-b6ee-e6e0ab904905), and use each Place listed in the Depicts list as a "Related Locations" using the syntax/layout at top (to match this screen shot).

![image](https://github.com/project-lux/lux-frontend/assets/140099762/9f29616f-223a-479f-b3d1-420e319d9600)

**Comment by roamye** [comment]
Wording needs to be Related Locations for the accordion header. @miketullo95

**Comment by roamye** [comment]
@miketullo95 @prowns I have added the template for the related list accordion under wireframes.

**Comment by miketullo95** [comment]
@prowns wireframe updated

**Comment by roamye** [comment]
Approved per UAT

**Comment by roamye** [comment]
Closing as it looks good in prod.
