### ISSUE TITLE
Remove identifiers from events pages (from 2058)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-frontend#93]
**Problem Description:**
The frontend renders identifiers on event pages.

**Expected Behavior/Solution:**
The events pages should not have identifiers rendered.

**Requirements:**

- [ ] Remove record identifiers from event pages

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [ ] ~Wireframe/Mockup - Mike~
- [ ] ~Committee discussions - Sarah~
- [ ] ~Feasibility/Team discussion - Sarah~
- [ ] ~Backend requirements - TBD~
- [x] Frontend requirements - Kam
- [ ] ~Questions~

**UAT/LUX Examples:**

- https://lux-front-tst.collections.yale.edu/view/activity/d39ecdf7-1261-4ecf-9187-e3629a614e4f

**Dependencies/Blocks:**
N/A

**Related Github Issues:**
N/A

**Related links:**

- Bugherd: https://www.bugherd.com/projects/284041/tasks/2000

**Wireframe/Mockup:**
Current display:
![Image](https://github.com/project-lux/lux-frontend/assets/140102078/f1f0fc5a-ba1d-475d-9c47-26451e9c6aac)

Expected display:
![Image](https://github.com/project-lux/lux-frontend/assets/140102078/5793c471-5c84-418c-8fde-12e861c04ca8)

**Comment by prowns** [comment]
Per UAT -
This is not a front-end issue - YCBA should not vend these identifiers if they don't want them to show.   @kkdavis14

**Comment by kkdavis14** [comment]
fair enough. https://git.yale.edu/LUX/unit-data/issues/95

**Comment by prowns** [comment]
closing. unit-data issue.
