### ISSUE TITLE
Thumbnails for Works Results (from 2064)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-frontend#96]
**Problem Description:**
At the moment, we do not have thumbnails for Works result lists.

**Expected Behavior/Solution:**
Image should appear in the thumbnail Works results, using the same IIIF thumbnail components and UI as on objects pages. 

**Requirements:**
- Image within the Works record will also appear in the thumbnail of the Works results. 

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [ ] ~Wireframe/Mockup - Mike~
- [ ] ~Committee discussions - Sarah~
- [ ] Feasibility/Team discussion - Sarah
- [ ] Backend requirements - TBD
- [ ] Frontend requirements- TBD
- [ ] Questions
- List of questions for discussions. Answers should be documented within the issue.

**UAT/LUX Examples:**
What it looks like [now](https://lux-front-tst.collections.yale.edu/view/results/works?q=%7B%22AND%22%3A%5B%7B%22text%22%3A%22hadleigh%22%2C%22_lang%22%3A%22en%22%7D%2C%7B%22text%22%3A%22castle%22%2C%22_lang%22%3A%22en%22%7D%5D%7D&sq=hadleigh%20castle): 
![image](https://github.com/project-lux/lux-frontend/assets/160149818/a3ca8f47-3a0e-4db9-9fe1-76c8aaf608e0)

what it should look like: 
should have image within the thumbnail as o[bjects](https://lux-front-tst.collections.yale.edu/view/results/objects?q=%7B%22AND%22%3A%5B%7B%22text%22%3A%22hadleigh%22%2C%22_lang%22%3A%22en%22%7D%2C%7B%22text%22%3A%22castle%22%2C%22_lang%22%3A%22en%22%7D%5D%7D&sq=hadleigh+castle) does; 

**Dependencies/Blocks:**

**Related Github Issues:**

**Related links:**

- https://www.bugherd.com/projects/284041/tasks/1844
- https://www.bugherd.com/projects/284041/tasks/2019

**Wireframe/Mockup:**
Place wireframe/mockup for the proposed solution at end of ticket.

**Comment by kamerynB** [comment]
@prowns @azaroth42 Both of you created the original bugherds. If I'm understanding this, the image to be displayed on the results page either comes from the Work record itself **OR** is the image coming from the object that carries the work, correct?

**Comment by prowns** [comment]
Discussed at 3/14 team mtg.  This would need to be a semantic query; what is compute cost of this specific feature.

This also re-raises the question of having IIIF images from LUX objects shown at all on Works pages.  Works Facet - Has Digital Image- will only find Works records with digital images (e.g., images from external sources/Wikidata only).  

For consideration/further discussion
- leave as is (wont fix)
- do not show thumbnails for any works results
- do we pull images down from Yale Visual Works records? 

[Dort Example](https://lux-front-tst.collections.yale.edu/view/results/works?q=%7B%22text%22%3A%22dort%22%2C%22_lang%22%3A%22en%22%7D&sq=dort ): Wikidata record has thumbnail image; YCBA visual image record does not.  This is from YCBA decision not to merge wikidata, so we end up with 2 records. YUL reconciles to wikidata record.

**Comment by prowns** [comment]
Per follow-up conversation with @azaroth42:  This issue stems from YUL reference to works via wikidata, and then LUX pulling in the data and image from that reference.   The thumbnail issue will affect all units where YUL refers to works via WD.  These will have thumbnails on works, and will return results for  "Has digital image" = YES facet.   

The recommendation is to close this ticket, with the understanding #62 will provide a link back to the referring record from these dead ends.
