### ISSUE TITLE
Definition of the current tab at the top of the Help text (from 2071)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-frontend#97]
**Problem Description:**
Currently there is no help text to define the current tab a user is on when doing an advanced search. 
[**Note:** There is help text to define the tabs of advanced search on the landing page, but that text does not describe the scope of the search, e.g. Objects. ]

**Expected Behavior/Solution:**
Add help text to define the current tab a user is on. 

**Requirements:**
- Help text must be added for each tab. (Objects, works. etc) 
- Help text must dynamically change dependent on what tab a user is in. (objects, works, etc) 
- Must be the first sentence under the Help box. 

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [ ] Wireframe/Mockup - Mike
- [ ] Committee discussions - Sarah
- [ ] Feasibility/Team discussion - Sarah
- [ ] Backend requirements - TBD
- [ ] Frontend requirements- TBD
- [ ] Questions
- List of questions for discussions. Answers should be documented within the issue.

**UAT/LUX Examples:**
What it looks like now: 
![image](https://github.com/project-lux/lux-frontend/assets/160149818/22c9eb5d-3c83-45fb-a680-1088fddfc504)

What it should look like: 
TBD - dependent on mike

**Dependencies/Blocks:**

**Related Github Issues:**

- Issues that contain similar work but are not blocking or being blocked by the current issue.

**Related links:**
- https://www.bugherd.com/projects/284041/tasks/1443

**Wireframe/Mockup:**
Place wireframe/mockup for the proposed solution at end of ticket.

**Comment by ar2674** [comment]
Closing as this issue was fixed by https://git.yale.edu/lux-its/lux-web/issues/1668
